-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_dimensions', 'dim_gl_account') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('gl_account_code') }} as gl_account_code,
        {{ fix_mojibake('gl_account_name') }} as gl_account_name,
        {{ fix_mojibake('account_class') }} as account_class,
        {{ clean_integer('gl_account_key') }} as gl_account_key,
        {{ fix_mojibake('normal_balance') }} as normal_balance,
        try_cast(is_pnl as boolean) as is_pnl
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
