-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_dimensions', 'dim_loyalty_member') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('loyalty_member_id') }} as loyalty_member_id,
        {{ clean_integer('loyalty_member_key') }} as loyalty_member_key,
        {{ fix_mojibake('tier') }} as tier,
        {{ clean_timestamp('joined_date') }} as joined_date,
        {{ clean_code('home_site_id') }} as home_site_id,
        try_cast(opt_in_marketing as boolean) as opt_in_marketing,
        try_cast(is_active as boolean) as is_active
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (loyalty_member_id is not null) as _dq_loyalty_member_id_present,
        (coalesce(_dq_loyalty_member_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_loyalty_member_id_present, false) then 'loyalty_member_id_present' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
