-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_dimensions', 'dim_route') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('route_id') }} as route_id,
        {{ clean_integer('route_key') }} as route_key,
        {{ clean_code('origin_terminal_id') }} as origin_terminal_id,
        {{ fix_mojibake('route_name') }} as route_name,
        {{ clean_measure('planned_distance_km') }} as planned_distance_km,
        {{ fix_mojibake('route_class') }} as route_class,
        {{ clean_integer('drop_count') }} as drop_count,
        {{ clean_measure('planned_duration_hours') }} as planned_duration_hours
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (route_id is not null) as _dq_route_id_present,
        (coalesce(_dq_route_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_route_id_present, false) then 'route_id_present' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
