-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_dimensions', 'dim_customer') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('customer_id') }} as customer_id,
        {{ clean_integer('customer_key') }} as customer_key,
        {{ fix_mojibake('customer_name') }} as customer_name,
        {{ fix_mojibake('sector') }} as sector,
        {{ fix_mojibake('segment') }} as segment,
        {{ clean_code('country_code') }} as country_code,
        {{ fix_mojibake('credit_band') }} as credit_band,
        {{ clean_measure('credit_limit_zar') }} as credit_limit_zar,
        {{ clean_integer('payment_terms_days') }} as payment_terms_days,
        {{ clean_timestamp('onboarded_date') }} as onboarded_date,
        try_cast(is_active as boolean) as is_active,
        {{ clean_measure('revenue_index') }} as revenue_index,
        {{ clean_timestamp('effective_from_date') }} as effective_from_date,
        {{ clean_timestamp('effective_to_date') }} as effective_to_date,
        try_cast(is_current as boolean) as is_current,
        {{ clean_integer('scd_version') }} as scd_version,
        {{ fix_mojibake('record_source') }} as record_source,
        {{ clean_timestamp('dw_load_ts') }} as dw_load_ts,
        {{ fix_mojibake('dw_hash_diff') }} as dw_hash_diff
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (customer_id is not null) as _dq_customer_id_present,
        (country_code is not null) as _dq_country_code_present,
        (credit_limit_zar >= 0) as _dq_credit_limit_zar_non_negative,
        (coalesce(_dq_customer_id_present, false) and coalesce(_dq_country_code_present, false) and coalesce(_dq_credit_limit_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_customer_id_present, false) then 'customer_id_present' end,
            case when not coalesce(_dq_country_code_present, false) then 'country_code_present' end,
            case when not coalesce(_dq_credit_limit_zar_non_negative, false) then 'credit_limit_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
