-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_dimensions', 'bridge_supplier_product') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('supplier_id') }} as supplier_id,
        {{ clean_code('product_id') }} as product_id,
        try_cast(is_approved as boolean) as is_approved
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (supplier_id is not null) as _dq_supplier_id_present,
        (product_id is not null) as _dq_product_id_present,
        (coalesce(_dq_supplier_id_present, false) and coalesce(_dq_product_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_supplier_id_present, false) then 'supplier_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
