-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_dimensions', 'dim_depot') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('depot_id') }} as depot_id,
        {{ clean_integer('depot_key') }} as depot_key,
        {{ fix_mojibake('depot_name') }} as depot_name,
        {{ clean_code('parent_terminal_id') }} as parent_terminal_id,
        {{ clean_code('country_code') }} as country_code,
        {{ clean_integer('storage_capacity_litres') }} as storage_capacity_litres,
        try_cast(serves_lpg as boolean) as serves_lpg,
        try_cast(serves_lubricants as boolean) as serves_lubricants
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (depot_id is not null) as _dq_depot_id_present,
        (coalesce(_dq_depot_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_depot_id_present, false) then 'depot_id_present' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
