-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_dimensions', 'dim_pump') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('pump_id') }} as pump_id,
        {{ clean_integer('pump_key') }} as pump_key,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_integer('pump_number') }} as pump_number,
        {{ clean_integer('nozzle_count') }} as nozzle_count,
        {{ clean_measure('flow_rate_lpm') }} as flow_rate_lpm,
        try_cast(supports_high_flow_diesel as boolean) as supports_high_flow_diesel
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (pump_id is not null) as _dq_pump_id_present,
        (site_id is not null) as _dq_site_id_present,
        (coalesce(_dq_pump_id_present, false) and coalesce(_dq_site_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_pump_id_present, false) then 'pump_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
