-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_dimensions', 'dim_unit_of_measure') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('uom_code') }} as uom_code,
        {{ fix_mojibake('uom_name') }} as uom_name,
        {{ fix_mojibake('uom_type') }} as uom_type,
        {{ clean_measure('base_conversion') }} as base_conversion,
        {{ clean_integer('uom_key') }} as uom_key
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
