-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_dimensions', 'dim_country') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('country_code') }} as country_code,
        {{ fix_mojibake('country_name') }} as country_name,
        {{ fix_mojibake('market_group') }} as market_group,
        {{ clean_measure('capital_latitude') }} as capital_latitude,
        {{ clean_measure('capital_longitude') }} as capital_longitude,
        {{ clean_integer('country_key') }} as country_key,
        {{ clean_code('currency_code') }} as currency_code,
        try_cast(is_home_market as boolean) as is_home_market
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (country_code is not null) as _dq_country_code_present,
        (coalesce(_dq_country_code_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_country_code_present, false) then 'country_code_present' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
