-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_dimensions', 'dim_tax') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('tax_code') }} as tax_code,
        {{ clean_integer('tax_key') }} as tax_key,
        {{ fix_mojibake('tax_name') }} as tax_name,
        {{ clean_measure('tax_rate') }} as tax_rate,
        {{ clean_measure('tax_cents_per_litre') }} as tax_cents_per_litre,
        {{ fix_mojibake('tax_type') }} as tax_type
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
