-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_dimensions', 'dim_city') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('city_name') }} as city_name,
        {{ fix_mojibake('province_name') }} as province_name,
        {{ clean_code('country_code') }} as country_code,
        {{ clean_measure('latitude') }} as latitude,
        {{ clean_measure('longitude') }} as longitude,
        {{ fix_mojibake('urban_class') }} as urban_class,
        try_cast(on_national_route as boolean) as on_national_route,
        {{ clean_integer('anchor_weight') }} as anchor_weight,
        {{ clean_integer('city_key') }} as city_key
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (country_code is not null) as _dq_country_code_present,
        (coalesce(_dq_country_code_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_country_code_present, false) then 'country_code_present' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
