-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_dimensions', 'dim_contract') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('contract_id') }} as contract_id,
        {{ clean_integer('contract_key') }} as contract_key,
        {{ clean_code('customer_id') }} as customer_id,
        {{ fix_mojibake('contract_type') }} as contract_type,
        {{ clean_timestamp('start_date', '1950-01-01', '2035-12-31') }} as start_date,
        {{ clean_timestamp('end_date', '1950-01-01', '2035-12-31') }} as end_date,
        {{ clean_measure('committed_volume_litres') }} as committed_volume_litres,
        {{ fix_mojibake('price_mechanism') }} as price_mechanism,
        {{ clean_measure('discount_cents_per_litre') }} as discount_cents_per_litre,
        {{ clean_timestamp('effective_from_date') }} as effective_from_date,
        {{ clean_timestamp('effective_to_date') }} as effective_to_date,
        try_cast(is_current as boolean) as is_current,
        {{ clean_integer('scd_version') }} as scd_version,
        {{ fix_mojibake('record_source') }} as record_source,
        {{ clean_timestamp('dw_load_ts') }} as dw_load_ts,
        {{ fix_mojibake('dw_hash_diff') }} as dw_hash_diff
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (contract_id is not null) as _dq_contract_id_present,
        (customer_id is not null) as _dq_customer_id_present,
        (coalesce(_dq_contract_id_present, false) and coalesce(_dq_customer_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_contract_id_present, false) then 'contract_id_present' end,
            case when not coalesce(_dq_customer_id_present, false) then 'customer_id_present' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
