-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_dimensions', 'dim_carrier') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('carrier_id') }} as carrier_id,
        {{ clean_integer('carrier_key') }} as carrier_key,
        {{ fix_mojibake('carrier_name') }} as carrier_name,
        try_cast(is_own_fleet as boolean) as is_own_fleet,
        {{ clean_integer('fleet_size') }} as fleet_size,
        {{ fix_mojibake('safety_rating') }} as safety_rating
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (carrier_id is not null) as _dq_carrier_id_present,
        (coalesce(_dq_carrier_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_carrier_id_present, false) then 'carrier_id_present' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
