-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_dimensions', 'dim_weather') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('weather_condition') }} as weather_condition,
        {{ clean_integer('weather_key') }} as weather_key,
        {{ clean_measure('demand_impact_pct') }} as demand_impact_pct
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
