-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_dimensions', 'dim_tank') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('tank_id') }} as tank_id,
        {{ clean_integer('tank_key') }} as tank_key,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_code('product_id') }} as product_id,
        {{ clean_integer('capacity_litres') }} as capacity_litres,
        {{ fix_mojibake('tank_material') }} as tank_material,
        {{ clean_integer('install_year') }} as install_year,
        try_cast(has_leak_detection as boolean) as has_leak_detection,
        try_cast(telemetry_enabled as boolean) as telemetry_enabled
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (tank_id is not null) as _dq_tank_id_present,
        (site_id is not null) as _dq_site_id_present,
        (product_id is not null) as _dq_product_id_present,
        (coalesce(_dq_tank_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_product_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_tank_id_present, false) then 'tank_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
