-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_bunker_deliveries') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('bunker_delivery_id') }} as bunker_delivery_id,
        {{ clean_timestamp('delivery_ts') }} as delivery_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('port_code') }} as port_code,
        {{ fix_mojibake('vessel_imo') }} as vessel_imo,
        {{ fix_mojibake('delivery_mode') }} as delivery_mode,
        {{ correct_unit_error(clean_measure('delivered_litres'), 60000) }} as delivered_litres,
        {{ clean_measure('pumping_rate_lpm') }} as pumping_rate_lpm,
        {{ clean_measure('delivery_hours') }} as delivery_hours,
        try_cast(bunker_delivery_note_signed as boolean) as bunker_delivery_note_signed,
        try_cast(quantity_dispute_raised as boolean) as quantity_dispute_raised,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (bunker_delivery_id is not null) as _dq_bunker_delivery_id_present,
        (delivery_ts is not null) as _dq_event_timestamp_valid,
        (delivered_litres >= 0) as _dq_delivered_litres_non_negative,
        (delivered_litres <= 60000) as _dq_delivered_litres_within_range,
        (coalesce(_dq_bunker_delivery_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_delivered_litres_non_negative, false) and coalesce(_dq_delivered_litres_within_range, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_bunker_delivery_id_present, false) then 'bunker_delivery_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_delivered_litres_non_negative, false) then 'delivered_litres_non_negative' end,
            case when not coalesce(_dq_delivered_litres_within_range, false) then 'delivered_litres_within_range' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so
-- the same business key can arrive more than once. Keep the
-- most recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by bunker_delivery_id order by ingested_at desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    bunker_delivery_id,
    delivery_ts,
    date_key,
    port_code,
    vessel_imo,
    delivery_mode,
    delivered_litres,
    pumping_rate_lpm,
    delivery_hours,
    bunker_delivery_note_signed,
    quantity_dispute_raised,
    source_system_code,
    ingested_at,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
