-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by charger_status_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_ev_charger_status') }}
    where _dq_is_valid
)

select
    charger_status_id,
    status_ts,
    date_key,
    ev_charger_id,
    site_id,
    status,
    is_available,
    is_faulted,
    error_code,
    temperature_celsius,
    firmware_version,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
