-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_pump_meter_readings') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by reading_id order by reading_ts desc) as _row_rank
    from source
),

renamed as (
    select
        reading_id,
        reading_ts,
        date_key,
        pump_id,
        site_id,
        product_id,
        totaliser_litres,
        litres_since_last_reading,
        meter_drift_pct,
        calibration_due,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
