-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_vehicle_safety_events') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('vehicle_safety_event_id') }} as vehicle_safety_event_id,
        {{ clean_timestamp('event_ts') }} as event_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('vehicle_id') }} as vehicle_id,
        {{ clean_code('driver_id') }} as driver_id,
        {{ fix_mojibake('event_type') }} as event_type,
        {{ fix_mojibake('severity') }} as severity,
        {{ clean_measure('speed_kph') }} as speed_kph,
        {{ clean_integer('speed_limit_kph') }} as speed_limit_kph,
        {{ clean_measure('g_force') }} as g_force,
        {{ clean_measure('latitude') }} as latitude,
        {{ clean_measure('longitude') }} as longitude,
        try_cast(resulted_in_incident as boolean) as resulted_in_incident,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (vehicle_safety_event_id is not null) as _dq_vehicle_safety_event_id_present,
        (event_ts is not null) as _dq_event_timestamp_valid,
        (coalesce(_dq_vehicle_safety_event_id_present, false) and coalesce(_dq_event_timestamp_valid, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_vehicle_safety_event_id_present, false) then 'vehicle_safety_event_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so
-- the same business key can arrive more than once. Keep the
-- most recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by vehicle_safety_event_id order by ingested_at desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    vehicle_safety_event_id,
    event_ts,
    date_key,
    vehicle_id,
    driver_id,
    event_type,
    severity,
    speed_kph,
    speed_limit_kph,
    g_force,
    latitude,
    longitude,
    resulted_in_incident,
    source_system_code,
    ingested_at,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
