-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_facts', 'fact_ev_charger_status') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('charger_status_id') }} as charger_status_id,
        {{ clean_timestamp('status_ts') }} as status_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('ev_charger_id') }} as ev_charger_id,
        {{ clean_code('site_id') }} as site_id,
        {{ fix_mojibake('status') }} as status,
        try_cast(is_available as boolean) as is_available,
        try_cast(is_faulted as boolean) as is_faulted,
        {{ clean_code('error_code') }} as error_code,
        {{ clean_measure('temperature_celsius') }} as temperature_celsius,
        {{ fix_mojibake('firmware_version') }} as firmware_version,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (charger_status_id is not null) as _dq_charger_status_id_present,
        (site_id is not null) as _dq_site_id_present,
        (status_ts is not null) as _dq_event_timestamp_valid,
        (coalesce(_dq_charger_status_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_event_timestamp_valid, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_charger_status_id_present, false) then 'charger_status_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so the
-- same business key can arrive more than once. Keep the most
-- recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by charger_status_id order by ingested_at desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    charger_status_id,
    status_ts,
    date_key,
    ev_charger_id,
    site_id,
    status,
    is_available,
    is_faulted,
    error_code,
    temperature_celsius,
    firmware_version,
    source_system_code,
    ingested_at,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
