-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by grid_flow_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_grid_import_export') }}
    where _dq_is_valid
)

select
    grid_flow_id,
    reading_ts,
    date_key,
    site_id,
    import_kwh,
    export_kwh,
    net_kwh,
    self_consumption_pct,
    load_shedding_stage,
    backup_generator_running,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
