-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_lpg_sales') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by lpg_sale_id order by sale_ts desc) as _row_rank
    from source
),

renamed as (
    select
        lpg_sale_id,
        sale_ts,
        date_key,
        site_id,
        customer_id,
        product_id,
        cylinder_type_code,
        quantity_kg,
        unit_price_zar,
        revenue_zar,
        cogs_zar,
        gross_margin_zar,
        channel,
        is_winter_peak,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
