-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_budget') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by budget_id order by period_date desc) as _row_rank
    from source
),

renamed as (
    select
        budget_id,
        period_date,
        date_key,
        budget_version_code,
        gl_account_code,
        cost_centre_code,
        business_unit_code,
        budget_amount_zar,
        budget_volume_litres,
        scenario_name,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
