-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_bunker_deliveries') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by bunker_delivery_id order by delivery_ts desc) as _row_rank
    from source
),

renamed as (
    select
        bunker_delivery_id,
        delivery_ts,
        date_key,
        port_code,
        vessel_imo,
        delivery_mode,
        delivered_litres,
        pumping_rate_lpm,
        delivery_hours,
        bunker_delivery_note_signed,
        quantity_dispute_raised,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
