-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_shop_sales') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by shop_line_id order by transaction_ts desc) as _row_rank
    from source
),

renamed as (
    select
        shop_line_id,
        basket_id,
        transaction_ts,
        date_key,
        time_key,
        site_id,
        product_id,
        quantity,
        unit_price_zar,
        gross_sales_zar,
        cogs_zar,
        gross_margin_zar,
        promotion_applied,
        payment_method,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
