-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by campaign_response_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_campaign_responses') }}
    where _dq_is_valid
)

select
    campaign_response_id,
    response_ts,
    date_key,
    campaign_id,
    digital_user_id,
    channel,
    was_delivered,
    was_opened,
    was_clicked,
    was_redeemed,
    incremental_spend_zar,
    attribution_model,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
