-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_general_ledger') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by journal_line_id order by posting_date desc) as _row_rank
    from source
),

renamed as (
    select
        journal_line_id,
        posting_date,
        date_key,
        journal_id,
        gl_account_code,
        account_class,
        cost_centre_code,
        profit_centre_code,
        legal_entity_code,
        debit_amount_zar,
        credit_amount_zar,
        signed_amount_zar,
        currency_code,
        document_type,
        is_reversal,
        fiscal_period,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
