-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_commercial_order_lines') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by order_line_id order by order_ts desc) as _row_rank
    from source
),

renamed as (
    select
        order_line_id,
        order_id,
        line_number,
        order_ts,
        date_key,
        customer_id,
        product_id,
        ordered_quantity,
        delivered_quantity,
        unit_price_zar,
        line_revenue_zar,
        line_status,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
