-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_cashflow') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by cashflow_id order by period_date desc) as _row_rank
    from source
),

renamed as (
    select
        cashflow_id,
        period_date,
        date_key,
        legal_entity_code,
        cashflow_category,
        inflow_zar,
        outflow_zar,
        net_cashflow_zar,
        closing_balance_zar,
        currency_code,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
