-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by transaction_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_retail_fuel_sales') }}
    where _dq_is_valid
)

select
    transaction_id,
    transaction_ts,
    date_key,
    time_key,
    site_id,
    product_id,
    pump_number,
    forecourt_lane,
    shift_name,
    litres,
    unit_price_zar,
    gross_sales_zar,
    cogs_zar,
    gross_margin_zar,
    payment_method,
    loyalty_flag,
    loyalty_member_id,
    is_fleet_sale,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
