-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by fleet_cost_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_fleet_costs') }}
    where _dq_is_valid
)

select
    fleet_cost_id,
    cost_date,
    date_key,
    vehicle_id,
    carrier_id,
    cost_type,
    amount_zar,
    kilometres_in_period,
    cost_centre_code,
    is_accrual,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
