-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_forecourt_shift') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by forecourt_shift_id order by business_date desc) as _row_rank
    from source
),

renamed as (
    select
        forecourt_shift_id,
        business_date,
        date_key,
        site_id,
        shift_name,
        supervisor_employee_id,
        attendants_on_duty,
        litres_dispensed,
        transaction_count,
        cash_declared_zar,
        cash_variance_zar,
        pump_downtime_minutes,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
