-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_commercial_deliveries') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by commercial_delivery_id order by ingested_at desc) as _row_rank
    from source
),

renamed as (
    select
        commercial_delivery_id,
        planned_delivery_ts,
        actual_delivery_ts,
        date_key,
        customer_id,
        order_id,
        product_id,
        vehicle_id,
        ordered_litres,
        delivered_litres,
        delay_minutes,
        is_on_time,
        is_in_full,
        otif_flag,
        delivery_status,
        failure_reason_code,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
