-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_marine_inventory_snapshot') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by marine_snapshot_id order by snapshot_ts desc) as _row_rank
    from source
),

renamed as (
    select
        marine_snapshot_id,
        snapshot_ts,
        date_key,
        port_code,
        product_id,
        capacity_litres,
        stock_on_hand_litres,
        days_of_cover,
        viscosity_cst,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
