-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by aviation_sale_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_aviation_sales') }}
    where _dq_is_valid
)

select
    aviation_sale_id,
    sale_ts,
    date_key,
    airport_code,
    airline_code,
    customer_id,
    product_id,
    uplift_litres,
    unit_price_zar,
    revenue_zar,
    cogs_zar,
    flight_type,
    is_into_plane,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
