-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_aircraft_uplifts') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by uplift_id order by uplift_ts desc) as _row_rank
    from source
),

renamed as (
    select
        uplift_id,
        uplift_ts,
        date_key,
        airport_code,
        airline_code,
        flight_number,
        aircraft_registration,
        uplift_litres,
        uplift_duration_minutes,
        density_kg_per_litre,
        meter_start,
        quality_check_passed,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
