-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by tank_dip_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_tank_dips') }}
    where _dq_is_valid
)

select
    tank_dip_id,
    dip_ts,
    date_key,
    tank_id,
    site_id,
    product_id,
    capacity_litres,
    volume_litres,
    ullage_litres,
    fill_pct,
    water_level_mm,
    temperature_celsius,
    below_reorder_point,
    reading_source,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
