-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_fleet_costs') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by fleet_cost_id order by ingested_at desc) as _row_rank
    from source
),

renamed as (
    select
        fleet_cost_id,
        cost_date,
        date_key,
        vehicle_id,
        carrier_id,
        cost_type,
        amount_zar,
        kilometres_in_period,
        cost_centre_code,
        is_accrual,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
