-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by cylinder_movement_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_lpg_cylinder_movements') }}
    where _dq_is_valid
)

select
    cylinder_movement_id,
    movement_ts,
    date_key,
    site_id,
    depot_id,
    cylinder_type_code,
    movement_type,
    cylinder_count,
    deposit_value_zar,
    requires_requalification,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
