-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_loyalty_transactions') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by loyalty_transaction_id order by transaction_ts desc) as _row_rank
    from source
),

renamed as (
    select
        loyalty_transaction_id,
        transaction_ts,
        date_key,
        loyalty_member_id,
        tier,
        site_id,
        transaction_type,
        qualifying_spend_zar,
        points_delta,
        points_value_zar,
        earn_category,
        channel,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
