-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_lubricant_orders') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by lubricant_order_id order by order_date desc) as _row_rank
    from source
),

renamed as (
    select
        lubricant_order_id,
        order_date,
        date_key,
        customer_id,
        warehouse_id,
        product_id,
        ordered_litres,
        fulfilled_litres,
        order_status,
        lead_time_days,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
