-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by finance_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_finance_revenue_cost') }}
    where _dq_is_valid
)

select
    finance_id,
    period_date,
    date_key,
    business_unit_code,
    site_id,
    cost_centre_code,
    revenue_zar,
    cogs_zar,
    gross_profit_zar,
    opex_zar,
    ebitda_zar,
    depreciation_zar,
    gross_margin_pct,
    currency_code,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
