-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by route_performance_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_route_performance') }}
    where _dq_is_valid
)

select
    route_performance_id,
    business_date,
    date_key,
    route_id,
    planned_distance_km,
    actual_distance_km,
    distance_variance_pct,
    planned_duration_hours,
    actual_duration_hours,
    drops_planned,
    drops_completed,
    cost_per_km_zar,
    utilisation_pct,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
