-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_tank_dips') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by tank_dip_id order by dip_ts desc) as _row_rank
    from source
),

renamed as (
    select
        tank_dip_id,
        dip_ts,
        date_key,
        tank_id,
        site_id,
        product_id,
        capacity_litres,
        volume_litres,
        ullage_litres,
        fill_pct,
        water_level_mm,
        temperature_celsius,
        below_reorder_point,
        reading_source,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
