-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by journal_line_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_general_ledger') }}
    where _dq_is_valid
)

select
    journal_line_id,
    posting_date,
    date_key,
    journal_id,
    gl_account_code,
    account_class,
    cost_centre_code,
    profit_centre_code,
    legal_entity_code,
    debit_amount_zar,
    credit_amount_zar,
    signed_amount_zar,
    currency_code,
    document_type,
    is_reversal,
    fiscal_period,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
