-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by shop_line_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_shop_sales') }}
    where _dq_is_valid
)

select
    shop_line_id,
    basket_id,
    transaction_ts,
    date_key,
    time_key,
    site_id,
    product_id,
    quantity,
    unit_price_zar,
    gross_sales_zar,
    cogs_zar,
    gross_margin_zar,
    promotion_applied,
    payment_method,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
