-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by commercial_delivery_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_commercial_deliveries') }}
    where _dq_is_valid
)

select
    commercial_delivery_id,
    planned_delivery_ts,
    actual_delivery_ts,
    date_key,
    customer_id,
    order_id,
    product_id,
    vehicle_id,
    ordered_litres,
    delivered_litres,
    delay_minutes,
    is_on_time,
    is_in_full,
    otif_flag,
    delivery_status,
    failure_reason_code,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
