-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_lpg_inventory_snapshot') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('lpg_snapshot_id') }} as lpg_snapshot_id,
        {{ clean_timestamp('snapshot_ts') }} as snapshot_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('depot_id') }} as depot_id,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_measure('capacity_kg') }} as capacity_kg,
        {{ clean_measure('stock_on_hand_kg') }} as stock_on_hand_kg,
        {{ clean_integer('cylinders_full') }} as cylinders_full,
        {{ clean_integer('cylinders_empty') }} as cylinders_empty,
        {{ clean_measure('days_of_cover') }} as days_of_cover,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (lpg_snapshot_id is not null) as _dq_lpg_snapshot_id_present,
        (site_id is not null) as _dq_site_id_present,
        (snapshot_ts is not null) as _dq_event_timestamp_valid,
        (coalesce(_dq_lpg_snapshot_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_event_timestamp_valid, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_lpg_snapshot_id_present, false) then 'lpg_snapshot_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so
-- the same business key can arrive more than once. Keep the
-- most recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by lpg_snapshot_id order by ingested_at desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    lpg_snapshot_id,
    snapshot_ts,
    date_key,
    depot_id,
    site_id,
    capacity_kg,
    stock_on_hand_kg,
    cylinders_full,
    cylinders_empty,
    days_of_cover,
    source_system_code,
    ingested_at,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
