-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_site_daily_operations') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('site_day_id') }} as site_day_id,
        {{ clean_timestamp('business_date') }} as business_date,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_measure('fuel_litres') }} as fuel_litres,
        {{ clean_measure('fuel_revenue_zar') }} as fuel_revenue_zar,
        {{ clean_measure('shop_revenue_zar') }} as shop_revenue_zar,
        {{ clean_integer('customer_count') }} as customer_count,
        {{ clean_measure('average_basket_zar') }} as average_basket_zar,
        {{ clean_measure('staff_hours') }} as staff_hours,
        {{ correct_unit_error(clean_measure('energy_kwh'), 400) }} as energy_kwh,
        {{ clean_measure('downtime_minutes') }} as downtime_minutes,
        {{ fix_mojibake('weather_condition') }} as weather_condition,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (site_day_id is not null) as _dq_site_day_id_present,
        (site_id is not null) as _dq_site_id_present,
        (business_date is not null) as _dq_event_timestamp_valid,
        (fuel_revenue_zar >= 0) as _dq_fuel_revenue_zar_non_negative,
        (shop_revenue_zar >= 0) as _dq_shop_revenue_zar_non_negative,
        (average_basket_zar >= 0) as _dq_average_basket_zar_non_negative,
        (energy_kwh >= 0) as _dq_energy_kwh_non_negative,
        (energy_kwh <= 400) as _dq_energy_kwh_within_range,
        (coalesce(_dq_site_day_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_fuel_revenue_zar_non_negative, false) and coalesce(_dq_shop_revenue_zar_non_negative, false) and coalesce(_dq_average_basket_zar_non_negative, false) and coalesce(_dq_energy_kwh_non_negative, false) and coalesce(_dq_energy_kwh_within_range, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_site_day_id_present, false) then 'site_day_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_fuel_revenue_zar_non_negative, false) then 'fuel_revenue_zar_non_negative' end,
            case when not coalesce(_dq_shop_revenue_zar_non_negative, false) then 'shop_revenue_zar_non_negative' end,
            case when not coalesce(_dq_average_basket_zar_non_negative, false) then 'average_basket_zar_non_negative' end,
            case when not coalesce(_dq_energy_kwh_non_negative, false) then 'energy_kwh_non_negative' end,
            case when not coalesce(_dq_energy_kwh_within_range, false) then 'energy_kwh_within_range' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so
-- the same business key can arrive more than once. Keep the
-- most recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by site_day_id order by ingested_at desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    site_day_id,
    business_date,
    date_key,
    site_id,
    fuel_litres,
    fuel_revenue_zar,
    shop_revenue_zar,
    customer_count,
    average_basket_zar,
    staff_hours,
    energy_kwh,
    downtime_minutes,
    weather_condition,
    source_system_code,
    ingested_at,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
