-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_near_misses') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by near_miss_id order by reported_ts desc) as _row_rank
    from source
),

renamed as (
    select
        near_miss_id,
        reported_ts,
        date_key,
        site_id,
        hazard_type,
        potential_severity,
        immediate_action_taken,
        days_to_close,
        reported_by_employee_id,
        is_repeat_hazard,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
