-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_customer_invoices') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by invoice_id order by invoice_date desc) as _row_rank
    from source
),

renamed as (
    select
        invoice_id,
        invoice_date,
        date_key,
        customer_id,
        due_date,
        net_amount_zar,
        vat_amount_zar,
        gross_amount_zar,
        payment_terms_days,
        days_to_payment,
        is_overdue,
        credit_band,
        invoice_status,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
