-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_vehicle_trips') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by trip_id order by trip_start_ts desc) as _row_rank
    from source
),

renamed as (
    select
        trip_id,
        trip_start_ts,
        trip_end_ts,
        date_key,
        vehicle_id,
        driver_id,
        route_id,
        distance_km,
        duration_hours,
        average_speed_kph,
        fuel_consumed_litres,
        litres_per_100km,
        idle_minutes,
        harsh_braking_events,
        harsh_acceleration_events,
        speeding_events,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
