-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_facts', 'fact_contract_volume_commitments') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('commitment_id') }} as commitment_id,
        {{ clean_timestamp('period_start_date') }} as period_start_date,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('contract_id') }} as contract_id,
        {{ clean_code('customer_id') }} as customer_id,
        {{ clean_code('product_id') }} as product_id,
        {{ clean_measure('committed_litres') }} as committed_litres,
        {{ clean_measure('achieved_litres') }} as achieved_litres,
        {{ clean_measure('achievement_pct') }} as achievement_pct,
        try_cast(is_shortfall as boolean) as is_shortfall,
        {{ clean_measure('shortfall_penalty_zar') }} as shortfall_penalty_zar,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (commitment_id is not null) as _dq_commitment_id_present,
        (customer_id is not null) as _dq_customer_id_present,
        (product_id is not null) as _dq_product_id_present,
        (period_start_date is not null) as _dq_event_timestamp_valid,
        (shortfall_penalty_zar >= 0) as _dq_shortfall_penalty_zar_non_negative,
        (coalesce(_dq_commitment_id_present, false) and coalesce(_dq_customer_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_shortfall_penalty_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_commitment_id_present, false) then 'commitment_id_present' end,
            case when not coalesce(_dq_customer_id_present, false) then 'customer_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_shortfall_penalty_zar_non_negative, false) then 'shortfall_penalty_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so the
-- same business key can arrive more than once. Keep the most
-- recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by commitment_id order by ingested_at desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    commitment_id,
    period_start_date,
    date_key,
    contract_id,
    customer_id,
    product_id,
    committed_litres,
    achieved_litres,
    achievement_pct,
    is_shortfall,
    shortfall_penalty_zar,
    source_system_code,
    ingested_at,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
