-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by loyalty_transaction_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_loyalty_transactions') }}
    where _dq_is_valid
)

select
    loyalty_transaction_id,
    transaction_ts,
    date_key,
    loyalty_member_id,
    tier,
    site_id,
    transaction_type,
    qualifying_spend_zar,
    points_delta,
    points_value_zar,
    earn_category,
    channel,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
