-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by stock_loss_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_stock_losses') }}
    where _dq_is_valid
)

select
    stock_loss_id,
    loss_date,
    date_key,
    site_id,
    terminal_id,
    product_id,
    loss_litres,
    loss_value_zar,
    loss_category,
    is_recoverable,
    insurance_claim_raised,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
