-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_lpg_cylinder_movements') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by cylinder_movement_id order by movement_ts desc) as _row_rank
    from source
),

renamed as (
    select
        cylinder_movement_id,
        movement_ts,
        date_key,
        site_id,
        depot_id,
        cylinder_type_code,
        movement_type,
        cylinder_count,
        deposit_value_zar,
        requires_requalification,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
