-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_maintenance_work_orders') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by work_order_id order by raised_ts desc) as _row_rank
    from source
),

renamed as (
    select
        work_order_id,
        raised_ts,
        date_key,
        asset_id,
        site_id,
        asset_type,
        criticality,
        asset_age_years,
        maintenance_type,
        failure_mode,
        priority,
        response_hours,
        labour_hours,
        labour_cost_zar,
        parts_cost_zar,
        total_cost_zar,
        completed_ts,
        is_completed,
        is_breakdown,
        technician_employee_id,
        sla_breached,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
