-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by training_record_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_training_compliance') }}
    where _dq_is_valid
)

select
    training_record_id,
    completed_date,
    date_key,
    employee_id,
    site_id,
    course_name,
    result,
    score_pct,
    expiry_date,
    is_expired,
    is_mandatory,
    training_hours,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
