-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_procurement_orders') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by purchase_order_id order by order_date desc) as _row_rank
    from source
),

renamed as (
    select
        purchase_order_id,
        order_date,
        date_key,
        supplier_id,
        terminal_id,
        product_id,
        ordered_litres,
        expected_delivery_date,
        incoterm,
        order_status,
        contracted_price_zar,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
