-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by receipt_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_procurement_receipts') }}
    where _dq_is_valid
)

select
    receipt_id,
    receipt_ts,
    date_key,
    purchase_order_id,
    supplier_id,
    terminal_id,
    product_id,
    quantity_litres,
    unit_cost_zar,
    total_cost_zar,
    source_mode,
    quality_pass,
    density_kg_per_m3,
    temperature_celsius,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
