-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_replenishment_orders') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by replenishment_id order by raised_ts desc) as _row_rank
    from source
),

renamed as (
    select
        replenishment_id,
        raised_ts,
        date_key,
        site_id,
        terminal_id,
        product_id,
        requested_litres,
        trigger_type,
        days_of_cover_at_raise,
        promised_delivery_ts,
        fulfilled_flag,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
