-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_lubricant_orders') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('lubricant_order_id') }} as lubricant_order_id,
        {{ clean_timestamp('order_date') }} as order_date,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('customer_id') }} as customer_id,
        {{ clean_code('warehouse_id') }} as warehouse_id,
        {{ clean_code('product_id') }} as product_id,
        {{ clean_measure('ordered_litres') }} as ordered_litres,
        {{ clean_measure('fulfilled_litres') }} as fulfilled_litres,
        {{ fix_mojibake('order_status') }} as order_status,
        {{ clean_measure('lead_time_days') }} as lead_time_days,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (lubricant_order_id is not null) as _dq_lubricant_order_id_present,
        (customer_id is not null) as _dq_customer_id_present,
        (product_id is not null) as _dq_product_id_present,
        (order_date is not null) as _dq_event_timestamp_valid,
        (coalesce(_dq_lubricant_order_id_present, false) and coalesce(_dq_customer_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_lubricant_order_id_present, false) then 'lubricant_order_id_present' end,
            case when not coalesce(_dq_customer_id_present, false) then 'customer_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so
-- the same business key can arrive more than once. Keep the
-- most recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by lubricant_order_id order by ingested_at desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    lubricant_order_id,
    order_date,
    date_key,
    customer_id,
    warehouse_id,
    product_id,
    ordered_litres,
    fulfilled_litres,
    order_status,
    lead_time_days,
    source_system_code,
    ingested_at,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
