-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by terminal_issue_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_terminal_issues') }}
    where _dq_is_valid
)

select
    terminal_issue_id,
    issue_ts,
    date_key,
    terminal_id,
    product_id,
    vehicle_id,
    gantry_bay,
    issued_litres,
    loading_minutes,
    queue_minutes,
    destination_site_id,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
