-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_finance_revenue_cost') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by finance_id order by period_date desc) as _row_rank
    from source
),

renamed as (
    select
        finance_id,
        period_date,
        date_key,
        business_unit_code,
        site_id,
        cost_centre_code,
        revenue_zar,
        cogs_zar,
        gross_profit_zar,
        opex_zar,
        ebitda_zar,
        depreciation_zar,
        gross_margin_pct,
        currency_code,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
