-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_terminal_throughput') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by throughput_id order by business_date desc) as _row_rank
    from source
),

renamed as (
    select
        throughput_id,
        business_date,
        date_key,
        terminal_id,
        product_id,
        opening_stock_litres,
        receipts_litres,
        issues_litres,
        closing_stock_litres,
        capacity_litres,
        utilisation_pct,
        days_of_cover,
        gain_loss_litres,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
