-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_contract_pricing') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by contract_price_id order by effective_date desc) as _row_rank
    from source
),

renamed as (
    select
        contract_price_id,
        effective_date,
        date_key,
        contract_id,
        product_id,
        basic_fuel_price_zar,
        differential_cents_per_litre,
        discount_cents_per_litre,
        net_contract_price_zar,
        price_mechanism,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
