-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by meter_reading_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_asset_meter_readings') }}
    where _dq_is_valid
)

select
    meter_reading_id,
    reading_ts,
    date_key,
    asset_id,
    site_id,
    running_hours,
    cycle_count,
    vibration_mm_s,
    temperature_celsius,
    pressure_bar,
    current_draw_amps,
    is_alarm,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
