-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_vehicle_safety_events') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by vehicle_safety_event_id order by event_ts desc) as _row_rank
    from source
),

renamed as (
    select
        vehicle_safety_event_id,
        event_ts,
        date_key,
        vehicle_id,
        driver_id,
        event_type,
        severity,
        speed_kph,
        speed_limit_kph,
        g_force,
        latitude,
        longitude,
        resulted_in_incident,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
