-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_facts', 'fact_spare_parts_usage') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('parts_usage_id') }} as parts_usage_id,
        {{ clean_timestamp('usage_ts') }} as usage_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('work_order_id') }} as work_order_id,
        {{ clean_code('asset_id') }} as asset_id,
        {{ fix_mojibake('part_number') }} as part_number,
        {{ clean_integer('quantity_used') }} as quantity_used,
        {{ clean_measure('unit_cost_zar') }} as unit_cost_zar,
        {{ clean_measure('total_cost_zar') }} as total_cost_zar,
        {{ clean_code('warehouse_id') }} as warehouse_id,
        try_cast(was_stocked_out as boolean) as was_stocked_out,
        {{ clean_measure('lead_time_days') }} as lead_time_days,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (parts_usage_id is not null) as _dq_parts_usage_id_present,
        (usage_ts is not null) as _dq_event_timestamp_valid,
        (unit_cost_zar >= 0) as _dq_unit_cost_zar_non_negative,
        (total_cost_zar >= 0) as _dq_total_cost_zar_non_negative,
        (coalesce(_dq_parts_usage_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_unit_cost_zar_non_negative, false) and coalesce(_dq_total_cost_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_parts_usage_id_present, false) then 'parts_usage_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_unit_cost_zar_non_negative, false) then 'unit_cost_zar_non_negative' end,
            case when not coalesce(_dq_total_cost_zar_non_negative, false) then 'total_cost_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so the
-- same business key can arrive more than once. Keep the most
-- recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by parts_usage_id order by ingested_at desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    parts_usage_id,
    usage_ts,
    date_key,
    work_order_id,
    asset_id,
    part_number,
    quantity_used,
    unit_cost_zar,
    total_cost_zar,
    warehouse_id,
    was_stocked_out,
    lead_time_days,
    source_system_code,
    ingested_at,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
