-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by site_day_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_site_daily_operations') }}
    where _dq_is_valid
)

select
    site_day_id,
    business_date,
    date_key,
    site_id,
    fuel_litres,
    fuel_revenue_zar,
    shop_revenue_zar,
    customer_count,
    average_basket_zar,
    staff_hours,
    energy_kwh,
    downtime_minutes,
    weather_condition,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
