-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_inventory_movements') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by movement_id order by movement_ts desc) as _row_rank
    from source
),

renamed as (
    select
        movement_id,
        movement_ts,
        date_key,
        movement_type,
        site_id,
        terminal_id,
        product_id,
        quantity_litres,
        signed_quantity_litres,
        reason_code,
        posted_by_employee_id,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
