-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_contract_volume_commitments') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by commitment_id order by period_start_date desc) as _row_rank
    from source
),

renamed as (
    select
        commitment_id,
        period_start_date,
        date_key,
        contract_id,
        customer_id,
        product_id,
        committed_litres,
        achieved_litres,
        achievement_pct,
        is_shortfall,
        shortfall_penalty_zar,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
