-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_energy_costs') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by energy_cost_id order by billing_period_start desc) as _row_rank
    from source
),

renamed as (
    select
        energy_cost_id,
        billing_period_start,
        date_key,
        site_id,
        energy_source,
        consumption_kwh,
        unit_rate_zar_per_kwh,
        demand_charge_zar,
        energy_charge_zar,
        total_cost_zar,
        carbon_kg,
        cost_centre_code,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
