-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by movement_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_inventory_movements') }}
    where _dq_is_valid
)

select
    movement_id,
    movement_ts,
    date_key,
    movement_type,
    site_id,
    terminal_id,
    product_id,
    quantity_litres,
    signed_quantity_litres,
    reason_code,
    posted_by_employee_id,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
