-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_shop_sales') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('shop_line_id') }} as shop_line_id,
        {{ clean_code('basket_id') }} as basket_id,
        {{ clean_timestamp('transaction_ts') }} as transaction_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_integer('time_key') }} as time_key,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_code('product_id') }} as product_id,
        {{ clean_integer('quantity') }} as quantity,
        {{ clean_measure('unit_price_zar') }} as unit_price_zar,
        {{ clean_measure('gross_sales_zar') }} as gross_sales_zar,
        {{ clean_measure('cogs_zar') }} as cogs_zar,
        {{ clean_measure('gross_margin_zar') }} as gross_margin_zar,
        try_cast(promotion_applied as boolean) as promotion_applied,
        {{ fix_mojibake('payment_method') }} as payment_method,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (shop_line_id is not null) as _dq_shop_line_id_present,
        (site_id is not null) as _dq_site_id_present,
        (product_id is not null) as _dq_product_id_present,
        (transaction_ts is not null) as _dq_event_timestamp_valid,
        (unit_price_zar >= 0) as _dq_unit_price_zar_non_negative,
        (gross_sales_zar >= 0) as _dq_gross_sales_zar_non_negative,
        (cogs_zar >= 0) as _dq_cogs_zar_non_negative,
        (gross_margin_zar >= 0) as _dq_gross_margin_zar_non_negative,
        (coalesce(_dq_shop_line_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_unit_price_zar_non_negative, false) and coalesce(_dq_gross_sales_zar_non_negative, false) and coalesce(_dq_cogs_zar_non_negative, false) and coalesce(_dq_gross_margin_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_shop_line_id_present, false) then 'shop_line_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_unit_price_zar_non_negative, false) then 'unit_price_zar_non_negative' end,
            case when not coalesce(_dq_gross_sales_zar_non_negative, false) then 'gross_sales_zar_non_negative' end,
            case when not coalesce(_dq_cogs_zar_non_negative, false) then 'cogs_zar_non_negative' end,
            case when not coalesce(_dq_gross_margin_zar_non_negative, false) then 'gross_margin_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so
-- the same business key can arrive more than once. Keep the
-- most recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by shop_line_id order by ingested_at desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    shop_line_id,
    basket_id,
    transaction_ts,
    date_key,
    time_key,
    site_id,
    product_id,
    quantity,
    unit_price_zar,
    gross_sales_zar,
    cogs_zar,
    gross_margin_zar,
    promotion_applied,
    payment_method,
    source_system_code,
    ingested_at,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
