-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_customer_credit_exposure') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by exposure_id order by snapshot_date desc) as _row_rank
    from source
),

renamed as (
    select
        exposure_id,
        snapshot_date,
        date_key,
        customer_id,
        credit_limit_zar,
        outstanding_balance_zar,
        utilisation_pct,
        overdue_balance_zar,
        days_sales_outstanding,
        is_over_limit,
        credit_band,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
