-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_finance_revenue_cost') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('finance_id') }} as finance_id,
        {{ clean_timestamp('period_date') }} as period_date,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('business_unit_code') }} as business_unit_code,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_code('cost_centre_code') }} as cost_centre_code,
        {{ clean_measure('revenue_zar') }} as revenue_zar,
        {{ clean_measure('cogs_zar') }} as cogs_zar,
        {{ clean_measure('gross_profit_zar') }} as gross_profit_zar,
        {{ clean_measure('opex_zar') }} as opex_zar,
        {{ clean_measure('ebitda_zar') }} as ebitda_zar,
        {{ clean_measure('depreciation_zar') }} as depreciation_zar,
        {{ clean_measure('gross_margin_pct') }} as gross_margin_pct,
        {{ clean_code('currency_code') }} as currency_code,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (finance_id is not null) as _dq_finance_id_present,
        (site_id is not null) as _dq_site_id_present,
        (period_date is not null) as _dq_event_timestamp_valid,
        (revenue_zar >= 0) as _dq_revenue_zar_non_negative,
        (cogs_zar >= 0) as _dq_cogs_zar_non_negative,
        (gross_profit_zar >= 0) as _dq_gross_profit_zar_non_negative,
        (opex_zar >= 0) as _dq_opex_zar_non_negative,
        (ebitda_zar >= 0) as _dq_ebitda_zar_non_negative,
        (depreciation_zar >= 0) as _dq_depreciation_zar_non_negative,
        (coalesce(_dq_finance_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_revenue_zar_non_negative, false) and coalesce(_dq_cogs_zar_non_negative, false) and coalesce(_dq_gross_profit_zar_non_negative, false) and coalesce(_dq_opex_zar_non_negative, false) and coalesce(_dq_ebitda_zar_non_negative, false) and coalesce(_dq_depreciation_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_finance_id_present, false) then 'finance_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_revenue_zar_non_negative, false) then 'revenue_zar_non_negative' end,
            case when not coalesce(_dq_cogs_zar_non_negative, false) then 'cogs_zar_non_negative' end,
            case when not coalesce(_dq_gross_profit_zar_non_negative, false) then 'gross_profit_zar_non_negative' end,
            case when not coalesce(_dq_opex_zar_non_negative, false) then 'opex_zar_non_negative' end,
            case when not coalesce(_dq_ebitda_zar_non_negative, false) then 'ebitda_zar_non_negative' end,
            case when not coalesce(_dq_depreciation_zar_non_negative, false) then 'depreciation_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so
-- the same business key can arrive more than once. Keep the
-- most recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by finance_id order by ingested_at desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    finance_id,
    period_date,
    date_key,
    business_unit_code,
    site_id,
    cost_centre_code,
    revenue_zar,
    cogs_zar,
    gross_profit_zar,
    opex_zar,
    ebitda_zar,
    depreciation_zar,
    gross_margin_pct,
    currency_code,
    source_system_code,
    ingested_at,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
