-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by mobile_payment_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_mobile_payments') }}
    where _dq_is_valid
)

select
    mobile_payment_id,
    payment_ts,
    date_key,
    digital_user_id,
    site_id,
    amount_zar,
    payment_instrument,
    is_approved,
    decline_reason,
    processing_ms,
    is_flagged_fraud,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
