-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_retail_fuel_sales') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by transaction_id order by transaction_ts desc) as _row_rank
    from source
),

renamed as (
    select
        transaction_id,
        transaction_ts,
        date_key,
        time_key,
        site_id,
        product_id,
        pump_number,
        forecourt_lane,
        shift_name,
        litres,
        unit_price_zar,
        gross_sales_zar,
        cogs_zar,
        gross_margin_zar,
        payment_method,
        loyalty_flag,
        loyalty_member_id,
        is_fleet_sale,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
