-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_capex') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by capex_id order by period_date desc) as _row_rank
    from source
),

renamed as (
    select
        capex_id,
        period_date,
        date_key,
        project_code,
        site_id,
        capex_category,
        budget_zar,
        actual_spend_zar,
        variance_zar,
        variance_pct,
        expected_irr_pct,
        payback_years,
        project_status,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
