-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by price_change_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_price_changes') }}
    where _dq_is_valid
)

select
    price_change_id,
    effective_ts,
    date_key,
    site_id,
    product_id,
    old_price_zar,
    new_price_zar,
    change_cents_per_litre,
    change_reason,
    approved_by_employee_id,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
