-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_facts', 'fact_hsseq_incidents') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('incident_id') }} as incident_id,
        {{ clean_timestamp('incident_ts') }} as incident_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('site_id') }} as site_id,
        {{ fix_mojibake('incident_type') }} as incident_type,
        {{ fix_mojibake('severity') }} as severity,
        {{ clean_integer('severity_rank') }} as severity_rank,
        try_cast(is_lost_time_injury as boolean) as is_lost_time_injury,
        {{ clean_measure('lost_days') }} as lost_days,
        {{ clean_integer('people_affected') }} as people_affected,
        {{ clean_measure('estimated_cost_zar') }} as estimated_cost_zar,
        try_cast(is_reportable as boolean) as is_reportable,
        {{ fix_mojibake('root_cause_category') }} as root_cause_category,
        {{ clean_integer('corrective_actions_raised') }} as corrective_actions_raised,
        {{ clean_integer('corrective_actions_closed') }} as corrective_actions_closed,
        {{ clean_measure('investigation_days') }} as investigation_days,
        {{ clean_code('reported_by_employee_id') }} as reported_by_employee_id,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (incident_id is not null) as _dq_incident_id_present,
        (site_id is not null) as _dq_site_id_present,
        (incident_ts is not null) as _dq_event_timestamp_valid,
        (estimated_cost_zar >= 0) as _dq_estimated_cost_zar_non_negative,
        (coalesce(_dq_incident_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_estimated_cost_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_incident_id_present, false) then 'incident_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_estimated_cost_zar_non_negative, false) then 'estimated_cost_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so the
-- same business key can arrive more than once. Keep the most
-- recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by incident_id order by ingested_at desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    incident_id,
    incident_ts,
    date_key,
    site_id,
    incident_type,
    severity,
    severity_rank,
    is_lost_time_injury,
    lost_days,
    people_affected,
    estimated_cost_zar,
    is_reportable,
    root_cause_category,
    corrective_actions_raised,
    corrective_actions_closed,
    investigation_days,
    reported_by_employee_id,
    source_system_code,
    ingested_at,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
