-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_solar_generation') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by solar_reading_id order by reading_ts desc) as _row_rank
    from source
),

renamed as (
    select
        solar_reading_id,
        reading_ts,
        date_key,
        time_key,
        solar_asset_id,
        site_id,
        installed_kwp,
        interval_minutes,
        energy_kwh,
        irradiance_w_m2,
        panel_temperature_celsius,
        inverter_efficiency_pct,
        capacity_factor,
        is_daylight,
        co2_avoided_kg,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
