-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by lpg_snapshot_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_lpg_inventory_snapshot') }}
    where _dq_is_valid
)

select
    lpg_snapshot_id,
    snapshot_ts,
    date_key,
    depot_id,
    site_id,
    capacity_kg,
    stock_on_hand_kg,
    cylinders_full,
    cylinders_empty,
    days_of_cover,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
