-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by cargo_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_import_cargoes') }}
    where _dq_is_valid
)

select
    cargo_id,
    eta_ts,
    date_key,
    discharge_port_code,
    supplier_id,
    product_id,
    cargo_volume_litres,
    discharge_hours,
    demurrage_hours,
    demurrage_cost_usd,
    landed_cost_zar_per_litre,
    vessel_imo,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
