-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_hsseq_incidents') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by incident_id order by incident_ts desc) as _row_rank
    from source
),

renamed as (
    select
        incident_id,
        incident_ts,
        date_key,
        site_id,
        incident_type,
        severity,
        severity_rank,
        is_lost_time_injury,
        lost_days,
        people_affected,
        estimated_cost_zar,
        is_reportable,
        root_cause_category,
        corrective_actions_raised,
        corrective_actions_closed,
        investigation_days,
        reported_by_employee_id,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
