-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_daily_executive_kpi') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by executive_kpi_id order by business_date desc) as _row_rank
    from source
),

renamed as (
    select
        executive_kpi_id,
        business_date,
        date_key,
        site_id,
        business_unit_code,
        province,
        fuel_volume_litres,
        fuel_revenue_zar,
        shop_revenue_zar,
        total_revenue_zar,
        gross_margin_zar,
        gross_margin_pct,
        customer_count,
        average_transaction_zar,
        otif_pct,
        stock_availability_pct,
        safety_incidents,
        nps_score,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
