-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_price_changes') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by price_change_id order by effective_ts desc) as _row_rank
    from source
),

renamed as (
    select
        price_change_id,
        effective_ts,
        date_key,
        site_id,
        product_id,
        old_price_zar,
        new_price_zar,
        change_cents_per_litre,
        change_reason,
        approved_by_employee_id,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
