-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_route_performance') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by route_performance_id order by business_date desc) as _row_rank
    from source
),

renamed as (
    select
        route_performance_id,
        business_date,
        date_key,
        route_id,
        planned_distance_km,
        actual_distance_km,
        distance_variance_pct,
        planned_duration_hours,
        actual_duration_hours,
        drops_planned,
        drops_completed,
        cost_per_km_zar,
        utilisation_pct,
        source_system_code,
        ingested_at,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
