-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by energy_consumption_id order by ingested_at desc nulls last) as _row_rank
    from {{ ref('cln_fact_site_energy_consumption') }}
    where _dq_is_valid
)

select
    energy_consumption_id,
    reading_ts,
    date_key,
    site_id,
    energy_source,
    consumption_kwh,
    peak_demand_kva,
    power_factor,
    tariff_period,
    cost_zar,
    source_system_code,
    ingested_at,
    _cleansed_at
from deduplicated
where _row_rank = 1
