-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_digital_sessions') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('session_id') }} as session_id,
        {{ clean_timestamp('session_start_ts') }} as session_start_ts,
        {{ clean_timestamp('session_end_ts') }} as session_end_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('digital_user_id') }} as digital_user_id,
        {{ fix_mojibake('device_type') }} as device_type,
        {{ clean_integer('event_count') }} as event_count,
        {{ clean_measure('duration_seconds') }} as duration_seconds,
        {{ clean_integer('screens_viewed') }} as screens_viewed,
        try_cast(is_bounce as boolean) as is_bounce,
        try_cast(converted as boolean) as converted,
        {{ fix_mojibake('acquisition_channel') }} as acquisition_channel,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (session_id is not null) as _dq_session_id_present,
        (session_start_ts is not null) as _dq_event_timestamp_valid,
        (coalesce(_dq_session_id_present, false) and coalesce(_dq_event_timestamp_valid, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_session_id_present, false) then 'session_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
