-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_accounts_receivable') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('ar_id') }} as ar_id,
        {{ clean_timestamp('snapshot_date') }} as snapshot_date,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('customer_id') }} as customer_id,
        {{ clean_code('invoice_id') }} as invoice_id,
        {{ clean_measure('outstanding_zar') }} as outstanding_zar,
        {{ clean_integer('days_outstanding') }} as days_outstanding,
        {{ fix_mojibake('ageing_bucket') }} as ageing_bucket,
        {{ fix_mojibake('credit_band') }} as credit_band,
        {{ clean_measure('provision_pct') }} as provision_pct,
        try_cast(is_doubtful as boolean) as is_doubtful,
        {{ clean_measure('provision_zar') }} as provision_zar,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (ar_id is not null) as _dq_ar_id_present,
        (customer_id is not null) as _dq_customer_id_present,
        (snapshot_date is not null) as _dq_event_timestamp_valid,
        (outstanding_zar >= 0) as _dq_outstanding_zar_non_negative,
        (provision_zar >= 0) as _dq_provision_zar_non_negative,
        (coalesce(_dq_ar_id_present, false) and coalesce(_dq_customer_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_outstanding_zar_non_negative, false) and coalesce(_dq_provision_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_ar_id_present, false) then 'ar_id_present' end,
            case when not coalesce(_dq_customer_id_present, false) then 'customer_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_outstanding_zar_non_negative, false) then 'outstanding_zar_non_negative' end,
            case when not coalesce(_dq_provision_zar_non_negative, false) then 'provision_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
