-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_contract_pricing') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('contract_price_id') }} as contract_price_id,
        {{ clean_timestamp('effective_date') }} as effective_date,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('contract_id') }} as contract_id,
        {{ clean_code('product_id') }} as product_id,
        {{ clean_measure('basic_fuel_price_zar') }} as basic_fuel_price_zar,
        {{ clean_measure('differential_cents_per_litre') }} as differential_cents_per_litre,
        {{ clean_measure('discount_cents_per_litre') }} as discount_cents_per_litre,
        {{ clean_measure('net_contract_price_zar') }} as net_contract_price_zar,
        {{ fix_mojibake('price_mechanism') }} as price_mechanism,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (contract_price_id is not null) as _dq_contract_price_id_present,
        (product_id is not null) as _dq_product_id_present,
        (effective_date is not null) as _dq_event_timestamp_valid,
        (basic_fuel_price_zar >= 0) as _dq_basic_fuel_price_zar_non_negative,
        (net_contract_price_zar >= 0) as _dq_net_contract_price_zar_non_negative,
        (coalesce(_dq_contract_price_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_basic_fuel_price_zar_non_negative, false) and coalesce(_dq_net_contract_price_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_contract_price_id_present, false) then 'contract_price_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_basic_fuel_price_zar_non_negative, false) then 'basic_fuel_price_zar_non_negative' end,
            case when not coalesce(_dq_net_contract_price_zar_non_negative, false) then 'net_contract_price_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
