-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_asset_inspections') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('inspection_id') }} as inspection_id,
        {{ clean_timestamp('inspection_ts') }} as inspection_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('asset_id') }} as asset_id,
        {{ clean_code('site_id') }} as site_id,
        {{ fix_mojibake('inspection_type') }} as inspection_type,
        {{ clean_code('inspector_employee_id') }} as inspector_employee_id,
        {{ fix_mojibake('result') }} as result,
        {{ clean_integer('defects_found') }} as defects_found,
        {{ clean_measure('condition_score') }} as condition_score,
        {{ clean_timestamp('next_due_date') }} as next_due_date,
        try_cast(is_overdue as boolean) as is_overdue,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (inspection_id is not null) as _dq_inspection_id_present,
        (site_id is not null) as _dq_site_id_present,
        (inspection_ts is not null) as _dq_event_timestamp_valid,
        (coalesce(_dq_inspection_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_event_timestamp_valid, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_inspection_id_present, false) then 'inspection_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
