-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_contract_volume_commitments') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('commitment_id') }} as commitment_id,
        {{ clean_timestamp('period_start_date', '1950-01-01', '2035-12-31') }} as period_start_date,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('contract_id') }} as contract_id,
        {{ clean_code('customer_id') }} as customer_id,
        {{ clean_code('product_id') }} as product_id,
        {{ clean_measure('committed_litres') }} as committed_litres,
        {{ clean_measure('achieved_litres') }} as achieved_litres,
        {{ clean_measure('achievement_pct') }} as achievement_pct,
        try_cast(is_shortfall as boolean) as is_shortfall,
        {{ clean_measure('shortfall_penalty_zar') }} as shortfall_penalty_zar,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (commitment_id is not null) as _dq_commitment_id_present,
        (customer_id is not null) as _dq_customer_id_present,
        (product_id is not null) as _dq_product_id_present,
        (period_start_date is not null) as _dq_event_timestamp_valid,
        (shortfall_penalty_zar >= 0) as _dq_shortfall_penalty_zar_non_negative,
        (coalesce(_dq_commitment_id_present, false) and coalesce(_dq_customer_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_shortfall_penalty_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_commitment_id_present, false) then 'commitment_id_present' end,
            case when not coalesce(_dq_customer_id_present, false) then 'customer_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_shortfall_penalty_zar_non_negative, false) then 'shortfall_penalty_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
