-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_aviation_inventory_snapshot') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('aviation_snapshot_id') }} as aviation_snapshot_id,
        {{ clean_timestamp('snapshot_ts') }} as snapshot_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('airport_code') }} as airport_code,
        {{ clean_code('product_id') }} as product_id,
        {{ clean_measure('capacity_litres') }} as capacity_litres,
        {{ clean_measure('stock_on_hand_litres') }} as stock_on_hand_litres,
        {{ clean_measure('days_of_cover') }} as days_of_cover,
        {{ clean_measure('water_ppm') }} as water_ppm,
        try_cast(on_specification as boolean) as on_specification,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (aviation_snapshot_id is not null) as _dq_aviation_snapshot_id_present,
        (product_id is not null) as _dq_product_id_present,
        (snapshot_ts is not null) as _dq_event_timestamp_valid,
        (capacity_litres >= 0) as _dq_capacity_litres_non_negative,
        (stock_on_hand_litres >= 0) as _dq_stock_on_hand_litres_non_negative,
        (coalesce(_dq_aviation_snapshot_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_capacity_litres_non_negative, false) and coalesce(_dq_stock_on_hand_litres_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_aviation_snapshot_id_present, false) then 'aviation_snapshot_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_capacity_litres_non_negative, false) then 'capacity_litres_non_negative' end,
            case when not coalesce(_dq_stock_on_hand_litres_non_negative, false) then 'stock_on_hand_litres_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
