-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_site_energy_consumption') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('energy_consumption_id') }} as energy_consumption_id,
        {{ clean_timestamp('reading_ts') }} as reading_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('site_id') }} as site_id,
        {{ fix_mojibake('energy_source') }} as energy_source,
        {{ clean_measure('consumption_kwh') }} as consumption_kwh,
        {{ clean_measure('peak_demand_kva') }} as peak_demand_kva,
        {{ clean_measure('power_factor') }} as power_factor,
        {{ fix_mojibake('tariff_period') }} as tariff_period,
        {{ clean_measure('cost_zar') }} as cost_zar,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (energy_consumption_id is not null) as _dq_energy_consumption_id_present,
        (site_id is not null) as _dq_site_id_present,
        (reading_ts is not null) as _dq_event_timestamp_valid,
        (cost_zar >= 0) as _dq_cost_zar_non_negative,
        (coalesce(_dq_energy_consumption_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_cost_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_energy_consumption_id_present, false) then 'energy_consumption_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_cost_zar_non_negative, false) then 'cost_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
