-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_marine_sales') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('marine_sale_id') }} as marine_sale_id,
        {{ clean_timestamp('sale_ts') }} as sale_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('port_code') }} as port_code,
        {{ clean_code('customer_id') }} as customer_id,
        {{ fix_mojibake('vessel_imo') }} as vessel_imo,
        {{ clean_code('product_id') }} as product_id,
        {{ correct_unit_error(clean_measure('bunker_litres'), 3000000) }} as bunker_litres,
        {{ clean_measure('unit_price_zar') }} as unit_price_zar,
        {{ clean_measure('revenue_zar') }} as revenue_zar,
        {{ clean_measure('cogs_zar') }} as cogs_zar,
        {{ fix_mojibake('vessel_class') }} as vessel_class,
        {{ clean_measure('sulphur_pct') }} as sulphur_pct,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (marine_sale_id is not null) as _dq_marine_sale_id_present,
        (customer_id is not null) as _dq_customer_id_present,
        (product_id is not null) as _dq_product_id_present,
        (sale_ts is not null) as _dq_event_timestamp_valid,
        (bunker_litres >= 0) as _dq_bunker_litres_non_negative,
        (bunker_litres <= 3000000) as _dq_bunker_litres_within_range,
        (unit_price_zar >= 0) as _dq_unit_price_zar_non_negative,
        (unit_price_zar between 8.0 and 45.0) as _dq_unit_price_zar_plausible,
        (revenue_zar >= 0) as _dq_revenue_zar_non_negative,
        (cogs_zar >= 0) as _dq_cogs_zar_non_negative,
        (coalesce(_dq_marine_sale_id_present, false) and coalesce(_dq_customer_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_bunker_litres_non_negative, false) and coalesce(_dq_bunker_litres_within_range, false) and coalesce(_dq_unit_price_zar_non_negative, false) and coalesce(_dq_unit_price_zar_plausible, false) and coalesce(_dq_revenue_zar_non_negative, false) and coalesce(_dq_cogs_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_marine_sale_id_present, false) then 'marine_sale_id_present' end,
            case when not coalesce(_dq_customer_id_present, false) then 'customer_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_bunker_litres_non_negative, false) then 'bunker_litres_non_negative' end,
            case when not coalesce(_dq_bunker_litres_within_range, false) then 'bunker_litres_within_range' end,
            case when not coalesce(_dq_unit_price_zar_non_negative, false) then 'unit_price_zar_non_negative' end,
            case when not coalesce(_dq_unit_price_zar_plausible, false) then 'unit_price_zar_plausible' end,
            case when not coalesce(_dq_revenue_zar_non_negative, false) then 'revenue_zar_non_negative' end,
            case when not coalesce(_dq_cogs_zar_non_negative, false) then 'cogs_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
