-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_daily_executive_kpi') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('executive_kpi_id') }} as executive_kpi_id,
        {{ clean_timestamp('business_date') }} as business_date,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_code('business_unit_code') }} as business_unit_code,
        {{ fix_mojibake('province') }} as province,
        {{ clean_measure('fuel_volume_litres') }} as fuel_volume_litres,
        {{ clean_measure('fuel_revenue_zar') }} as fuel_revenue_zar,
        {{ clean_measure('shop_revenue_zar') }} as shop_revenue_zar,
        {{ clean_measure('total_revenue_zar') }} as total_revenue_zar,
        {{ clean_measure('gross_margin_zar') }} as gross_margin_zar,
        {{ clean_measure('gross_margin_pct') }} as gross_margin_pct,
        {{ clean_integer('customer_count') }} as customer_count,
        {{ clean_measure('average_transaction_zar') }} as average_transaction_zar,
        {{ clean_measure('otif_pct') }} as otif_pct,
        {{ clean_measure('stock_availability_pct') }} as stock_availability_pct,
        {{ clean_integer('safety_incidents') }} as safety_incidents,
        {{ clean_measure('nps_score') }} as nps_score,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (executive_kpi_id is not null) as _dq_executive_kpi_id_present,
        (site_id is not null) as _dq_site_id_present,
        (business_date is not null) as _dq_event_timestamp_valid,
        (fuel_revenue_zar >= 0) as _dq_fuel_revenue_zar_non_negative,
        (shop_revenue_zar >= 0) as _dq_shop_revenue_zar_non_negative,
        (total_revenue_zar >= 0) as _dq_total_revenue_zar_non_negative,
        (gross_margin_zar >= 0) as _dq_gross_margin_zar_non_negative,
        (average_transaction_zar >= 0) as _dq_average_transaction_zar_non_negative,
        (coalesce(_dq_executive_kpi_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_fuel_revenue_zar_non_negative, false) and coalesce(_dq_shop_revenue_zar_non_negative, false) and coalesce(_dq_total_revenue_zar_non_negative, false) and coalesce(_dq_gross_margin_zar_non_negative, false) and coalesce(_dq_average_transaction_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_executive_kpi_id_present, false) then 'executive_kpi_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_fuel_revenue_zar_non_negative, false) then 'fuel_revenue_zar_non_negative' end,
            case when not coalesce(_dq_shop_revenue_zar_non_negative, false) then 'shop_revenue_zar_non_negative' end,
            case when not coalesce(_dq_total_revenue_zar_non_negative, false) then 'total_revenue_zar_non_negative' end,
            case when not coalesce(_dq_gross_margin_zar_non_negative, false) then 'gross_margin_zar_non_negative' end,
            case when not coalesce(_dq_average_transaction_zar_non_negative, false) then 'average_transaction_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
