-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_vehicle_trips') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('trip_id') }} as trip_id,
        {{ clean_timestamp('trip_start_ts') }} as trip_start_ts,
        {{ clean_timestamp('trip_end_ts') }} as trip_end_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('vehicle_id') }} as vehicle_id,
        {{ clean_code('driver_id') }} as driver_id,
        {{ clean_code('route_id') }} as route_id,
        {{ clean_measure('distance_km') }} as distance_km,
        {{ clean_measure('duration_hours') }} as duration_hours,
        {{ clean_measure('average_speed_kph') }} as average_speed_kph,
        {{ clean_measure('fuel_consumed_litres') }} as fuel_consumed_litres,
        {{ clean_measure('litres_per_100km') }} as litres_per_100km,
        {{ clean_measure('idle_minutes') }} as idle_minutes,
        {{ clean_integer('harsh_braking_events') }} as harsh_braking_events,
        {{ clean_integer('harsh_acceleration_events') }} as harsh_acceleration_events,
        {{ clean_integer('speeding_events') }} as speeding_events,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (trip_id is not null) as _dq_trip_id_present,
        (trip_start_ts is not null) as _dq_event_timestamp_valid,
        (coalesce(_dq_trip_id_present, false) and coalesce(_dq_event_timestamp_valid, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_trip_id_present, false) then 'trip_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
