-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_import_cargoes') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('cargo_id') }} as cargo_id,
        {{ clean_timestamp('eta_ts') }} as eta_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('discharge_port_code') }} as discharge_port_code,
        {{ clean_code('supplier_id') }} as supplier_id,
        {{ clean_code('product_id') }} as product_id,
        {{ clean_measure('cargo_volume_litres') }} as cargo_volume_litres,
        {{ clean_measure('discharge_hours') }} as discharge_hours,
        {{ clean_measure('demurrage_hours') }} as demurrage_hours,
        {{ clean_measure('demurrage_cost_usd') }} as demurrage_cost_usd,
        {{ clean_measure('landed_cost_zar_per_litre') }} as landed_cost_zar_per_litre,
        {{ fix_mojibake('vessel_imo') }} as vessel_imo,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (cargo_id is not null) as _dq_cargo_id_present,
        (product_id is not null) as _dq_product_id_present,
        (eta_ts is not null) as _dq_event_timestamp_valid,
        (demurrage_cost_usd >= 0) as _dq_demurrage_cost_usd_non_negative,
        (coalesce(_dq_cargo_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_demurrage_cost_usd_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_cargo_id_present, false) then 'cargo_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_demurrage_cost_usd_non_negative, false) then 'demurrage_cost_usd_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
