-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_aircraft_uplifts') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('uplift_id') }} as uplift_id,
        {{ clean_timestamp('uplift_ts') }} as uplift_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('airport_code') }} as airport_code,
        {{ clean_code('airline_code') }} as airline_code,
        {{ fix_mojibake('flight_number') }} as flight_number,
        {{ fix_mojibake('aircraft_registration') }} as aircraft_registration,
        {{ correct_unit_error(clean_measure('uplift_litres'), 300000) }} as uplift_litres,
        {{ clean_measure('uplift_duration_minutes') }} as uplift_duration_minutes,
        {{ clean_measure('density_kg_per_litre') }} as density_kg_per_litre,
        {{ clean_measure('meter_start') }} as meter_start,
        try_cast(quality_check_passed as boolean) as quality_check_passed,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (uplift_id is not null) as _dq_uplift_id_present,
        (uplift_ts is not null) as _dq_event_timestamp_valid,
        (uplift_litres >= 0) as _dq_uplift_litres_non_negative,
        (uplift_litres <= 300000) as _dq_uplift_litres_within_range,
        (coalesce(_dq_uplift_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_uplift_litres_non_negative, false) and coalesce(_dq_uplift_litres_within_range, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_uplift_id_present, false) then 'uplift_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_uplift_litres_non_negative, false) then 'uplift_litres_non_negative' end,
            case when not coalesce(_dq_uplift_litres_within_range, false) then 'uplift_litres_within_range' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
