-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_working_capital') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('working_capital_id') }} as working_capital_id,
        {{ clean_timestamp('period_date') }} as period_date,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('legal_entity_code') }} as legal_entity_code,
        {{ clean_code('business_unit_code') }} as business_unit_code,
        {{ clean_measure('receivables_zar') }} as receivables_zar,
        {{ clean_measure('inventory_zar') }} as inventory_zar,
        {{ clean_measure('payables_zar') }} as payables_zar,
        {{ clean_measure('days_sales_outstanding') }} as days_sales_outstanding,
        {{ clean_measure('days_inventory_outstanding') }} as days_inventory_outstanding,
        {{ clean_measure('days_payables_outstanding') }} as days_payables_outstanding,
        {{ clean_measure('cash_conversion_cycle_days') }} as cash_conversion_cycle_days,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (working_capital_id is not null) as _dq_working_capital_id_present,
        (period_date is not null) as _dq_event_timestamp_valid,
        (receivables_zar >= 0) as _dq_receivables_zar_non_negative,
        (inventory_zar >= 0) as _dq_inventory_zar_non_negative,
        (payables_zar >= 0) as _dq_payables_zar_non_negative,
        (coalesce(_dq_working_capital_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_receivables_zar_non_negative, false) and coalesce(_dq_inventory_zar_non_negative, false) and coalesce(_dq_payables_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_working_capital_id_present, false) then 'working_capital_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_receivables_zar_non_negative, false) then 'receivables_zar_non_negative' end,
            case when not coalesce(_dq_inventory_zar_non_negative, false) then 'inventory_zar_non_negative' end,
            case when not coalesce(_dq_payables_zar_non_negative, false) then 'payables_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
