-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_inventory_snapshot') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('snapshot_id') }} as snapshot_id,
        {{ clean_timestamp('snapshot_ts') }} as snapshot_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ fix_mojibake('location_type') }} as location_type,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_code('terminal_id') }} as terminal_id,
        {{ clean_code('product_id') }} as product_id,
        {{ clean_measure('capacity_litres') }} as capacity_litres,
        {{ clean_measure('stock_on_hand_litres') }} as stock_on_hand_litres,
        {{ clean_measure('ullage_litres') }} as ullage_litres,
        {{ clean_measure('fill_pct') }} as fill_pct,
        {{ clean_measure('average_daily_usage_litres') }} as average_daily_usage_litres,
        {{ clean_measure('days_of_cover') }} as days_of_cover,
        try_cast(is_stock_out_risk as boolean) as is_stock_out_risk,
        {{ clean_measure('reorder_point_litres') }} as reorder_point_litres,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (snapshot_id is not null) as _dq_snapshot_id_present,
        (site_id is not null) as _dq_site_id_present,
        (product_id is not null) as _dq_product_id_present,
        (snapshot_ts is not null) as _dq_event_timestamp_valid,
        (capacity_litres >= 0) as _dq_capacity_litres_non_negative,
        (stock_on_hand_litres >= 0) as _dq_stock_on_hand_litres_non_negative,
        (fill_pct between 0 and 100) as _dq_fill_pct_in_range,
        (coalesce(_dq_snapshot_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_capacity_litres_non_negative, false) and coalesce(_dq_stock_on_hand_litres_non_negative, false) and coalesce(_dq_fill_pct_in_range, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_snapshot_id_present, false) then 'snapshot_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_capacity_litres_non_negative, false) then 'capacity_litres_non_negative' end,
            case when not coalesce(_dq_stock_on_hand_litres_non_negative, false) then 'stock_on_hand_litres_non_negative' end,
            case when not coalesce(_dq_fill_pct_in_range, false) then 'fill_pct_in_range' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
