-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_route_performance') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('route_performance_id') }} as route_performance_id,
        {{ clean_timestamp('business_date') }} as business_date,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('route_id') }} as route_id,
        {{ clean_measure('planned_distance_km') }} as planned_distance_km,
        {{ clean_measure('actual_distance_km') }} as actual_distance_km,
        {{ clean_measure('distance_variance_pct') }} as distance_variance_pct,
        {{ clean_measure('planned_duration_hours') }} as planned_duration_hours,
        {{ clean_measure('actual_duration_hours') }} as actual_duration_hours,
        {{ clean_integer('drops_planned') }} as drops_planned,
        {{ clean_integer('drops_completed') }} as drops_completed,
        {{ clean_measure('cost_per_km_zar') }} as cost_per_km_zar,
        {{ clean_measure('utilisation_pct') }} as utilisation_pct,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (route_performance_id is not null) as _dq_route_performance_id_present,
        (business_date is not null) as _dq_event_timestamp_valid,
        (cost_per_km_zar >= 0) as _dq_cost_per_km_zar_non_negative,
        (utilisation_pct between 0 and 100) as _dq_utilisation_pct_in_range,
        (coalesce(_dq_route_performance_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_cost_per_km_zar_non_negative, false) and coalesce(_dq_utilisation_pct_in_range, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_route_performance_id_present, false) then 'route_performance_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_cost_per_km_zar_non_negative, false) then 'cost_per_km_zar_non_negative' end,
            case when not coalesce(_dq_utilisation_pct_in_range, false) then 'utilisation_pct_in_range' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
