-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_digital_events') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('digital_event_id') }} as digital_event_id,
        {{ clean_timestamp('event_ts') }} as event_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_integer('time_key') }} as time_key,
        {{ clean_code('digital_user_id') }} as digital_user_id,
        {{ clean_code('session_id') }} as session_id,
        {{ fix_mojibake('event_type') }} as event_type,
        {{ fix_mojibake('device_type') }} as device_type,
        {{ fix_mojibake('app_version') }} as app_version,
        {{ clean_code('site_id') }} as site_id,
        {{ fix_mojibake('screen_name') }} as screen_name,
        {{ clean_integer('duration_ms') }} as duration_ms,
        try_cast(is_conversion as boolean) as is_conversion,
        {{ fix_mojibake('network_type') }} as network_type,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (digital_event_id is not null) as _dq_digital_event_id_present,
        (event_ts is not null) as _dq_event_timestamp_valid,
        (coalesce(_dq_digital_event_id_present, false) and coalesce(_dq_event_timestamp_valid, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_digital_event_id_present, false) then 'digital_event_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
