-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 1 of 2 in the cleansing layer: repair every column and
-- assess every row, once. `stg_` and `qtn_` both read from here,
-- so the expensive parsing is not paid for twice.

with source as (
    select * from {{ source('lake_facts', 'fact_promotions') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('promotion_fact_id') }} as promotion_fact_id,
        {{ clean_timestamp('measurement_date') }} as measurement_date,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_code('promotion_id') }} as promotion_id,
        {{ clean_measure('baseline_units') }} as baseline_units,
        {{ clean_measure('promoted_units') }} as promoted_units,
        {{ clean_measure('uplift_pct') }} as uplift_pct,
        {{ clean_measure('discount_cost_zar') }} as discount_cost_zar,
        {{ clean_measure('incremental_margin_zar') }} as incremental_margin_zar,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (promotion_id is not null) as _dq_promotion_id_present,
        (site_id is not null) as _dq_site_id_present,
        (measurement_date is not null) as _dq_event_timestamp_valid,
        (discount_cost_zar >= 0) as _dq_discount_cost_zar_non_negative,
        (incremental_margin_zar >= 0) as _dq_incremental_margin_zar_non_negative,
        (coalesce(_dq_promotion_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_discount_cost_zar_non_negative, false) and coalesce(_dq_incremental_margin_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_promotion_id_present, false) then 'promotion_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_discount_cost_zar_non_negative, false) then 'discount_cost_zar_non_negative' end,
            case when not coalesce(_dq_incremental_margin_zar_non_negative, false) then 'incremental_margin_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

select
    *,
    {{ cleansing_layer_columns() }}
from assessed
