-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_price_changes') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('price_change_id') }} as price_change_id,
        {{ clean_timestamp('effective_ts') }} as effective_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_code('product_id') }} as product_id,
        {{ clean_measure('old_price_zar') }} as old_price_zar,
        {{ clean_measure('new_price_zar') }} as new_price_zar,
        {{ clean_measure('change_cents_per_litre') }} as change_cents_per_litre,
        {{ fix_mojibake('change_reason') }} as change_reason,
        {{ clean_code('approved_by_employee_id') }} as approved_by_employee_id,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (price_change_id is not null) as _dq_price_change_id_present,
        (site_id is not null) as _dq_site_id_present,
        (product_id is not null) as _dq_product_id_present,
        (effective_ts is not null) as _dq_event_timestamp_valid,
        (old_price_zar >= 0) as _dq_old_price_zar_non_negative,
        (new_price_zar >= 0) as _dq_new_price_zar_non_negative,
        (coalesce(_dq_price_change_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_old_price_zar_non_negative, false) and coalesce(_dq_new_price_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_price_change_id_present, false) then 'price_change_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_old_price_zar_non_negative, false) then 'old_price_zar_non_negative' end,
            case when not coalesce(_dq_new_price_zar_non_negative, false) then 'new_price_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'fact_price_changes' as _source_table,
    price_change_id,
    effective_ts,
    date_key,
    site_id,
    product_id,
    old_price_zar,
    new_price_zar,
    change_cents_per_litre,
    change_reason,
    approved_by_employee_id,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
