-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_solar_generation') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('solar_reading_id') }} as solar_reading_id,
        {{ clean_timestamp('reading_ts') }} as reading_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_integer('time_key') }} as time_key,
        {{ clean_code('solar_asset_id') }} as solar_asset_id,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_measure('installed_kwp') }} as installed_kwp,
        {{ clean_integer('interval_minutes') }} as interval_minutes,
        {{ correct_unit_error(clean_measure('energy_kwh'), 400) }} as energy_kwh,
        {{ clean_measure('irradiance_w_m2') }} as irradiance_w_m2,
        {{ clean_measure('panel_temperature_celsius') }} as panel_temperature_celsius,
        {{ clean_measure('inverter_efficiency_pct') }} as inverter_efficiency_pct,
        {{ clean_measure('capacity_factor') }} as capacity_factor,
        try_cast(is_daylight as boolean) as is_daylight,
        {{ clean_measure('co2_avoided_kg') }} as co2_avoided_kg,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (solar_reading_id is not null) as _dq_solar_reading_id_present,
        (site_id is not null) as _dq_site_id_present,
        (reading_ts is not null) as _dq_event_timestamp_valid,
        (energy_kwh >= 0) as _dq_energy_kwh_non_negative,
        (energy_kwh <= 400) as _dq_energy_kwh_within_range,
        (coalesce(_dq_solar_reading_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_energy_kwh_non_negative, false) and coalesce(_dq_energy_kwh_within_range, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_solar_reading_id_present, false) then 'solar_reading_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_energy_kwh_non_negative, false) then 'energy_kwh_non_negative' end,
            case when not coalesce(_dq_energy_kwh_within_range, false) then 'energy_kwh_within_range' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'fact_solar_generation' as _source_table,
    solar_reading_id,
    reading_ts,
    date_key,
    time_key,
    solar_asset_id,
    site_id,
    installed_kwp,
    interval_minutes,
    energy_kwh,
    irradiance_w_m2,
    panel_temperature_celsius,
    inverter_efficiency_pct,
    capacity_factor,
    is_daylight,
    co2_avoided_kg,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
