-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_terminal_issues') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('terminal_issue_id') }} as terminal_issue_id,
        {{ clean_timestamp('issue_ts') }} as issue_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('terminal_id') }} as terminal_id,
        {{ clean_code('product_id') }} as product_id,
        {{ clean_code('vehicle_id') }} as vehicle_id,
        {{ clean_integer('gantry_bay') }} as gantry_bay,
        {{ clean_measure('issued_litres') }} as issued_litres,
        {{ clean_measure('loading_minutes') }} as loading_minutes,
        {{ clean_measure('queue_minutes') }} as queue_minutes,
        {{ clean_code('destination_site_id') }} as destination_site_id,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (terminal_issue_id is not null) as _dq_terminal_issue_id_present,
        (product_id is not null) as _dq_product_id_present,
        (issue_ts is not null) as _dq_event_timestamp_valid,
        (coalesce(_dq_terminal_issue_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_terminal_issue_id_present, false) then 'terminal_issue_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'fact_terminal_issues' as _source_table,
    terminal_issue_id,
    issue_ts,
    date_key,
    terminal_id,
    product_id,
    vehicle_id,
    gantry_bay,
    issued_litres,
    loading_minutes,
    queue_minutes,
    destination_site_id,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
