-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_commercial_deliveries' as _source_table,
    commercial_delivery_id,
    planned_delivery_ts,
    actual_delivery_ts,
    date_key,
    customer_id,
    order_id,
    product_id,
    vehicle_id,
    ordered_litres,
    delivered_litres,
    delay_minutes,
    is_on_time,
    is_in_full,
    otif_flag,
    delivery_status,
    failure_reason_code,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_commercial_deliveries') }}
where not _dq_is_valid
