-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_working_capital' as _source_table,
    working_capital_id,
    period_date,
    date_key,
    legal_entity_code,
    business_unit_code,
    receivables_zar,
    inventory_zar,
    payables_zar,
    days_sales_outstanding,
    days_inventory_outstanding,
    days_payables_outstanding,
    cash_conversion_cycle_days,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_working_capital') }}
where not _dq_is_valid
