-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'bridge_supplier_product' as _source_table,
    supplier_id,
    product_id,
    is_approved,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_bridge_supplier_product') }}
where not _dq_is_valid
