-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_customer_receipts' as _source_table,
    receipt_id,
    receipt_date,
    date_key,
    customer_id,
    invoice_id,
    amount_received_zar,
    payment_channel,
    is_partial_payment,
    allocated_flag,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_customer_receipts') }}
where not _dq_is_valid
