-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'bridge_site_product') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('site_id') }} as site_id,
        {{ clean_code('product_id') }} as product_id,
        try_cast(is_primary_grade as boolean) as is_primary_grade,
        {{ clean_timestamp('listed_from_date') }} as listed_from_date,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (site_id is not null) as _dq_site_id_present,
        (product_id is not null) as _dq_product_id_present,
        (coalesce(_dq_site_id_present, false) and coalesce(_dq_product_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'bridge_site_product' as _source_table,
    site_id,
    product_id,
    is_primary_grade,
    listed_from_date,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
