-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_inventory_adjustments' as _source_table,
    adjustment_id,
    adjustment_ts,
    date_key,
    site_id,
    product_id,
    book_stock_litres,
    physical_stock_litres,
    variance_litres,
    variance_pct,
    adjustment_reason,
    requires_investigation,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_inventory_adjustments') }}
where not _dq_is_valid
