-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_marine_inventory_snapshot') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('marine_snapshot_id') }} as marine_snapshot_id,
        {{ clean_timestamp('snapshot_ts') }} as snapshot_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('port_code') }} as port_code,
        {{ clean_code('product_id') }} as product_id,
        {{ clean_measure('capacity_litres') }} as capacity_litres,
        {{ clean_measure('stock_on_hand_litres') }} as stock_on_hand_litres,
        {{ clean_measure('days_of_cover') }} as days_of_cover,
        {{ clean_measure('viscosity_cst') }} as viscosity_cst,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (marine_snapshot_id is not null) as _dq_marine_snapshot_id_present,
        (product_id is not null) as _dq_product_id_present,
        (snapshot_ts is not null) as _dq_event_timestamp_valid,
        (coalesce(_dq_marine_snapshot_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_marine_snapshot_id_present, false) then 'marine_snapshot_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'fact_marine_inventory_snapshot' as _source_table,
    marine_snapshot_id,
    snapshot_ts,
    date_key,
    port_code,
    product_id,
    capacity_litres,
    stock_on_hand_litres,
    days_of_cover,
    viscosity_cst,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
