-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_asset_downtime') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('downtime_id') }} as downtime_id,
        {{ clean_timestamp('downtime_start_ts') }} as downtime_start_ts,
        {{ clean_timestamp('downtime_end_ts') }} as downtime_end_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('asset_id') }} as asset_id,
        {{ clean_code('site_id') }} as site_id,
        {{ fix_mojibake('asset_type') }} as asset_type,
        {{ clean_measure('downtime_hours') }} as downtime_hours,
        try_cast(is_planned as boolean) as is_planned,
        {{ fix_mojibake('downtime_category') }} as downtime_category,
        {{ clean_measure('lost_volume_litres') }} as lost_volume_litres,
        {{ clean_measure('lost_revenue_zar') }} as lost_revenue_zar,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (downtime_id is not null) as _dq_downtime_id_present,
        (site_id is not null) as _dq_site_id_present,
        (downtime_start_ts is not null) as _dq_event_timestamp_valid,
        (lost_revenue_zar >= 0) as _dq_lost_revenue_zar_non_negative,
        (coalesce(_dq_downtime_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_lost_revenue_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_downtime_id_present, false) then 'downtime_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_lost_revenue_zar_non_negative, false) then 'lost_revenue_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'fact_asset_downtime' as _source_table,
    downtime_id,
    downtime_start_ts,
    downtime_end_ts,
    date_key,
    asset_id,
    site_id,
    asset_type,
    downtime_hours,
    is_planned,
    downtime_category,
    lost_volume_litres,
    lost_revenue_zar,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
