-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_lpg_sales') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('lpg_sale_id') }} as lpg_sale_id,
        {{ clean_timestamp('sale_ts') }} as sale_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_code('customer_id') }} as customer_id,
        {{ clean_code('product_id') }} as product_id,
        {{ clean_code('cylinder_type_code') }} as cylinder_type_code,
        {{ correct_unit_error(clean_measure('quantity_kg'), 60000) }} as quantity_kg,
        {{ clean_measure('unit_price_zar') }} as unit_price_zar,
        {{ clean_measure('revenue_zar') }} as revenue_zar,
        {{ clean_measure('cogs_zar') }} as cogs_zar,
        {{ clean_measure('gross_margin_zar') }} as gross_margin_zar,
        {{ fix_mojibake('channel') }} as channel,
        try_cast(is_winter_peak as boolean) as is_winter_peak,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (lpg_sale_id is not null) as _dq_lpg_sale_id_present,
        (site_id is not null) as _dq_site_id_present,
        (customer_id is not null) as _dq_customer_id_present,
        (product_id is not null) as _dq_product_id_present,
        (sale_ts is not null) as _dq_event_timestamp_valid,
        (quantity_kg >= 0) as _dq_quantity_kg_non_negative,
        (quantity_kg <= 60000) as _dq_quantity_kg_within_range,
        (unit_price_zar >= 0) as _dq_unit_price_zar_non_negative,
        (revenue_zar >= 0) as _dq_revenue_zar_non_negative,
        (cogs_zar >= 0) as _dq_cogs_zar_non_negative,
        (gross_margin_zar >= 0) as _dq_gross_margin_zar_non_negative,
        (coalesce(_dq_lpg_sale_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_customer_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_quantity_kg_non_negative, false) and coalesce(_dq_quantity_kg_within_range, false) and coalesce(_dq_unit_price_zar_non_negative, false) and coalesce(_dq_revenue_zar_non_negative, false) and coalesce(_dq_cogs_zar_non_negative, false) and coalesce(_dq_gross_margin_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_lpg_sale_id_present, false) then 'lpg_sale_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_customer_id_present, false) then 'customer_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_quantity_kg_non_negative, false) then 'quantity_kg_non_negative' end,
            case when not coalesce(_dq_quantity_kg_within_range, false) then 'quantity_kg_within_range' end,
            case when not coalesce(_dq_unit_price_zar_non_negative, false) then 'unit_price_zar_non_negative' end,
            case when not coalesce(_dq_revenue_zar_non_negative, false) then 'revenue_zar_non_negative' end,
            case when not coalesce(_dq_cogs_zar_non_negative, false) then 'cogs_zar_non_negative' end,
            case when not coalesce(_dq_gross_margin_zar_non_negative, false) then 'gross_margin_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'fact_lpg_sales' as _source_table,
    lpg_sale_id,
    sale_ts,
    date_key,
    site_id,
    customer_id,
    product_id,
    cylinder_type_code,
    quantity_kg,
    unit_price_zar,
    revenue_zar,
    cogs_zar,
    gross_margin_zar,
    channel,
    is_winter_peak,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
