-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_campaign') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('campaign_id') }} as campaign_id,
        {{ clean_integer('campaign_key') }} as campaign_key,
        {{ fix_mojibake('campaign_name') }} as campaign_name,
        {{ fix_mojibake('channel') }} as channel,
        {{ clean_timestamp('start_date') }} as start_date,
        {{ clean_timestamp('end_date') }} as end_date,
        {{ clean_measure('budget_zar') }} as budget_zar,
        {{ fix_mojibake('target_segment') }} as target_segment
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (campaign_id is not null) as _dq_campaign_id_present,
        (budget_zar >= 0) as _dq_budget_zar_non_negative,
        (coalesce(_dq_campaign_id_present, false) and coalesce(_dq_budget_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_campaign_id_present, false) then 'campaign_id_present' end,
            case when not coalesce(_dq_budget_zar_non_negative, false) then 'budget_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

-- Rows that failed the contract. Kept, not dropped: a
-- silently discarded row becomes an unexplainable variance
-- months later, and there is no way back from it.
select
    'dim_campaign' as _source_table,
    campaign_id,
    campaign_key,
    campaign_name,
    channel,
    start_date,
    end_date,
    budget_zar,
    target_segment,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
