-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_tank_dips' as _source_table,
    tank_dip_id,
    dip_ts,
    date_key,
    tank_id,
    site_id,
    product_id,
    capacity_litres,
    volume_litres,
    ullage_litres,
    fill_pct,
    water_level_mm,
    temperature_celsius,
    below_reorder_point,
    reading_source,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_tank_dips') }}
where not _dq_is_valid
