-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_vehicle') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('vehicle_id') }} as vehicle_id,
        {{ clean_integer('vehicle_key') }} as vehicle_key,
        {{ clean_code('carrier_id') }} as carrier_id,
        {{ fix_mojibake('vehicle_type') }} as vehicle_type,
        {{ clean_integer('capacity_litres') }} as capacity_litres,
        {{ clean_integer('compartments') }} as compartments,
        {{ clean_integer('model_year') }} as model_year,
        try_cast(telematics_enabled as boolean) as telematics_enabled,
        try_cast(is_active as boolean) as is_active
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (vehicle_id is not null) as _dq_vehicle_id_present,
        (coalesce(_dq_vehicle_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_vehicle_id_present, false) then 'vehicle_id_present' end
        ) as _dq_failed_rules
    from cleansed
)

-- Rows that failed the contract. Kept, not dropped: a
-- silently discarded row becomes an unexplainable variance
-- months later, and there is no way back from it.
select
    'dim_vehicle' as _source_table,
    vehicle_id,
    vehicle_key,
    carrier_id,
    vehicle_type,
    capacity_litres,
    compartments,
    model_year,
    telematics_enabled,
    is_active,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
