-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_asset_inspections' as _source_table,
    inspection_id,
    inspection_ts,
    date_key,
    asset_id,
    site_id,
    inspection_type,
    inspector_employee_id,
    result,
    defects_found,
    condition_score,
    next_due_date,
    is_overdue,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_asset_inspections') }}
where not _dq_is_valid
