-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_safety_observations' as _source_table,
    observation_id,
    observation_ts,
    date_key,
    site_id,
    observer_employee_id,
    observation_type,
    category,
    is_positive,
    action_required,
    closed_flag,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_safety_observations') }}
where not _dq_is_valid
