-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_vehicle_safety_events' as _source_table,
    vehicle_safety_event_id,
    event_ts,
    date_key,
    vehicle_id,
    driver_id,
    event_type,
    severity,
    speed_kph,
    speed_limit_kph,
    g_force,
    latitude,
    longitude,
    resulted_in_incident,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_vehicle_safety_events') }}
where not _dq_is_valid
