-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'dim_supplier' as _source_table,
    supplier_id,
    supplier_key,
    supplier_name,
    supplier_type,
    country_code,
    risk_rating,
    esg_score,
    preferred_supplier,
    contract_start_date,
    effective_from_date,
    effective_to_date,
    is_current,
    scd_version,
    record_source,
    dw_load_ts,
    dw_hash_diff,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_dim_supplier') }}
where not _dq_is_valid
