-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_permit_to_work' as _source_table,
    permit_id,
    issued_ts,
    date_key,
    site_id,
    permit_type,
    contractor_flag,
    issued_by_employee_id,
    planned_duration_hours,
    closed_ts,
    isolations_required,
    gas_test_performed,
    closed_correctly,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_permit_to_work') }}
where not _dq_is_valid
