-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_energy_costs' as _source_table,
    energy_cost_id,
    billing_period_start,
    date_key,
    site_id,
    energy_source,
    consumption_kwh,
    unit_rate_zar_per_kwh,
    demand_charge_zar,
    energy_charge_zar,
    total_cost_zar,
    carbon_kg,
    cost_centre_code,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_energy_costs') }}
where not _dq_is_valid
