-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_facts', 'fact_lpg_bulk_deliveries') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('lpg_delivery_id') }} as lpg_delivery_id,
        {{ clean_timestamp('delivery_ts') }} as delivery_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('customer_id') }} as customer_id,
        {{ clean_code('depot_id') }} as depot_id,
        {{ clean_code('vehicle_id') }} as vehicle_id,
        {{ clean_measure('delivered_kg') }} as delivered_kg,
        {{ clean_measure('tank_fill_pct_before') }} as tank_fill_pct_before,
        {{ clean_measure('tank_fill_pct_after') }} as tank_fill_pct_after,
        {{ clean_measure('revenue_zar') }} as revenue_zar,
        try_cast(is_emergency_delivery as boolean) as is_emergency_delivery,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (lpg_delivery_id is not null) as _dq_lpg_delivery_id_present,
        (customer_id is not null) as _dq_customer_id_present,
        (delivery_ts is not null) as _dq_event_timestamp_valid,
        (revenue_zar >= 0) as _dq_revenue_zar_non_negative,
        (coalesce(_dq_lpg_delivery_id_present, false) and coalesce(_dq_customer_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_revenue_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_lpg_delivery_id_present, false) then 'lpg_delivery_id_present' end,
            case when not coalesce(_dq_customer_id_present, false) then 'customer_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_revenue_zar_non_negative, false) then 'revenue_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

-- Rows that failed the contract. Kept, not dropped: a
-- silently discarded row becomes an unexplainable variance
-- months later, and there is no way back from it.
select
    'fact_lpg_bulk_deliveries' as _source_table,
    lpg_delivery_id,
    delivery_ts,
    date_key,
    customer_id,
    depot_id,
    vehicle_id,
    delivered_kg,
    tank_fill_pct_before,
    tank_fill_pct_after,
    revenue_zar,
    is_emergency_delivery,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
