-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_import_cargoes' as _source_table,
    cargo_id,
    eta_ts,
    date_key,
    discharge_port_code,
    supplier_id,
    product_id,
    cargo_volume_litres,
    discharge_hours,
    demurrage_hours,
    demurrage_cost_usd,
    landed_cost_zar_per_litre,
    vessel_imo,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_import_cargoes') }}
where not _dq_is_valid
