-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_contract_volume_commitments' as _source_table,
    commitment_id,
    period_start_date,
    date_key,
    contract_id,
    customer_id,
    product_id,
    committed_litres,
    achieved_litres,
    achievement_pct,
    is_shortfall,
    shortfall_penalty_zar,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_contract_volume_commitments') }}
where not _dq_is_valid
