-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_training_compliance' as _source_table,
    training_record_id,
    completed_date,
    date_key,
    employee_id,
    site_id,
    course_name,
    result,
    score_pct,
    expiry_date,
    is_expired,
    is_mandatory,
    training_hours,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_training_compliance') }}
where not _dq_is_valid
