-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'dim_loyalty_member' as _source_table,
    loyalty_member_id,
    loyalty_member_key,
    tier,
    joined_date,
    home_site_id,
    opt_in_marketing,
    is_active,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_dim_loyalty_member') }}
where not _dq_is_valid
