-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_maintenance_work_orders') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('work_order_id') }} as work_order_id,
        {{ clean_timestamp('raised_ts') }} as raised_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('asset_id') }} as asset_id,
        {{ clean_code('site_id') }} as site_id,
        {{ fix_mojibake('asset_type') }} as asset_type,
        {{ fix_mojibake('criticality') }} as criticality,
        {{ clean_measure('asset_age_years') }} as asset_age_years,
        {{ fix_mojibake('maintenance_type') }} as maintenance_type,
        {{ fix_mojibake('failure_mode') }} as failure_mode,
        {{ fix_mojibake('priority') }} as priority,
        {{ clean_measure('response_hours') }} as response_hours,
        {{ clean_measure('labour_hours') }} as labour_hours,
        {{ clean_measure('labour_cost_zar') }} as labour_cost_zar,
        {{ clean_measure('parts_cost_zar') }} as parts_cost_zar,
        {{ clean_measure('total_cost_zar') }} as total_cost_zar,
        {{ clean_timestamp('completed_ts') }} as completed_ts,
        try_cast(is_completed as boolean) as is_completed,
        try_cast(is_breakdown as boolean) as is_breakdown,
        {{ clean_code('technician_employee_id') }} as technician_employee_id,
        try_cast(sla_breached as boolean) as sla_breached,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (work_order_id is not null) as _dq_work_order_id_present,
        (site_id is not null) as _dq_site_id_present,
        (raised_ts is not null) as _dq_event_timestamp_valid,
        (labour_cost_zar >= 0) as _dq_labour_cost_zar_non_negative,
        (parts_cost_zar >= 0) as _dq_parts_cost_zar_non_negative,
        (total_cost_zar >= 0) as _dq_total_cost_zar_non_negative,
        (coalesce(_dq_work_order_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_labour_cost_zar_non_negative, false) and coalesce(_dq_parts_cost_zar_non_negative, false) and coalesce(_dq_total_cost_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_work_order_id_present, false) then 'work_order_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_labour_cost_zar_non_negative, false) then 'labour_cost_zar_non_negative' end,
            case when not coalesce(_dq_parts_cost_zar_non_negative, false) then 'parts_cost_zar_non_negative' end,
            case when not coalesce(_dq_total_cost_zar_non_negative, false) then 'total_cost_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'fact_maintenance_work_orders' as _source_table,
    work_order_id,
    raised_ts,
    date_key,
    asset_id,
    site_id,
    asset_type,
    criticality,
    asset_age_years,
    maintenance_type,
    failure_mode,
    priority,
    response_hours,
    labour_hours,
    labour_cost_zar,
    parts_cost_zar,
    total_cost_zar,
    completed_ts,
    is_completed,
    is_breakdown,
    technician_employee_id,
    sla_breached,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
