-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_capex' as _source_table,
    capex_id,
    period_date,
    date_key,
    project_code,
    site_id,
    capex_category,
    budget_zar,
    actual_spend_zar,
    variance_zar,
    variance_pct,
    expected_irr_pct,
    payback_years,
    project_status,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_capex') }}
where not _dq_is_valid
