-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_mobile_payments' as _source_table,
    mobile_payment_id,
    payment_ts,
    date_key,
    digital_user_id,
    site_id,
    amount_zar,
    payment_instrument,
    is_approved,
    decline_reason,
    processing_ms,
    is_flagged_fraud,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_mobile_payments') }}
where not _dq_is_valid
