-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_replenishment_orders' as _source_table,
    replenishment_id,
    raised_ts,
    date_key,
    site_id,
    terminal_id,
    product_id,
    requested_litres,
    trigger_type,
    days_of_cover_at_raise,
    promised_delivery_ts,
    fulfilled_flag,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_replenishment_orders') }}
where not _dq_is_valid
