-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_deliveries' as _source_table,
    delivery_id,
    planned_arrival_ts,
    actual_arrival_ts,
    date_key,
    route_id,
    origin_terminal_id,
    destination_site_id,
    vehicle_id,
    driver_id,
    carrier_id,
    product_id,
    planned_litres,
    delivered_litres,
    fill_rate_pct,
    distance_km,
    drop_count,
    delay_minutes,
    is_late,
    otif_flag,
    delivery_status,
    reason_code,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_deliveries') }}
where not _dq_is_valid
