-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'bridge_customer_hierarchy' as _source_table,
    parent_customer_id,
    child_customer_id,
    hierarchy_level,
    ownership_pct,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_bridge_customer_hierarchy') }}
where not _dq_is_valid
