-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'dim_vehicle' as _source_table,
    vehicle_id,
    vehicle_key,
    carrier_id,
    vehicle_type,
    capacity_litres,
    compartments,
    model_year,
    telematics_enabled,
    is_active,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_dim_vehicle') }}
where not _dq_is_valid
