-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_site') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('site_id') }} as site_id,
        {{ fix_mojibake('site_name') }} as site_name,
        {{ clean_code('country_code') }} as country_code,
        {{ fix_mojibake('province') }} as province,
        {{ fix_mojibake('city') }} as city,
        {{ fix_mojibake('urban_class') }} as urban_class,
        {{ clean_measure('latitude') }} as latitude,
        {{ clean_measure('longitude') }} as longitude,
        {{ fix_mojibake('site_type') }} as site_type,
        {{ fix_mojibake('ownership_model') }} as ownership_model,
        try_cast(on_national_route as boolean) as on_national_route,
        {{ clean_integer('site_key') }} as site_key,
        {{ clean_integer('forecourt_lanes') }} as forecourt_lanes,
        try_cast(has_convenience as boolean) as has_convenience,
        try_cast(has_qsr as boolean) as has_qsr,
        try_cast(has_car_wash as boolean) as has_car_wash,
        try_cast(has_ev_charging as boolean) as has_ev_charging,
        try_cast(has_solar as boolean) as has_solar,
        try_cast(has_lpg as boolean) as has_lpg,
        try_cast(is_24_hour as boolean) as is_24_hour,
        {{ clean_timestamp('opened_date') }} as opened_date,
        {{ fix_mojibake('site_status') }} as site_status,
        {{ clean_measure('demand_index') }} as demand_index,
        {{ clean_timestamp('effective_from_date') }} as effective_from_date,
        {{ clean_timestamp('effective_to_date') }} as effective_to_date,
        try_cast(is_current as boolean) as is_current,
        {{ clean_integer('scd_version') }} as scd_version,
        {{ fix_mojibake('record_source') }} as record_source,
        {{ clean_timestamp('dw_load_ts') }} as dw_load_ts,
        {{ fix_mojibake('dw_hash_diff') }} as dw_hash_diff,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (site_id is not null) as _dq_site_id_present,
        (coalesce(_dq_site_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'dim_site' as _source_table,
    site_id,
    site_name,
    country_code,
    province,
    city,
    urban_class,
    latitude,
    longitude,
    site_type,
    ownership_model,
    on_national_route,
    site_key,
    forecourt_lanes,
    has_convenience,
    has_qsr,
    has_car_wash,
    has_ev_charging,
    has_solar,
    has_lpg,
    is_24_hour,
    opened_date,
    site_status,
    demand_index,
    effective_from_date,
    effective_to_date,
    is_current,
    scd_version,
    record_source,
    dw_load_ts,
    dw_hash_diff,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
