-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_accounts_receivable' as _source_table,
    ar_id,
    snapshot_date,
    date_key,
    customer_id,
    invoice_id,
    outstanding_zar,
    days_outstanding,
    ageing_bucket,
    credit_band,
    provision_pct,
    is_doubtful,
    provision_zar,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_accounts_receivable') }}
where not _dq_is_valid
