-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_facts', 'fact_customer_receipts') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('receipt_id') }} as receipt_id,
        {{ clean_timestamp('receipt_date') }} as receipt_date,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('customer_id') }} as customer_id,
        {{ clean_code('invoice_id') }} as invoice_id,
        {{ clean_measure('amount_received_zar') }} as amount_received_zar,
        {{ fix_mojibake('payment_channel') }} as payment_channel,
        try_cast(is_partial_payment as boolean) as is_partial_payment,
        try_cast(allocated_flag as boolean) as allocated_flag,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (receipt_id is not null) as _dq_receipt_id_present,
        (customer_id is not null) as _dq_customer_id_present,
        (receipt_date is not null) as _dq_event_timestamp_valid,
        (amount_received_zar >= 0) as _dq_amount_received_zar_non_negative,
        (coalesce(_dq_receipt_id_present, false) and coalesce(_dq_customer_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_amount_received_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_receipt_id_present, false) then 'receipt_id_present' end,
            case when not coalesce(_dq_customer_id_present, false) then 'customer_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_amount_received_zar_non_negative, false) then 'amount_received_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

-- Rows that failed the contract. Kept, not dropped: a
-- silently discarded row becomes an unexplainable variance
-- months later, and there is no way back from it.
select
    'fact_customer_receipts' as _source_table,
    receipt_id,
    receipt_date,
    date_key,
    customer_id,
    invoice_id,
    amount_received_zar,
    payment_channel,
    is_partial_payment,
    allocated_flag,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
