-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_inventory_movements') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('movement_id') }} as movement_id,
        {{ clean_timestamp('movement_ts') }} as movement_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ fix_mojibake('movement_type') }} as movement_type,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_code('terminal_id') }} as terminal_id,
        {{ clean_code('product_id') }} as product_id,
        {{ correct_unit_error(clean_measure('quantity_litres'), 15000000) }} as quantity_litres,
        {{ clean_measure('signed_quantity_litres') }} as signed_quantity_litres,
        {{ clean_code('reason_code') }} as reason_code,
        {{ clean_code('posted_by_employee_id') }} as posted_by_employee_id,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (movement_id is not null) as _dq_movement_id_present,
        (site_id is not null) as _dq_site_id_present,
        (product_id is not null) as _dq_product_id_present,
        (movement_ts is not null) as _dq_event_timestamp_valid,
        (quantity_litres >= 0) as _dq_quantity_litres_non_negative,
        (quantity_litres <= 15000000) as _dq_quantity_litres_within_range,
        (coalesce(_dq_movement_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_quantity_litres_non_negative, false) and coalesce(_dq_quantity_litres_within_range, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_movement_id_present, false) then 'movement_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_quantity_litres_non_negative, false) then 'quantity_litres_non_negative' end,
            case when not coalesce(_dq_quantity_litres_within_range, false) then 'quantity_litres_within_range' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'fact_inventory_movements' as _source_table,
    movement_id,
    movement_ts,
    date_key,
    movement_type,
    site_id,
    terminal_id,
    product_id,
    quantity_litres,
    signed_quantity_litres,
    reason_code,
    posted_by_employee_id,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
