-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'dim_promotion' as _source_table,
    promotion_id,
    promotion_key,
    promotion_name,
    mechanic,
    start_date,
    end_date,
    discount_pct,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_dim_promotion') }}
where not _dq_is_valid
