-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_loyalty_points_balance') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('points_balance_id') }} as points_balance_id,
        {{ clean_timestamp('snapshot_date') }} as snapshot_date,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('loyalty_member_id') }} as loyalty_member_id,
        {{ clean_integer('opening_points') }} as opening_points,
        {{ clean_integer('points_earned') }} as points_earned,
        {{ clean_integer('points_burned') }} as points_burned,
        {{ clean_integer('points_expired') }} as points_expired,
        {{ clean_integer('closing_points') }} as closing_points,
        {{ clean_measure('liability_zar') }} as liability_zar,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (points_balance_id is not null) as _dq_points_balance_id_present,
        (snapshot_date is not null) as _dq_event_timestamp_valid,
        (liability_zar >= 0) as _dq_liability_zar_non_negative,
        (coalesce(_dq_points_balance_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_liability_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_points_balance_id_present, false) then 'points_balance_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_liability_zar_non_negative, false) then 'liability_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'fact_loyalty_points_balance' as _source_table,
    points_balance_id,
    snapshot_date,
    date_key,
    loyalty_member_id,
    opening_points,
    points_earned,
    points_burned,
    points_expired,
    closing_points,
    liability_zar,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
