-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'dim_ev_charger' as _source_table,
    ev_charger_id,
    ev_charger_key,
    site_id,
    connector_type,
    rated_power_kw,
    commissioned_date,
    network_operator,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_dim_ev_charger') }}
where not _dq_is_valid
