-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_facts', 'fact_asset_failures') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('failure_id') }} as failure_id,
        {{ clean_timestamp('failure_ts') }} as failure_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('asset_id') }} as asset_id,
        {{ clean_code('site_id') }} as site_id,
        {{ fix_mojibake('asset_type') }} as asset_type,
        {{ clean_measure('asset_age_years') }} as asset_age_years,
        {{ fix_mojibake('failure_mode') }} as failure_mode,
        {{ fix_mojibake('detection_method') }} as detection_method,
        {{ clean_measure('time_to_repair_hours') }} as time_to_repair_hours,
        {{ clean_measure('repair_cost_zar') }} as repair_cost_zar,
        try_cast(is_repeat_failure as boolean) as is_repeat_failure,
        try_cast(root_cause_identified as boolean) as root_cause_identified,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (failure_id is not null) as _dq_failure_id_present,
        (site_id is not null) as _dq_site_id_present,
        (failure_ts is not null) as _dq_event_timestamp_valid,
        (repair_cost_zar >= 0) as _dq_repair_cost_zar_non_negative,
        (coalesce(_dq_failure_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_repair_cost_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_failure_id_present, false) then 'failure_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_repair_cost_zar_non_negative, false) then 'repair_cost_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

-- Rows that failed the contract. Kept, not dropped: a
-- silently discarded row becomes an unexplainable variance
-- months later, and there is no way back from it.
select
    'fact_asset_failures' as _source_table,
    failure_id,
    failure_ts,
    date_key,
    asset_id,
    site_id,
    asset_type,
    asset_age_years,
    failure_mode,
    detection_method,
    time_to_repair_hours,
    repair_cost_zar,
    is_repeat_failure,
    root_cause_identified,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
