-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_facts', 'fact_energy_costs') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('energy_cost_id') }} as energy_cost_id,
        {{ clean_timestamp('billing_period_start') }} as billing_period_start,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('site_id') }} as site_id,
        {{ fix_mojibake('energy_source') }} as energy_source,
        {{ clean_measure('consumption_kwh') }} as consumption_kwh,
        {{ clean_measure('unit_rate_zar_per_kwh') }} as unit_rate_zar_per_kwh,
        {{ clean_measure('demand_charge_zar') }} as demand_charge_zar,
        {{ clean_measure('energy_charge_zar') }} as energy_charge_zar,
        {{ clean_measure('total_cost_zar') }} as total_cost_zar,
        {{ clean_measure('carbon_kg') }} as carbon_kg,
        {{ clean_code('cost_centre_code') }} as cost_centre_code,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (energy_cost_id is not null) as _dq_energy_cost_id_present,
        (site_id is not null) as _dq_site_id_present,
        (billing_period_start is not null) as _dq_event_timestamp_valid,
        (demand_charge_zar >= 0) as _dq_demand_charge_zar_non_negative,
        (energy_charge_zar >= 0) as _dq_energy_charge_zar_non_negative,
        (total_cost_zar >= 0) as _dq_total_cost_zar_non_negative,
        (coalesce(_dq_energy_cost_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_demand_charge_zar_non_negative, false) and coalesce(_dq_energy_charge_zar_non_negative, false) and coalesce(_dq_total_cost_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_energy_cost_id_present, false) then 'energy_cost_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_demand_charge_zar_non_negative, false) then 'demand_charge_zar_non_negative' end,
            case when not coalesce(_dq_energy_charge_zar_non_negative, false) then 'energy_charge_zar_non_negative' end,
            case when not coalesce(_dq_total_cost_zar_non_negative, false) then 'total_cost_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
)

-- Rows that failed the contract. Kept, not dropped: a
-- silently discarded row becomes an unexplainable variance
-- months later, and there is no way back from it.
select
    'fact_energy_costs' as _source_table,
    energy_cost_id,
    billing_period_start,
    date_key,
    site_id,
    energy_source,
    consumption_kwh,
    unit_rate_zar_per_kwh,
    demand_charge_zar,
    energy_charge_zar,
    total_cost_zar,
    carbon_kg,
    cost_centre_code,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
