-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_stock_losses') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('stock_loss_id') }} as stock_loss_id,
        {{ clean_timestamp('loss_date') }} as loss_date,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_code('terminal_id') }} as terminal_id,
        {{ clean_code('product_id') }} as product_id,
        {{ clean_measure('loss_litres') }} as loss_litres,
        {{ clean_measure('loss_value_zar') }} as loss_value_zar,
        {{ fix_mojibake('loss_category') }} as loss_category,
        try_cast(is_recoverable as boolean) as is_recoverable,
        try_cast(insurance_claim_raised as boolean) as insurance_claim_raised,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (stock_loss_id is not null) as _dq_stock_loss_id_present,
        (site_id is not null) as _dq_site_id_present,
        (product_id is not null) as _dq_product_id_present,
        (loss_date is not null) as _dq_event_timestamp_valid,
        (loss_value_zar >= 0) as _dq_loss_value_zar_non_negative,
        (coalesce(_dq_stock_loss_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_loss_value_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_stock_loss_id_present, false) then 'stock_loss_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_loss_value_zar_non_negative, false) then 'loss_value_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'fact_stock_losses' as _source_table,
    stock_loss_id,
    loss_date,
    date_key,
    site_id,
    terminal_id,
    product_id,
    loss_litres,
    loss_value_zar,
    loss_category,
    is_recoverable,
    insurance_claim_raised,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
