-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_shop_sales' as _source_table,
    shop_line_id,
    basket_id,
    transaction_ts,
    date_key,
    time_key,
    site_id,
    product_id,
    quantity,
    unit_price_zar,
    gross_sales_zar,
    cogs_zar,
    gross_margin_zar,
    promotion_applied,
    payment_method,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_shop_sales') }}
where not _dq_is_valid
