-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'dim_country' as _source_table,
    country_code,
    country_name,
    market_group,
    capital_latitude,
    capital_longitude,
    country_key,
    currency_code,
    is_home_market,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_dim_country') }}
where not _dq_is_valid
