-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_cashflow' as _source_table,
    cashflow_id,
    period_date,
    date_key,
    legal_entity_code,
    cashflow_category,
    inflow_zar,
    outflow_zar,
    net_cashflow_zar,
    closing_balance_zar,
    currency_code,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_cashflow') }}
where not _dq_is_valid
