-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_grid_import_export' as _source_table,
    grid_flow_id,
    reading_ts,
    date_key,
    site_id,
    import_kwh,
    export_kwh,
    net_kwh,
    self_consumption_pct,
    load_shedding_stage,
    backup_generator_running,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_grid_import_export') }}
where not _dq_is_valid
