-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'dim_customer' as _source_table,
    customer_id,
    customer_key,
    customer_name,
    sector,
    segment,
    country_code,
    credit_band,
    credit_limit_zar,
    payment_terms_days,
    onboarded_date,
    is_active,
    revenue_index,
    effective_from_date,
    effective_to_date,
    is_current,
    scd_version,
    record_source,
    dw_load_ts,
    dw_hash_diff,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_dim_customer') }}
where not _dq_is_valid
