-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_environmental_events' as _source_table,
    environmental_event_id,
    event_ts,
    date_key,
    site_id,
    terminal_id,
    event_type,
    volume_released_litres,
    contained_flag,
    soil_affected_m2,
    remediation_cost_zar,
    regulator_notified,
    days_to_remediate,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_environmental_events') }}
where not _dq_is_valid
