-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_bunker_deliveries' as _source_table,
    bunker_delivery_id,
    delivery_ts,
    date_key,
    port_code,
    vessel_imo,
    delivery_mode,
    delivered_litres,
    pumping_rate_lpm,
    delivery_hours,
    bunker_delivery_note_signed,
    quantity_dispute_raised,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_bunker_deliveries') }}
where not _dq_is_valid
