-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'dim_campaign' as _source_table,
    campaign_id,
    campaign_key,
    campaign_name,
    channel,
    start_date,
    end_date,
    budget_zar,
    target_segment,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_dim_campaign') }}
where not _dq_is_valid
