-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_ev_charging_sessions' as _source_table,
    ev_session_id,
    session_start_ts,
    session_end_ts,
    date_key,
    time_key,
    ev_charger_id,
    site_id,
    connector_type,
    rated_power_kw,
    duration_minutes,
    energy_kwh,
    average_power_kw,
    tariff_zar_per_kwh,
    revenue_zar,
    grid_cost_zar,
    gross_margin_zar,
    start_soc_pct,
    end_soc_pct,
    payment_method,
    session_ended_by,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_ev_charging_sessions') }}
where not _dq_is_valid
