-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_marine_inventory_snapshot' as _source_table,
    marine_snapshot_id,
    snapshot_ts,
    date_key,
    port_code,
    product_id,
    capacity_litres,
    stock_on_hand_litres,
    days_of_cover,
    viscosity_cst,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_marine_inventory_snapshot') }}
where not _dq_is_valid
