-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_aircraft_uplifts' as _source_table,
    uplift_id,
    uplift_ts,
    date_key,
    airport_code,
    airline_code,
    flight_number,
    aircraft_registration,
    uplift_litres,
    uplift_duration_minutes,
    density_kg_per_litre,
    meter_start,
    quality_check_passed,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_aircraft_uplifts') }}
where not _dq_is_valid
