-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_site_daily_operations' as _source_table,
    site_day_id,
    business_date,
    date_key,
    site_id,
    fuel_litres,
    fuel_revenue_zar,
    shop_revenue_zar,
    customer_count,
    average_basket_zar,
    staff_hours,
    energy_kwh,
    downtime_minutes,
    weather_condition,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_site_daily_operations') }}
where not _dq_is_valid
