-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_lpg_bulk_deliveries' as _source_table,
    lpg_delivery_id,
    delivery_ts,
    date_key,
    customer_id,
    depot_id,
    vehicle_id,
    delivered_kg,
    tank_fill_pct_before,
    tank_fill_pct_after,
    revenue_zar,
    is_emergency_delivery,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_lpg_bulk_deliveries') }}
where not _dq_is_valid
