-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'bridge_product_hierarchy') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('product_id') }} as product_id,
        {{ fix_mojibake('level_1_category') }} as level_1_category,
        {{ fix_mojibake('level_2_subcategory') }} as level_2_subcategory,
        {{ fix_mojibake('level_3_product') }} as level_3_product,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (product_id is not null) as _dq_product_id_present,
        (coalesce(_dq_product_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'bridge_product_hierarchy' as _source_table,
    product_id,
    level_1_category,
    level_2_subcategory,
    level_3_product,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
