-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_pump') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('pump_id') }} as pump_id,
        {{ clean_integer('pump_key') }} as pump_key,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_integer('pump_number') }} as pump_number,
        {{ clean_integer('nozzle_count') }} as nozzle_count,
        {{ clean_measure('flow_rate_lpm') }} as flow_rate_lpm,
        try_cast(supports_high_flow_diesel as boolean) as supports_high_flow_diesel
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (pump_id is not null) as _dq_pump_id_present,
        (site_id is not null) as _dq_site_id_present,
        (coalesce(_dq_pump_id_present, false) and coalesce(_dq_site_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_pump_id_present, false) then 'pump_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end
        ) as _dq_failed_rules
    from cleansed
)

-- Rows that failed the contract. Kept, not dropped: a
-- silently discarded row becomes an unexplainable variance
-- months later, and there is no way back from it.
select
    'dim_pump' as _source_table,
    pump_id,
    pump_key,
    site_id,
    pump_number,
    nozzle_count,
    flow_rate_lpm,
    supports_high_flow_diesel,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
