-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_replenishment_orders') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('replenishment_id') }} as replenishment_id,
        {{ clean_timestamp('raised_ts') }} as raised_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('site_id') }} as site_id,
        {{ clean_code('terminal_id') }} as terminal_id,
        {{ clean_code('product_id') }} as product_id,
        {{ clean_measure('requested_litres') }} as requested_litres,
        {{ fix_mojibake('trigger_type') }} as trigger_type,
        {{ clean_measure('days_of_cover_at_raise') }} as days_of_cover_at_raise,
        {{ clean_timestamp('promised_delivery_ts') }} as promised_delivery_ts,
        try_cast(fulfilled_flag as boolean) as fulfilled_flag,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (replenishment_id is not null) as _dq_replenishment_id_present,
        (site_id is not null) as _dq_site_id_present,
        (product_id is not null) as _dq_product_id_present,
        (raised_ts is not null) as _dq_event_timestamp_valid,
        (coalesce(_dq_replenishment_id_present, false) and coalesce(_dq_site_id_present, false) and coalesce(_dq_product_id_present, false) and coalesce(_dq_event_timestamp_valid, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_replenishment_id_present, false) then 'replenishment_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'fact_replenishment_orders' as _source_table,
    replenishment_id,
    raised_ts,
    date_key,
    site_id,
    terminal_id,
    product_id,
    requested_litres,
    trigger_type,
    days_of_cover_at_raise,
    promised_delivery_ts,
    fulfilled_flag,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
