-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_loyalty_transactions' as _source_table,
    loyalty_transaction_id,
    transaction_ts,
    date_key,
    loyalty_member_id,
    tier,
    site_id,
    transaction_type,
    qualifying_spend_zar,
    points_delta,
    points_value_zar,
    earn_category,
    channel,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_loyalty_transactions') }}
where not _dq_is_valid
