-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_lpg_cylinder_type') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('cylinder_type_code') }} as cylinder_type_code,
        {{ clean_integer('lpg_cylinder_type_key') }} as lpg_cylinder_type_key,
        {{ clean_measure('nominal_kg') }} as nominal_kg,
        {{ clean_measure('deposit_zar') }} as deposit_zar,
        try_cast(is_returnable as boolean) as is_returnable,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (deposit_zar >= 0) as _dq_deposit_zar_non_negative,
        (coalesce(_dq_deposit_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_deposit_zar_non_negative, false) then 'deposit_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'dim_lpg_cylinder_type' as _source_table,
    cylinder_type_code,
    lpg_cylinder_type_key,
    nominal_kg,
    deposit_zar,
    is_returnable,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
