-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_delivery_events' as _source_table,
    delivery_event_id,
    event_ts,
    date_key,
    delivery_id,
    event_type,
    vehicle_id,
    latitude,
    longitude,
    speed_kph,
    odometer_km,
    geofence_name,
    is_exception,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_delivery_events') }}
where not _dq_is_valid
