-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_budget_vs_actual') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('bva_id') }} as bva_id,
        {{ clean_timestamp('period_date') }} as period_date,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('gl_account_code') }} as gl_account_code,
        {{ clean_code('cost_centre_code') }} as cost_centre_code,
        {{ clean_code('business_unit_code') }} as business_unit_code,
        {{ clean_measure('budget_amount_zar') }} as budget_amount_zar,
        {{ clean_measure('actual_amount_zar') }} as actual_amount_zar,
        {{ clean_measure('variance_zar') }} as variance_zar,
        {{ clean_measure('variance_pct') }} as variance_pct,
        try_cast(is_favourable as boolean) as is_favourable,
        try_cast(variance_explanation_required as boolean) as variance_explanation_required,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (bva_id is not null) as _dq_bva_id_present,
        (period_date is not null) as _dq_event_timestamp_valid,
        (budget_amount_zar >= 0) as _dq_budget_amount_zar_non_negative,
        (actual_amount_zar >= 0) as _dq_actual_amount_zar_non_negative,
        (variance_zar >= 0) as _dq_variance_zar_non_negative,
        (coalesce(_dq_bva_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_budget_amount_zar_non_negative, false) and coalesce(_dq_actual_amount_zar_non_negative, false) and coalesce(_dq_variance_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_bva_id_present, false) then 'bva_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_budget_amount_zar_non_negative, false) then 'budget_amount_zar_non_negative' end,
            case when not coalesce(_dq_actual_amount_zar_non_negative, false) then 'actual_amount_zar_non_negative' end,
            case when not coalesce(_dq_variance_zar_non_negative, false) then 'variance_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'fact_budget_vs_actual' as _source_table,
    bva_id,
    period_date,
    date_key,
    gl_account_code,
    cost_centre_code,
    business_unit_code,
    budget_amount_zar,
    actual_amount_zar,
    variance_zar,
    variance_pct,
    is_favourable,
    variance_explanation_required,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
