-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'dim_city' as _source_table,
    city_name,
    province_name,
    country_code,
    latitude,
    longitude,
    urban_class,
    on_national_route,
    anchor_weight,
    city_key,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_dim_city') }}
where not _dq_is_valid
