-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'dim_digital_user' as _source_table,
    digital_user_id,
    digital_user_key,
    registered_date,
    primary_device_type,
    app_version,
    push_enabled,
    linked_loyalty_member_id,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_dim_digital_user') }}
where not _dq_is_valid
