-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'dim_site' as _source_table,
    site_id,
    site_name,
    country_code,
    province,
    city,
    urban_class,
    latitude,
    longitude,
    site_type,
    ownership_model,
    on_national_route,
    site_key,
    forecourt_lanes,
    has_convenience,
    has_qsr,
    has_car_wash,
    has_ev_charging,
    has_solar,
    has_lpg,
    is_24_hour,
    opened_date,
    site_status,
    demand_index,
    effective_from_date,
    effective_to_date,
    is_current,
    scd_version,
    record_source,
    dw_load_ts,
    dw_hash_diff,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_dim_site') }}
where not _dq_is_valid
