-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_lubricant_inventory_snapshot' as _source_table,
    lubricant_snapshot_id,
    snapshot_ts,
    date_key,
    warehouse_id,
    product_id,
    stock_on_hand_litres,
    stock_value_zar,
    pallet_positions_used,
    days_of_cover,
    is_slow_moving,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_lubricant_inventory_snapshot') }}
where not _dq_is_valid
