-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_facts', 'fact_campaign_responses') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('campaign_response_id') }} as campaign_response_id,
        {{ clean_timestamp('response_ts') }} as response_ts,
        {{ clean_integer('date_key') }} as date_key,
        {{ clean_code('campaign_id') }} as campaign_id,
        {{ clean_code('digital_user_id') }} as digital_user_id,
        {{ fix_mojibake('channel') }} as channel,
        try_cast(was_delivered as boolean) as was_delivered,
        try_cast(was_opened as boolean) as was_opened,
        try_cast(was_clicked as boolean) as was_clicked,
        try_cast(was_redeemed as boolean) as was_redeemed,
        {{ clean_measure('incremental_spend_zar') }} as incremental_spend_zar,
        {{ fix_mojibake('attribution_model') }} as attribution_model,
        {{ clean_code('source_system_code') }} as source_system_code,
        {{ clean_timestamp('ingested_at') }} as ingested_at,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (campaign_response_id is not null) as _dq_campaign_response_id_present,
        (response_ts is not null) as _dq_event_timestamp_valid,
        (incremental_spend_zar >= 0) as _dq_incremental_spend_zar_non_negative,
        (coalesce(_dq_campaign_response_id_present, false) and coalesce(_dq_event_timestamp_valid, false) and coalesce(_dq_incremental_spend_zar_non_negative, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_campaign_response_id_present, false) then 'campaign_response_id_present' end,
            case when not coalesce(_dq_event_timestamp_valid, false) then 'event_timestamp_valid' end,
            case when not coalesce(_dq_incremental_spend_zar_non_negative, false) then 'incremental_spend_zar_non_negative' end
        ) as _dq_failed_rules
    from cleansed
),

-- Rows that failed the contract. Kept, not dropped.
select
    'fact_campaign_responses' as _source_table,
    campaign_response_id,
    response_ts,
    date_key,
    campaign_id,
    digital_user_id,
    channel,
    was_delivered,
    was_opened,
    was_clicked,
    was_redeemed,
    incremental_spend_zar,
    attribution_model,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    {{ cleansing_layer_columns() }}
from assessed
where not _dq_is_valid
