-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Rows that failed the contract. Kept, not dropped: a silently
-- discarded row becomes an unexplainable variance months later,
-- and there is no way back from it.

select
    'fact_promotions' as _source_table,
    promotion_fact_id,
    measurement_date,
    date_key,
    site_id,
    promotion_id,
    baseline_units,
    promoted_units,
    uplift_pct,
    discount_cost_zar,
    incremental_margin_zar,
    source_system_code,
    ingested_at,
    _dq_failed_rules,
    _cleansed_at
from {{ ref('cln_fact_promotions') }}
where not _dq_is_valid
