-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_device') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('device_type_name') }} as device_type_name,
        {{ clean_integer('device_key') }} as device_key,
        try_cast(is_mobile as boolean) as is_mobile,
        1 as _dummy
    from source
),

assessed as (
    select *, true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
),

select
    device_type_name,
    device_key,
    is_mobile,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
