-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

select
    data_source_code,
    data_source_name,
    ingestion_pattern,
    owning_domain,
    data_source_key,
    sla_minutes,
    is_pii_bearing,
    _cleansed_at
from {{ ref('cln_dim_data_source') }}
where _dq_is_valid
