-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'bridge_site_hierarchy') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('site_id') }} as site_id,
        {{ clean_code('country_code') }} as country_code,
        {{ fix_mojibake('province') }} as province,
        {{ fix_mojibake('city') }} as city,
        {{ fix_mojibake('region_level') }} as region_level,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (site_id is not null) as _dq_site_id_present,
        (coalesce(_dq_site_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so
-- the same business key can arrive more than once. Keep the
-- most recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by site_id order by site_id desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    site_id,
    country_code,
    province,
    city,
    region_level,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
