-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

select
    order_status_name,
    order_status_key,
    is_open,
    _cleansed_at
from {{ ref('cln_dim_order_status') }}
where _dq_is_valid
