-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_pump') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by pump_id order by pump_id desc) as _row_rank
    from source
),

renamed as (
    select
        pump_id,
        pump_key,
        site_id,
        pump_number,
        nozzle_count,
        flow_rate_lpm,
        supports_high_flow_diesel,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
