-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_delivery_status') }}
),

renamed as (
    select
        delivery_status_name,
        delivery_status_key,
        is_terminal_state,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from source
)

select * from renamed
