-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_scenario') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('scenario_name') }} as scenario_name,
        {{ clean_integer('scenario_key') }} as scenario_key,
        try_cast(is_actual as boolean) as is_actual
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    scenario_name,
    scenario_key,
    is_actual,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
