-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_country') }}
),

renamed as (
    select
        country_code,
        country_name,
        market_group,
        capital_latitude,
        capital_longitude,
        country_key,
        currency_code,
        is_home_market,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from source
)

select * from renamed
