-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_gl_account') }}
),

renamed as (
    select
        gl_account_code,
        gl_account_name,
        account_class,
        gl_account_key,
        normal_balance,
        is_pnl,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from source
)

select * from renamed
