-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_loyalty_member') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by loyalty_member_id order by loyalty_member_id desc) as _row_rank
    from source
),

renamed as (
    select
        loyalty_member_id,
        loyalty_member_key,
        tier,
        joined_date,
        home_site_id,
        opt_in_marketing,
        is_active,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
