-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_promotion') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('promotion_id') }} as promotion_id,
        {{ clean_integer('promotion_key') }} as promotion_key,
        {{ fix_mojibake('promotion_name') }} as promotion_name,
        {{ fix_mojibake('mechanic') }} as mechanic,
        {{ clean_timestamp('start_date') }} as start_date,
        {{ clean_timestamp('end_date') }} as end_date,
        {{ clean_measure('discount_pct') }} as discount_pct
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (promotion_id is not null) as _dq_promotion_id_present,
        (coalesce(_dq_promotion_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_promotion_id_present, false) then 'promotion_id_present' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so the
-- same business key can arrive more than once. Keep the most
-- recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by promotion_id order by promotion_id desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    promotion_id,
    promotion_key,
    promotion_name,
    mechanic,
    start_date,
    end_date,
    discount_pct,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
