-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

select
    gl_account_code,
    gl_account_name,
    account_class,
    gl_account_key,
    normal_balance,
    is_pnl,
    _cleansed_at
from {{ ref('cln_dim_gl_account') }}
where _dq_is_valid
