-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_cost_centre') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('cost_centre_name') }} as cost_centre_name,
        {{ clean_integer('cost_centre_key') }} as cost_centre_key,
        {{ clean_code('cost_centre_code') }} as cost_centre_code,
        {{ fix_mojibake('function') }} as function
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    cost_centre_name,
    cost_centre_key,
    cost_centre_code,
    function,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
