-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_site_type') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('site_type_name') }} as site_type_name,
        {{ clean_integer('site_type_key') }} as site_type_key,
        try_cast(is_retail as boolean) as is_retail
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    site_type_name,
    site_type_key,
    is_retail,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
