-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

select
    legal_entity_code,
    legal_entity_key,
    legal_entity_name,
    country_code,
    functional_currency,
    consolidation_method,
    _cleansed_at
from {{ ref('cln_dim_legal_entity') }}
where _dq_is_valid
