-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_site') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by site_id order by site_id desc) as _row_rank
    from source
),

renamed as (
    select
        site_id,
        site_name,
        country_code,
        province,
        city,
        urban_class,
        latitude,
        longitude,
        site_type,
        ownership_model,
        on_national_route,
        site_key,
        forecourt_lanes,
        has_convenience,
        has_qsr,
        has_car_wash,
        has_ev_charging,
        has_solar,
        has_lpg,
        is_24_hour,
        opened_date,
        site_status,
        demand_index,
        effective_from_date,
        effective_to_date,
        is_current,
        scd_version,
        record_source,
        dw_load_ts,
        dw_hash_diff,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
