-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_promotion') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by promotion_id order by promotion_id desc) as _row_rank
    from source
),

renamed as (
    select
        promotion_id,
        promotion_key,
        promotion_name,
        mechanic,
        start_date,
        end_date,
        discount_pct,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
