-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by equipment_id order by equipment_id desc nulls last) as _row_rank
    from {{ ref('cln_dim_equipment') }}
    where _dq_is_valid
)

select
    equipment_id,
    equipment_key,
    parent_asset_id,
    equipment_name,
    serial_number,
    _cleansed_at
from deduplicated
where _row_rank = 1
