-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_vehicle') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by vehicle_id order by vehicle_id desc) as _row_rank
    from source
),

renamed as (
    select
        vehicle_id,
        vehicle_key,
        carrier_id,
        vehicle_type,
        capacity_litres,
        compartments,
        model_year,
        telematics_enabled,
        is_active,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
