-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'bridge_site_product') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by site_id order by site_id desc) as _row_rank
    from source
),

renamed as (
    select
        site_id,
        product_id,
        is_primary_grade,
        listed_from_date,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
