-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'bridge_supplier_product') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('supplier_id') }} as supplier_id,
        {{ clean_code('product_id') }} as product_id,
        try_cast(is_approved as boolean) as is_approved
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (supplier_id is not null) as _dq_supplier_id_present,
        (product_id is not null) as _dq_product_id_present,
        (coalesce(_dq_supplier_id_present, false) and coalesce(_dq_product_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_supplier_id_present, false) then 'supplier_id_present' end,
            case when not coalesce(_dq_product_id_present, false) then 'product_id_present' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so the
-- same business key can arrive more than once. Keep the most
-- recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by supplier_id order by supplier_id desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    supplier_id,
    product_id,
    is_approved,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
