-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

select
    budget_version_code,
    budget_version_key,
    fiscal_year,
    version_status,
    _cleansed_at
from {{ ref('cln_dim_budget_version') }}
where _dq_is_valid
