-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_supplier') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('supplier_id') }} as supplier_id,
        {{ clean_integer('supplier_key') }} as supplier_key,
        {{ fix_mojibake('supplier_name') }} as supplier_name,
        {{ fix_mojibake('supplier_type') }} as supplier_type,
        {{ clean_code('country_code') }} as country_code,
        {{ fix_mojibake('risk_rating') }} as risk_rating,
        {{ clean_measure('esg_score') }} as esg_score,
        try_cast(preferred_supplier as boolean) as preferred_supplier,
        {{ clean_timestamp('contract_start_date') }} as contract_start_date,
        {{ clean_timestamp('effective_from_date') }} as effective_from_date,
        {{ clean_timestamp('effective_to_date') }} as effective_to_date,
        try_cast(is_current as boolean) as is_current,
        {{ clean_integer('scd_version') }} as scd_version,
        {{ fix_mojibake('record_source') }} as record_source,
        {{ clean_timestamp('dw_load_ts') }} as dw_load_ts,
        {{ fix_mojibake('dw_hash_diff') }} as dw_hash_diff,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (supplier_id is not null) as _dq_supplier_id_present,
        (coalesce(_dq_supplier_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_supplier_id_present, false) then 'supplier_id_present' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so
-- the same business key can arrive more than once. Keep the
-- most recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by supplier_id order by supplier_id desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    supplier_id,
    supplier_key,
    supplier_name,
    supplier_type,
    country_code,
    risk_rating,
    esg_score,
    preferred_supplier,
    contract_start_date,
    effective_from_date,
    effective_to_date,
    is_current,
    scd_version,
    record_source,
    dw_load_ts,
    dw_hash_diff,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
