-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_time') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_integer('time_key') }} as time_key,
        {{ fix_mojibake('time_of_day') }} as time_of_day,
        {{ clean_integer('hour_24') }} as hour_24,
        {{ clean_integer('minute_of_hour') }} as minute_of_hour,
        {{ clean_integer('minute_of_day') }} as minute_of_day,
        {{ fix_mojibake('day_part') }} as day_part,
        try_cast(is_peak_hour as boolean) as is_peak_hour
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    time_key,
    time_of_day,
    hour_24,
    minute_of_hour,
    minute_of_day,
    day_part,
    is_peak_hour,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
