-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_terminal') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by terminal_id order by terminal_id desc) as _row_rank
    from source
),

renamed as (
    select
        terminal_id,
        terminal_name,
        country_code,
        province,
        city,
        terminal_key,
        capacity_litres,
        tank_count,
        pipeline_connected,
        rail_connected,
        port_connected,
        road_gantry_bays,
        commissioned_year,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
