-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

select
    energy_source_name,
    energy_source_key,
    is_renewable,
    kg_co2_per_kwh,
    _cleansed_at
from {{ ref('cln_dim_energy_source') }}
where _dq_is_valid
