-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_port') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('port_code') }} as port_code,
        {{ fix_mojibake('port_name') }} as port_name,
        {{ fix_mojibake('province') }} as province,
        {{ fix_mojibake('city') }} as city,
        {{ clean_integer('port_key') }} as port_key,
        {{ clean_code('country_code') }} as country_code,
        try_cast(has_bunkering as boolean) as has_bunkering
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    port_code,
    port_name,
    province,
    city,
    port_key,
    country_code,
    has_bunkering,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
