-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'bridge_route_site') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by route_id order by route_id desc) as _row_rank
    from source
),

renamed as (
    select
        route_id,
        site_id,
        drop_sequence,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
