-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_profit_centre') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('profit_centre_code') }} as profit_centre_code,
        {{ clean_integer('profit_centre_key') }} as profit_centre_key,
        {{ fix_mojibake('profit_centre_name') }} as profit_centre_name,
        {{ clean_code('business_unit_code') }} as business_unit_code
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    profit_centre_code,
    profit_centre_key,
    profit_centre_name,
    business_unit_code,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
