-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_airport') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('iata_code') }} as iata_code,
        {{ fix_mojibake('airport_name') }} as airport_name,
        {{ fix_mojibake('province') }} as province,
        {{ fix_mojibake('city') }} as city,
        {{ clean_integer('airport_key') }} as airport_key,
        {{ clean_code('country_code') }} as country_code,
        try_cast(has_fuel_farm as boolean) as has_fuel_farm,
        {{ fix_mojibake('annual_uplift_band') }} as annual_uplift_band
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    iata_code,
    airport_name,
    province,
    city,
    airport_key,
    country_code,
    has_fuel_farm,
    annual_uplift_band,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
