-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_depot') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('depot_id') }} as depot_id,
        {{ clean_integer('depot_key') }} as depot_key,
        {{ fix_mojibake('depot_name') }} as depot_name,
        {{ clean_code('parent_terminal_id') }} as parent_terminal_id,
        {{ clean_code('country_code') }} as country_code,
        {{ clean_integer('storage_capacity_litres') }} as storage_capacity_litres,
        try_cast(serves_lpg as boolean) as serves_lpg,
        try_cast(serves_lubricants as boolean) as serves_lubricants,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (depot_id is not null) as _dq_depot_id_present,
        (coalesce(_dq_depot_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_depot_id_present, false) then 'depot_id_present' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so
-- the same business key can arrive more than once. Keep the
-- most recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by depot_id order by depot_id desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    depot_id,
    depot_key,
    depot_name,
    parent_terminal_id,
    country_code,
    storage_capacity_litres,
    serves_lpg,
    serves_lubricants,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
