-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_reason_code') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('reason_code_name') }} as reason_code_name,
        {{ clean_integer('reason_code_key') }} as reason_code_key,
        {{ fix_mojibake('reason_category') }} as reason_category
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    reason_code_name,
    reason_code_key,
    reason_category,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
