-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_contract_type') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('contract_type_name') }} as contract_type_name,
        {{ clean_integer('contract_type_key') }} as contract_type_key,
        try_cast(requires_volume_commitment as boolean) as requires_volume_commitment
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    contract_type_name,
    contract_type_key,
    requires_volume_commitment,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
