-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by loyalty_member_id order by loyalty_member_id desc nulls last) as _row_rank
    from {{ ref('cln_dim_loyalty_member') }}
    where _dq_is_valid
)

select
    loyalty_member_id,
    loyalty_member_key,
    tier,
    joined_date,
    home_site_id,
    opt_in_marketing,
    is_active,
    _cleansed_at
from deduplicated
where _row_rank = 1
