-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_date') }}
),

renamed as (
    select
        date_key,
        full_date,
        day_of_month,
        day_of_week,
        day_name,
        day_of_year,
        week_of_year,
        month_number,
        month_name,
        quarter_number,
        quarter_name,
        calendar_year,
        fiscal_year,
        fiscal_quarter,
        fiscal_period,
        is_weekend,
        is_public_holiday_za,
        is_trading_day,
        season_southern,
        school_holiday_za,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from source
)

select * from renamed
