-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_data_source') }}
),

renamed as (
    select
        data_source_code,
        data_source_name,
        ingestion_pattern,
        owning_domain,
        data_source_key,
        sla_minutes,
        is_pii_bearing,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from source
)

select * from renamed
