-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_digital_user') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('digital_user_id') }} as digital_user_id,
        {{ clean_integer('digital_user_key') }} as digital_user_key,
        {{ clean_timestamp('registered_date') }} as registered_date,
        {{ fix_mojibake('primary_device_type') }} as primary_device_type,
        {{ fix_mojibake('app_version') }} as app_version,
        try_cast(push_enabled as boolean) as push_enabled,
        {{ clean_code('linked_loyalty_member_id') }} as linked_loyalty_member_id
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (digital_user_id is not null) as _dq_digital_user_id_present,
        (coalesce(_dq_digital_user_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_digital_user_id_present, false) then 'digital_user_id_present' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so the
-- same business key can arrive more than once. Keep the most
-- recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by digital_user_id order by digital_user_id desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    digital_user_id,
    digital_user_key,
    registered_date,
    primary_device_type,
    app_version,
    push_enabled,
    linked_loyalty_member_id,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
