-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_asset') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by asset_id order by asset_id desc) as _row_rank
    from source
),

renamed as (
    select
        asset_id,
        asset_key,
        site_id,
        asset_type,
        manufacturer,
        model_code,
        install_date,
        replacement_value_zar,
        criticality,
        age_years,
        failure_propensity,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
