-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_failure_mode') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('failure_mode_name') }} as failure_mode_name,
        {{ clean_integer('failure_mode_key') }} as failure_mode_key,
        {{ clean_measure('typical_repair_hours') }} as typical_repair_hours
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    failure_mode_name,
    failure_mode_key,
    typical_repair_hours,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
