-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_energy_source') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('energy_source_name') }} as energy_source_name,
        {{ clean_integer('energy_source_key') }} as energy_source_key,
        try_cast(is_renewable as boolean) as is_renewable,
        {{ clean_measure('kg_co2_per_kwh') }} as kg_co2_per_kwh
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    energy_source_name,
    energy_source_key,
    is_renewable,
    kg_co2_per_kwh,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
