-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_digital_user') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by digital_user_id order by digital_user_id desc) as _row_rank
    from source
),

renamed as (
    select
        digital_user_id,
        digital_user_key,
        registered_date,
        primary_device_type,
        app_version,
        push_enabled,
        linked_loyalty_member_id,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
