-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

select
    date_key,
    full_date,
    day_of_month,
    day_of_week,
    day_name,
    day_of_year,
    week_of_year,
    month_number,
    month_name,
    quarter_number,
    quarter_name,
    calendar_year,
    fiscal_year,
    fiscal_quarter,
    fiscal_period,
    is_weekend,
    is_public_holiday_za,
    is_trading_day,
    season_southern,
    school_holiday_za,
    _cleansed_at
from {{ ref('cln_dim_date') }}
where _dq_is_valid
