-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'bridge_customer_contract') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by customer_id order by customer_id desc) as _row_rank
    from source
),

renamed as (
    select
        customer_id,
        contract_id,
        is_primary_contract,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
