-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by terminal_id order by terminal_id desc nulls last) as _row_rank
    from {{ ref('cln_dim_terminal') }}
    where _dq_is_valid
)

select
    terminal_id,
    terminal_name,
    country_code,
    province,
    city,
    terminal_key,
    capacity_litres,
    tank_count,
    pipeline_connected,
    rail_connected,
    port_connected,
    road_gantry_bays,
    commissioned_year,
    _cleansed_at
from deduplicated
where _row_rank = 1
