-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by product_id order by product_id desc nulls last) as _row_rank
    from {{ ref('cln_bridge_product_hierarchy') }}
    where _dq_is_valid
)

select
    product_id,
    level_1_category,
    level_2_subcategory,
    level_3_product,
    _cleansed_at
from deduplicated
where _row_rank = 1
