-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by tank_id order by tank_id desc nulls last) as _row_rank
    from {{ ref('cln_dim_tank') }}
    where _dq_is_valid
)

select
    tank_id,
    tank_key,
    site_id,
    product_id,
    capacity_litres,
    tank_material,
    install_year,
    has_leak_detection,
    telemetry_enabled,
    _cleansed_at
from deduplicated
where _row_rank = 1
