-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'bridge_security_user_scope') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('user_principal') }} as user_principal,
        {{ fix_mojibake('scope_type') }} as scope_type,
        {{ fix_mojibake('scope_value') }} as scope_value
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    user_principal,
    scope_type,
    scope_value,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
