-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_city') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('city_name') }} as city_name,
        {{ fix_mojibake('province_name') }} as province_name,
        {{ clean_code('country_code') }} as country_code,
        {{ clean_measure('latitude') }} as latitude,
        {{ clean_measure('longitude') }} as longitude,
        {{ fix_mojibake('urban_class') }} as urban_class,
        try_cast(on_national_route as boolean) as on_national_route,
        {{ clean_integer('anchor_weight') }} as anchor_weight,
        {{ clean_integer('city_key') }} as city_key
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    city_name,
    province_name,
    country_code,
    latitude,
    longitude,
    urban_class,
    on_national_route,
    anchor_weight,
    city_key,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
