-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_contract') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by contract_id order by contract_id desc) as _row_rank
    from source
),

renamed as (
    select
        contract_id,
        contract_key,
        customer_id,
        contract_type,
        start_date,
        end_date,
        committed_volume_litres,
        price_mechanism,
        discount_cents_per_litre,
        effective_from_date,
        effective_to_date,
        is_current,
        scd_version,
        record_source,
        dw_load_ts,
        dw_hash_diff,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
