-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'bridge_customer_hierarchy') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('parent_customer_id') }} as parent_customer_id,
        {{ clean_code('child_customer_id') }} as child_customer_id,
        {{ clean_integer('hierarchy_level') }} as hierarchy_level,
        {{ clean_measure('ownership_pct') }} as ownership_pct,
        1 as _dummy
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (parent_customer_id is not null) as _dq_parent_customer_id_present,
        (coalesce(_dq_parent_customer_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_parent_customer_id_present, false) then 'parent_customer_id_present' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so
-- the same business key can arrive more than once. Keep the
-- most recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by parent_customer_id order by parent_customer_id desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    parent_customer_id,
    child_customer_id,
    hierarchy_level,
    ownership_pct,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
