-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'bridge_customer_site') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ clean_code('customer_id') }} as customer_id,
        {{ clean_code('site_id') }} as site_id,
        try_cast(delivery_point_flag as boolean) as delivery_point_flag
    from source
),

-- Stage 2: assess. One boolean per rule, so a quarantined
-- row records exactly why it was rejected.
assessed as (
    select
        *,
        (customer_id is not null) as _dq_customer_id_present,
        (site_id is not null) as _dq_site_id_present,
        (coalesce(_dq_customer_id_present, false) and coalesce(_dq_site_id_present, false)) as _dq_is_valid,
        concat_ws(',',
            case when not coalesce(_dq_customer_id_present, false) then 'customer_id_present' end,
            case when not coalesce(_dq_site_id_present, false) then 'site_id_present' end
        ) as _dq_failed_rules
    from cleansed
),

-- Stage 3: deduplicate. Source systems replay batches, so the
-- same business key can arrive more than once. Keep the most
-- recently ingested version.
deduplicated as (
    select
        *,
        row_number() over (partition by customer_id order by customer_id desc nulls last) as _row_rank
    from assessed
    where _dq_is_valid
)

select
    customer_id,
    site_id,
    delivery_point_flag,
    {{ cleansing_layer_columns() }}
from deduplicated
where _row_rank = 1
