-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by digital_user_id order by digital_user_id desc nulls last) as _row_rank
    from {{ ref('cln_dim_digital_user') }}
    where _dq_is_valid
)

select
    digital_user_id,
    digital_user_key,
    registered_date,
    primary_device_type,
    app_version,
    push_enabled,
    linked_loyalty_member_id,
    _cleansed_at
from deduplicated
where _row_rank = 1
