-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_incident_severity') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('severity_name') }} as severity_name,
        {{ clean_integer('incident_severity_key') }} as incident_severity_key,
        {{ clean_integer('severity_rank') }} as severity_rank,
        try_cast(is_reportable as boolean) as is_reportable
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    severity_name,
    incident_severity_key,
    severity_rank,
    is_reportable,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
