-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_product_category') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('category_name') }} as category_name,
        {{ clean_integer('category_key') }} as category_key,
        try_cast(is_regulated_price as boolean) as is_regulated_price,
        {{ fix_mojibake('margin_profile') }} as margin_profile
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    category_name,
    category_key,
    is_regulated_price,
    margin_profile,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
