-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_vessel') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('vessel_imo') }} as vessel_imo,
        {{ clean_integer('vessel_key') }} as vessel_key,
        {{ fix_mojibake('vessel_name') }} as vessel_name,
        {{ fix_mojibake('vessel_class') }} as vessel_class,
        {{ clean_integer('deadweight_tonnes') }} as deadweight_tonnes,
        {{ clean_code('flag_country_code') }} as flag_country_code
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    vessel_imo,
    vessel_key,
    vessel_name,
    vessel_class,
    deadweight_tonnes,
    flag_country_code,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
