-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by route_id order by route_id desc nulls last) as _row_rank
    from {{ ref('cln_dim_route') }}
    where _dq_is_valid
)

select
    route_id,
    route_key,
    origin_terminal_id,
    route_name,
    planned_distance_km,
    route_class,
    drop_count,
    planned_duration_hours,
    _cleansed_at
from deduplicated
where _row_rank = 1
