-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_employee') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by employee_id order by employee_id desc) as _row_rank
    from source
),

renamed as (
    select
        employee_id,
        employee_key,
        employee_name,
        role,
        home_site_id,
        business_unit_code,
        employment_type,
        hire_date,
        is_active,
        effective_from_date,
        effective_to_date,
        is_current,
        scd_version,
        record_source,
        dw_load_ts,
        dw_hash_diff,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
