-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

-- Stage 2 of 2: the clean, conformed rows the marts consume.

-- Source systems replay batches, so the same business key can
-- arrive more than once. Keep the most recently ingested version.
with deduplicated as (
    select
        *,
        row_number() over (partition by promotion_id order by promotion_id desc nulls last) as _row_rank
    from {{ ref('cln_dim_promotion') }}
    where _dq_is_valid
)

select
    promotion_id,
    promotion_key,
    promotion_name,
    mechanic,
    start_date,
    end_date,
    discount_pct,
    _cleansed_at
from deduplicated
where _row_rank = 1
