-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_vessel') }}
),

renamed as (
    select
        vessel_imo,
        vessel_key,
        vessel_name,
        vessel_class,
        deadweight_tonnes,
        flag_country_code,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from source
)

select * from renamed
