-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_shift') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('shift_name') }} as shift_name,
        {{ clean_integer('shift_key') }} as shift_key,
        {{ clean_integer('start_hour') }} as start_hour,
        {{ clean_integer('end_hour') }} as end_hour,
        1 as _dummy
    from source
),

assessed as (
    select *, true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
),

select
    shift_name,
    shift_key,
    start_hour,
    end_hour,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
