-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model or defect profile.

with source as (
    select * from {{ source('lake_dimensions', 'dim_channel') }}
),

-- Stage 1: repair. Trim, case-fold, parse numbers out of
-- locale-formatted text, range-check timestamps.
cleansed as (
    select
        {{ fix_mojibake('channel_name') }} as channel_name,
        {{ clean_integer('channel_key') }} as channel_key,
        try_cast(is_digital as boolean) as is_digital
    from source
),

assessed as (
    select *,
           true as _dq_is_valid,
           cast('' as varchar) as _dq_failed_rules
    from cleansed
)

select
    channel_name,
    channel_key,
    is_digital,
    {{ cleansing_layer_columns() }}
from assessed
where _dq_is_valid
