-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.
-- Regenerate after changing the synthetic data model.

{{ config(
    materialized='view'
) }}

with source as (
    select * from {{ source('lake_dimensions', 'dim_driver') }}
),

deduplicated as (
    select
        *,
        row_number() over (partition by driver_id order by driver_id desc) as _row_rank
    from source
),

renamed as (
    select
        driver_id,
        driver_key,
        driver_name,
        carrier_id,
        licence_class,
        hazmat_certified,
        years_experience,
        safety_score,
        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,
        {{ dbt_load_timestamp() }} as _dbt_loaded_at
    from deduplicated
    where _row_rank = 1
)

select * from renamed
