"""Generate dbt sources and staging models from the generated lake manifest.

The bronze landing zone has 155 tables. Hand-maintaining a staging model per
table is busy-work and drifts from the data; this script derives them from
`_manifest.json` so staging always matches what the generator actually wrote.

Each staging model:
  - selects from the bronze source
  - renames nothing (staging is a 1:1 typed view; renaming belongs in marts)
  - adds the standard dbt audit columns
  - deduplicates on the table's business key where one is detectable

Run:  python scripts/generate_dbt_staging.py --manifest data/lake/_manifest.json
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

HEADER = (
    "-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.\n"
    "-- Regenerate after changing the synthetic data model.\n"
)

# Columns that identify a row uniquely, in priority order of suffix.
KEY_SUFFIXES = ("_id",)

# Timestamp column preference for incremental filtering.
TS_PREFERENCE = (
    "transaction_ts", "event_ts", "sale_ts", "order_ts", "reading_ts",
    "receipt_ts", "movement_ts", "snapshot_ts", "session_start_ts",
    "issue_ts", "dip_ts", "payment_ts", "raised_ts", "failure_ts",
    "incident_ts", "delivery_ts", "posting_date", "period_date",
    "business_date", "snapshot_date", "invoice_date", "effective_ts",
    "planned_arrival_ts", "trip_start_ts", "opened_ts", "downtime_start_ts",
    "issued_ts", "reported_ts", "measurement_date", "completed_date",
    "loss_date", "order_date", "receipt_date", "response_ts",
    "billing_period_start", "eta_ts", "status_ts", "inspection_ts",
    "usage_ts", "adjustment_ts", "period_start_date", "effective_date",
    "return_ts", "uplift_ts", "session_end_ts", "ingested_at",
)


def pick_key(table: str, columns: list[str]) -> str | None:
    """The business key column, if the table has an obvious one."""
    singular = table.replace("fact_", "").replace("dim_", "")
    preferred = [
        f"{singular}_id",
        f"{singular.rstrip('s')}_id",
    ]
    for cand in preferred:
        if cand in columns:
            return cand
    id_cols = [c for c in columns if c.endswith(KEY_SUFFIXES)]
    # A single *_id column is unambiguous; several means it is a foreign key
    # soup and the first declared one is the grain.
    return id_cols[0] if id_cols else None


def pick_timestamp(columns: list[str]) -> str | None:
    for c in TS_PREFERENCE:
        if c in columns:
            return c
    return None


def render_model(table: str, columns: list[str], layer: str) -> str:
    key = pick_key(table, columns)
    ts = pick_timestamp(columns)

    cfg = ["    materialized='view'"]
    body = [HEADER, "{{ config(", ",\n".join(cfg), ") }}", ""]

    body.append("with source as (")
    body.append(f"    select * from {{{{ source('lake_{layer}', '{table}') }}}}")
    body.append("),")
    body.append("")

    if key:
        body.append("deduplicated as (")
        body.append("    select")
        body.append("        *,")
        order_col = ts or key
        body.append(
            f"        row_number() over (partition by {key} "
            f"order by {order_col} desc) as _row_rank"
        )
        body.append("    from source")
        body.append("),")
        body.append("")
        body.append("renamed as (")
        body.append("    select")
        for c in columns:
            body.append(f"        {c},")
        body.append("        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,")
        body.append("        {{ dbt_load_timestamp() }} as _dbt_loaded_at")
        body.append("    from deduplicated")
        body.append("    where _row_rank = 1")
        body.append(")")
    else:
        body.append("renamed as (")
        body.append("    select")
        for c in columns:
            body.append(f"        {c},")
        body.append("        cast('{{ invocation_id }}' as varchar) as _dbt_run_id,")
        body.append("        {{ dbt_load_timestamp() }} as _dbt_loaded_at")
        body.append("    from source")
        body.append(")")

    body.append("")
    body.append("select * from renamed")
    return "\n".join(body) + "\n"


def render_sources(tables: dict[str, dict]) -> str:
    dims = sorted(t for t in tables if not t.startswith("fact_"))
    facts = sorted(t for t in tables if t.startswith("fact_"))

    lines = [
        "# GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.",
        "version: 2",
        "",
        "sources:",
    ]
    for layer, names, folder in (
        ("dimensions", dims, "dimensions"),
        ("facts", facts, "facts"),
    ):
        lines += [
            f"  - name: lake_{layer}",
            "    description: >",
            f"      Bronze landing zone for {layer}. On DuckDB this reads the generated",
            "      Parquet lake directly; on Databricks it resolves to Delta tables in",
            "      the bronze schema of the environment catalog.",
            "    database: \"{{ env_var('VIVO_CATALOG', 'vivo_dev') }}\"",
            "    schema: bronze",
            "    meta:",
            "      external_location: >-",
            "        read_parquet('{{ env_var('VIVO_LAKE', '../data/lake') }}/"
            + folder
            + "/{name}/*.parquet', union_by_name=true)",
            "    tables:",
        ]
        for t in names:
            info = tables[t]
            lines.append(f"      - name: {t}")
            lines.append(
                f"        description: \"Bronze {t} -- "
                f"{info['rows']:,} synthetic rows.\""
            )
    return "\n".join(lines) + "\n"


def render_schema_yml(tables: dict[str, dict], layer: str) -> str:
    names = sorted(
        t for t in tables
        if (t.startswith("fact_") if layer == "facts" else not t.startswith("fact_"))
    )
    lines = [
        "# GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.",
        "version: 2",
        "",
        "models:",
    ]
    for t in names:
        cols = tables[t]["columns"]
        key = pick_key(t, cols)
        lines.append(f"  - name: stg_{t}")
        lines.append(f"    description: \"Cleaned 1:1 staging view over bronze {t}.\"")
        if key:
            lines.append("    columns:")
            lines.append(f"      - name: {key}")
            lines.append("        description: \"Business key.\"")
            lines.append("        data_tests:")
            lines.append("          - unique")
            lines.append("          - not_null")
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", type=Path, default=Path("data/lake/_manifest.json"))
    ap.add_argument("--out", type=Path, default=Path("dbt/models/staging"))
    args = ap.parse_args(argv)

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    tables = manifest["tables"]

    for sub in ("dimensions", "facts"):
        (args.out / sub).mkdir(parents=True, exist_ok=True)

    written = 0
    for table, info in sorted(tables.items()):
        layer = "facts" if table.startswith("fact_") else "dimensions"
        path = args.out / layer / f"stg_{table}.sql"
        path.write_text(render_model(table, info["columns"], layer), encoding="utf-8")
        written += 1

    (args.out / "_sources.yml").write_text(render_sources(tables), encoding="utf-8")
    (args.out / "dimensions" / "_schema.yml").write_text(
        render_schema_yml(tables, "dimensions"), encoding="utf-8")
    (args.out / "facts" / "_schema.yml").write_text(
        render_schema_yml(tables, "facts"), encoding="utf-8")

    print(f"wrote {written} staging models + sources + schema tests to {args.out}")


if __name__ == "__main__":
    main()
