"""Generate the dbt cleansing layer from the generated lake manifest.

The landing zone has 167 tables and is deliberately dirty (see
`src/vivo360/dirty.py`). Hand-writing a cleansing model per table would drift
from the data within a week, so the models are derived from `_manifest.json`,
which records each column's *intended* type -- captured before defect
injection, so the generator knows what a column is supposed to be rather than
guessing from the damaged values.

For each source table this emits two models:

  stg_<table>   cleansed rows that pass the contract. Text trimmed and
                sentinel-stripped, codes case-folded, numbers parsed out of
                locale-formatted text, timestamps range-checked, unit errors
                corrected, duplicates resolved on the business key.

  qtn_<table>   rows that failed, with a `_dq_failed_rules` column naming
                every rule they broke. Quarantined rather than dropped: a
                silently discarded row becomes an unexplainable variance three
                months later, and there is no way back from it.

Run:  python scripts/generate_dbt_staging.py --manifest data/lake/_manifest.json
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

HEADER = (
    "-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.\n"
    "-- Regenerate after changing the synthetic data model or defect profile.\n"
)

KEY_SUFFIXES = ("_id",)

TS_PREFERENCE = (
    "transaction_ts", "event_ts", "sale_ts", "order_ts", "reading_ts",
    "receipt_ts", "movement_ts", "snapshot_ts", "session_start_ts",
    "issue_ts", "dip_ts", "payment_ts", "raised_ts", "failure_ts",
    "incident_ts", "delivery_ts", "posting_date", "period_date",
    "business_date", "snapshot_date", "invoice_date", "effective_ts",
    "planned_arrival_ts", "trip_start_ts", "opened_ts", "downtime_start_ts",
    "issued_ts", "reported_ts", "measurement_date", "completed_date",
    "loss_date", "order_date", "receipt_date", "response_ts",
    "billing_period_start", "eta_ts", "status_ts", "inspection_ts",
    "usage_ts", "adjustment_ts", "period_start_date", "effective_date",
    "return_ts", "uplift_ts", "session_end_ts", "ingested_at",
)

# Measures where a kilolitre/litre confusion is recoverable, with the largest
# value that is still physically plausible for that column.
UNIT_CORRECTIONS = {
    "litres": 900,
    "volume_litres": 3_000_000,
    "quantity_litres": 15_000_000,
    "delivered_litres": 60_000,
    "quantity_kg": 60_000,
    "energy_kwh": 400,
    "uplift_litres": 300_000,
    "bunker_litres": 3_000_000,
}

# Columns that must be present for the row to mean anything.
def required_columns(table: str, columns: list[str], key: str | None) -> list[str]:
    req = [c for c in (key,) if c]
    for c in columns:
        if c in ("site_id", "product_id", "customer_id") and c not in req:
            req.append(c)
    return req


def pick_key(table: str, columns: list[str]) -> str | None:
    singular = table.replace("fact_", "").replace("dim_", "").replace("bridge_", "")
    for cand in (f"{singular}_id", f"{singular.rstrip('s')}_id"):
        if cand in columns:
            return cand
    id_cols = [c for c in columns if c.endswith(KEY_SUFFIXES)]
    return id_cols[0] if id_cols else None


def pick_timestamp(columns: list[str]) -> str | None:
    for c in TS_PREFERENCE:
        if c in columns:
            return c
    return None


def clean_expression(col: str, logical: str) -> str:
    """The cleansing expression for one column, given its intended type."""
    if logical == "code":
        return f"{{{{ clean_code('{col}') }}}}"
    if logical == "text":
        return f"{{{{ fix_mojibake('{col}') }}}}"
    if logical == "timestamp":
        return f"{{{{ clean_timestamp('{col}') }}}}"
    if logical == "integer":
        return f"{{{{ clean_integer('{col}') }}}}"
    if logical == "decimal":
        base = f"{{{{ clean_measure('{col}') }}}}"
        if col in UNIT_CORRECTIONS:
            return (f"{{{{ correct_unit_error(clean_measure('{col}'), "
                    f"{UNIT_CORRECTIONS[col]}) }}}}")
        return base
    if logical == "boolean":
        return f"try_cast({col} as boolean)"
    return f"{{{{ clean_text('{col}') }}}}"


def quality_rules(table: str, columns: list[str], types: dict,
                  key: str | None) -> dict[str, str]:
    """Row-level rules deciding clean vs quarantined."""
    rules: dict[str, str] = {}
    for col in required_columns(table, columns, key):
        rules[f"{col}_present"] = f"{col} is not null"

    ts = pick_timestamp(columns)
    if ts and types.get(ts) == "timestamp":
        rules["event_timestamp_valid"] = f"{ts} is not null"

    for col in columns:
        if types.get(col) != "decimal":
            continue
        if col.endswith(("_zar", "_usd")) or col in UNIT_CORRECTIONS:
            # A negative measure is a sign error or an unflagged credit; either
            # way it must not be silently summed into a revenue total.
            rules[f"{col}_non_negative"] = f"{col} >= 0"
        if col in UNIT_CORRECTIONS:
            rules[f"{col}_within_range"] = (
                f"{col} <= {UNIT_CORRECTIONS[col]}")
    return rules


def render_model(table: str, columns: list[str], types: dict,
                 layer: str, quarantine: bool) -> str:
    key = pick_key(table, columns)
    ts = pick_timestamp(columns)
    rules = quality_rules(table, columns, types, key)

    # Materialisation is deliberately not set here. It comes from
    # dbt_project.yml, so the cleansing layer can be switched between table
    # and view in one place rather than by regenerating 289 files.
    out = [HEADER]

    ctes: list[str] = []

    src = ["with source as (",
           f"    select * from {{{{ source('lake_{layer}', '{table}') }}}}",
           ")"]
    ctes.append("\n".join(src))

    repair = ["-- Stage 1: repair. Trim, case-fold, parse numbers out of",
              "-- locale-formatted text, range-check timestamps.",
              "cleansed as (",
              "    select"]
    repair += [
        f"        {clean_expression(col, types.get(col, 'text'))} as {col},"
        for col in columns[:-1]
    ]
    last = columns[-1]
    repair.append(
        f"        {clean_expression(last, types.get(last, 'text'))} as {last}")
    repair += ["    from source", ")"]
    ctes.append("\n".join(repair))

    if rules:
        assess = ["-- Stage 2: assess. One boolean per rule, so a quarantined",
                  "-- row records exactly why it was rejected.",
                  "assessed as (",
                  "    select",
                  "        *,"]
        assess += [f"        ({expr}) as _dq_{name},"
                   for name, expr in rules.items()]
        checks = " and ".join(f"coalesce(_dq_{n}, false)" for n in rules)
        assess.append(f"        ({checks}) as _dq_is_valid,")
        assess.append("        concat_ws(',',")
        assess.append(",\n".join(
            f"            case when not coalesce(_dq_{n}, false) then '{n}' end"
            for n in rules))
        assess.append("        ) as _dq_failed_rules")
        assess += ["    from cleansed", ")"]
    else:
        assess = ["assessed as (",
                  "    select *,",
                  "           true as _dq_is_valid,",
                  "           cast('' as varchar) as _dq_failed_rules",
                  "    from cleansed",
                  ")"]
    ctes.append("\n".join(assess))
    stage = "assessed"

    if quarantine:
        final = ["-- Rows that failed the contract. Kept, not dropped: a",
                 "-- silently discarded row becomes an unexplainable variance",
                 "-- months later, and there is no way back from it.",
                 "select",
                 f"    '{table}' as _source_table,"]
        final += [f"    {col}," for col in columns]
        final += ["    _dq_failed_rules,",
                  "    {{ cleansing_layer_columns() }}",
                  f"from {stage}",
                  "where not _dq_is_valid"]
    elif key:
        dedup = ["-- Stage 3: deduplicate. Source systems replay batches, so the",
                 "-- same business key can arrive more than once. Keep the most",
                 "-- recently ingested version.",
                 "deduplicated as (",
                 "    select",
                 "        *,"]
        order_col = "ingested_at" if "ingested_at" in columns else (ts or key)
        dedup += [
            f"        row_number() over (partition by {key} "
            f"order by {order_col} desc nulls last) as _row_rank",
            f"    from {stage}",
            "    where _dq_is_valid",
            ")"]
        ctes.append("\n".join(dedup))

        final = ["select"]
        final += [f"    {col}," for col in columns]
        final += ["    {{ cleansing_layer_columns() }}",
                  "from deduplicated",
                  "where _row_rank = 1"]
    else:
        final = ["select"]
        final += [f"    {col}," for col in columns]
        final += ["    {{ cleansing_layer_columns() }}",
                  f"from {stage}",
                  "where _dq_is_valid"]

    out.append(",\n\n".join(ctes))
    out.append("")
    out.append("\n".join(final))
    return "\n".join(out) + "\n"


def render_sources(tables: dict[str, dict]) -> str:
    dims = sorted(t for t in tables if not t.startswith("fact_"))
    facts = sorted(t for t in tables if t.startswith("fact_"))
    lines = [
        "# GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.",
        "version: 2",
        "",
        "sources:",
    ]
    for layer, names, folder in (("dimensions", dims, "dimensions"),
                                 ("facts", facts, "facts")):
        lines += [
            f"  - name: lake_{layer}",
            "    description: >",
            f"      Bronze landing zone for {layer}. Deliberately dirty: numbers",
            "      arrive as locale-formatted text, codes carry whitespace and",
            "      inconsistent casing, sentinels stand in for NULL, and source",
            "      batches replay. Cleansed by the stg_ models.",
            # No `database` on purpose: the catalog comes from the profile
            # target, so one definition serves DuckDB and every Databricks env.
            "    schema: bronze",
            "    meta:",
            "      external_location: >-",
            "        read_parquet('{{ env_var('VIVO_LAKE', '../data/lake') }}/"
            + folder + "/{name}/*.parquet', union_by_name=true)",
            "    tables:",
        ]
        for t in names:
            lines.append(f"      - name: {t}")
            lines.append(
                f"        description: \"Raw {t} -- {tables[t]['rows']:,} rows "
                f"as delivered by the source system.\"")
    return "\n".join(lines) + "\n"


def render_schema_yml(tables: dict[str, dict], layer: str) -> str:
    names = sorted(
        t for t in tables
        if (t.startswith("fact_") if layer == "facts" else not t.startswith("fact_")))
    lines = [
        "# GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.",
        "version: 2",
        "",
        "models:",
    ]
    for t in names:
        cols = tables[t]["columns"]
        key = pick_key(t, cols)
        lines.append(f"  - name: stg_{t}")
        lines.append(
            f"    description: \"Cleansed {t}. Repaired, validated and "
            f"deduplicated; rejected rows are in qtn_{t}.\"")
        if key:
            lines.append("    columns:")
            lines.append(f"      - name: {key}")
            lines.append(
                "        description: \"Business key. Unique and not null "
                "after cleansing -- if this fails, the cleansing layer is "
                "letting bad rows through.\"")
            lines.append("        data_tests:")
            lines.append("          - unique")
            lines.append("          - not_null")
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", type=Path, default=Path("data/lake/_manifest.json"))
    ap.add_argument("--out", type=Path, default=Path("dbt/models/staging"))
    ap.add_argument("--quarantine-out", type=Path,
                    default=Path("dbt/models/quarantine"))
    args = ap.parse_args(argv)

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    tables = manifest["tables"]

    for sub in ("dimensions", "facts"):
        (args.out / sub).mkdir(parents=True, exist_ok=True)
    args.quarantine_out.mkdir(parents=True, exist_ok=True)

    n_stg = n_qtn = 0
    for table, info in sorted(tables.items()):
        layer = "facts" if table.startswith("fact_") else "dimensions"
        cols = info["columns"]
        types = info.get("intended_types", {})

        (args.out / layer / f"stg_{table}.sql").write_text(
            render_model(table, cols, types, layer, quarantine=False),
            encoding="utf-8")
        n_stg += 1

        if quality_rules(table, cols, types, pick_key(table, cols)):
            (args.quarantine_out / f"qtn_{table}.sql").write_text(
                render_model(table, cols, types, layer, quarantine=True),
                encoding="utf-8")
            n_qtn += 1

    (args.out / "_sources.yml").write_text(render_sources(tables), encoding="utf-8")
    (args.out / "dimensions" / "_schema.yml").write_text(
        render_schema_yml(tables, "dimensions"), encoding="utf-8")
    (args.out / "facts" / "_schema.yml").write_text(
        render_schema_yml(tables, "facts"), encoding="utf-8")

    print(f"wrote {n_stg} cleansing models to {args.out}")
    print(f"wrote {n_qtn} quarantine models to {args.quarantine_out}")


if __name__ == "__main__":
    main()
