"""Generate the dbt cleansing layer from the generated lake manifest.

The landing zone has 167 tables and is deliberately dirty (see
`src/drakens360/dirty.py`). Hand-writing a cleansing model per table would drift
from the data within a week, so the models are derived from `_manifest.json`,
which records each column's *intended* type -- captured before defect
injection, so the generator knows what a column is supposed to be rather than
guessing from the damaged values.

For each source table this emits two models:

  stg_<table>   cleansed rows that pass the contract. Text trimmed and
                sentinel-stripped, codes case-folded, numbers parsed out of
                locale-formatted text, timestamps range-checked, unit errors
                corrected, duplicates resolved on the business key.

  qtn_<table>   rows that failed, with a `_dq_failed_rules` column naming
                every rule they broke. Quarantined rather than dropped: a
                silently discarded row becomes an unexplainable variance three
                months later, and there is no way back from it.

Run:  python scripts/generate_dbt_staging.py --manifest data/lake/_manifest.json
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

HEADER = (
    "-- GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.\n"
    "-- Regenerate after changing the synthetic data model or defect profile.\n"
)

KEY_SUFFIXES = ("_id",)

TS_PREFERENCE = (
    "transaction_ts", "event_ts", "sale_ts", "order_ts", "reading_ts",
    "receipt_ts", "movement_ts", "snapshot_ts", "session_start_ts",
    "issue_ts", "dip_ts", "payment_ts", "raised_ts", "failure_ts",
    "incident_ts", "delivery_ts", "posting_date", "period_date",
    "business_date", "snapshot_date", "invoice_date", "effective_ts",
    "planned_arrival_ts", "trip_start_ts", "opened_ts", "downtime_start_ts",
    "issued_ts", "reported_ts", "measurement_date", "completed_date",
    "loss_date", "order_date", "receipt_date", "response_ts",
    "billing_period_start", "eta_ts", "status_ts", "inspection_ts",
    "usage_ts", "adjustment_ts", "period_start_date", "effective_date",
    "return_ts", "uplift_ts", "session_end_ts", "ingested_at",
)

# Measures where a kilolitre/litre confusion is recoverable, with the largest
# value that is still physically plausible for that column.
UNIT_CORRECTIONS = {
    "litres": 900,
    "volume_litres": 3_000_000,
    "quantity_litres": 15_000_000,
    "delivered_litres": 60_000,
    "quantity_kg": 60_000,
    "energy_kwh": 400,
    "uplift_litres": 300_000,
    "bunker_litres": 3_000_000,
}

# Dates that describe *when something began*, not when an event happened.
#
# The default timestamp window is deliberately tight: a transaction dated 2099
# is clock skew, and a transaction dated 1970 is a dead clock. Applied to an
# attribute, the same rule is destructive. `dim_site.opened_date` records when
# a station opened, and stations open decades before the window a warehouse
# happens to model -- so the tight bound nulled 521 of 586 opening dates, 89%
# of the network, while every model built successfully and every test passed.
#
# The symptom was a map panel reporting that the entire network was between
# one and two years old, and an investment rule gated on "older than 12 years"
# that could never fire because no site could be older than three.
#
# These columns get a window wide enough to hold a real business history.
ATTRIBUTE_DATE_BOUNDS = ("1950-01-01", "2035-12-31")

ATTRIBUTE_DATE_SUFFIXES = (
    "opened_date", "onboarded_date", "commissioned_date", "hire_date",
    "start_date", "end_date", "expiry_date", "built_date",
    "installed_date", "first_order_date", "birth_date", "issued_date",
    "registration_date", "renewal_date", "valid_from_date", "valid_to_date",
)


def is_attribute_date(col: str) -> bool:
    return col.endswith(ATTRIBUTE_DATE_SUFFIXES)


# Amount columns that are legitimately signed, and must never be given a
# non-negativity rule.
#
# This exists because the blanket rule "any column ending _zar must be >= 0"
# quarantined 41,886 of the general ledger's 84,000 lines -- every credit leg
# of every journal -- because `signed_amount_zar` is negative on the credit
# side *by design*. The ledger that survived contained debits and almost no
# credits, so it could not balance, and the GL_DEBITS_EQUAL_CREDITS control
# reported a 99.98% variance that looked like a generator bug and was actually
# a contract bug.
#
# The lesson generalises: a validity rule inferred from a column's name is a
# guess, and a wrong guess deletes data silently rather than failing loudly.
# Signed measures are matched on the naming conventions that mean "this may be
# negative" rather than listed one by one, so a new net_ or _variance column
# is covered the day it is added.
SIGNED_PREFIXES = ("signed_", "net_", "delta_", "adjustment_", "variance_")
SIGNED_SUFFIXES = ("_variance_zar", "_delta_zar", "_change_zar",
                   "_adjustment_zar", "_movement_zar")


def is_signed_measure(col: str) -> bool:
    return col.startswith(SIGNED_PREFIXES) or col.endswith(SIGNED_SUFFIXES)


# Cross-field consistency rules, keyed on the columns they need.
#
# These exist because the single-column rules cannot catch the most damaging
# defect in the landing zone. The injector uses 0 as one of its numeric
# sentinels, and 0 passes every non-negativity check ever written. Stripping
# zero the way -999 is stripped is not an option either: zero litres, zero
# margin and zero downtime are all legitimate readings, and nulling them would
# destroy more data than the sentinel does.
#
# What a zero sentinel cannot survive is being checked against its own row. A
# transaction with 82 litres at R22.34 that reports R0.00 of sales is
# internally inconsistent whatever caused it -- a sentinel, a transposed
# digit, a truncated field -- so the rule catches the class rather than the
# instance.
#
# Tolerances are absolute rand amounts, not percentages, because the rounding
# error being allowed for is a rounding error in cents and does not scale with
# the size of the transaction.
CONSISTENCY_RULES = [
    (
        "amounts_reconcile",
        ("gross_sales_zar", "cogs_zar", "gross_margin_zar"),
        "abs(gross_sales_zar - cogs_zar - gross_margin_zar) <= 0.05",
    ),
    (
        "amounts_reconcile",
        ("revenue_zar", "cogs_zar", "gross_margin_zar"),
        "abs(revenue_zar - cogs_zar - gross_margin_zar) <= 0.05",
    ),
    (
        "sales_match_quantity_and_price",
        ("gross_sales_zar", "litres", "unit_price_zar"),
        "abs(gross_sales_zar - litres * unit_price_zar) <= 0.05",
    ),
]

# Percentages that are a share of something and therefore cannot fall
# outside 0-100.
#
# Listed explicitly rather than matched on a `_pct` suffix. Twice in this
# project a rule inferred from a column's name destroyed legitimate data --
# every credit leg of the general ledger, then 89% of site opening dates --
# and both times the rule looked obviously right. A margin percentage can be
# negative on a bad day and a growth rate is negative half the time, so the
# broad version of this rule would quarantine real rows. Only the ratios whose
# denominator physically bounds them are constrained.
BOUNDED_PERCENTAGES = {
    "fill_pct": (0, 100),
    "fill_rate_pct": (0, 100),
    "power_utilisation_pct": (0, 100),
    "otif_pct": (0, 100),
    "breakdown_rate_pct": (0, 100),
    "uptime_pct": (0, 100),
    "utilisation_pct": (0, 100),
    "compliance_pct": (0, 100),
    "attendance_pct": (0, 100),
}

# Physical quantities that cannot be negative. Listed explicitly, for the
# same reason as BOUNDED_PERCENTAGES: a suffix rule would sweep in
# delay_minutes, which is legitimately negative when a load arrives early.
NON_NEGATIVE_MEASURES = {
    "average_power_kw", "rated_power_kw", "energy_kwh", "capacity_litres",
    "stock_on_hand_litres", "solar_kwh", "generation_kwh",
}

# Plausible bands for unit prices. A regulated South African fuel price has
# never been R1.51 or R0.00 a litre; a row claiming one has lost a decimal
# separator or picked up a sentinel, and it must not reach a margin
# calculation. The band is deliberately wide -- it is a sanity check, not a
# forecast of the pump price.
PRICE_BANDS = {
    "unit_price_zar": (8.0, 45.0),
    "price_per_litre_zar": (8.0, 45.0),
}

# Columns that must be present for the row to mean anything.
def required_columns(table: str, columns: list[str], key: str | None) -> list[str]:
    req = [c for c in (key,) if c]
    # Foreign keys a row cannot be interpreted without, plus country_code:
    # a site or customer with no country cannot be placed on a map, rolled up
    # to a market, or priced in the right currency, so a row missing it is
    # unusable rather than merely incomplete.
    for c in columns:
        if c in ("site_id", "product_id", "customer_id", "country_code") \
                and c not in req:
            req.append(c)
    return req


def pick_key(table: str, columns: list[str]) -> str | None:
    singular = table.replace("fact_", "").replace("dim_", "").replace("bridge_", "")
    for cand in (f"{singular}_id", f"{singular.rstrip('s')}_id"):
        if cand in columns:
            return cand
    id_cols = [c for c in columns if c.endswith(KEY_SUFFIXES)]
    return id_cols[0] if id_cols else None


def pick_timestamp(columns: list[str]) -> str | None:
    for c in TS_PREFERENCE:
        if c in columns:
            return c
    return None


def clean_expression(col: str, logical: str) -> str:
    """The cleansing expression for one column, given its intended type."""
    if logical == "code":
        return f"{{{{ clean_code('{col}') }}}}"
    if logical == "text":
        return f"{{{{ fix_mojibake('{col}') }}}}"
    if logical == "timestamp":
        if is_attribute_date(col):
            return (f"{{{{ clean_timestamp('{col}', "
                    f"'{ATTRIBUTE_DATE_BOUNDS[0]}', "
                    f"'{ATTRIBUTE_DATE_BOUNDS[1]}') }}}}")
        return f"{{{{ clean_timestamp('{col}') }}}}"
    if logical == "integer":
        return f"{{{{ clean_integer('{col}') }}}}"
    if logical == "decimal":
        base = f"{{{{ clean_measure('{col}') }}}}"
        if col in UNIT_CORRECTIONS:
            return (f"{{{{ correct_unit_error(clean_measure('{col}'), "
                    f"{UNIT_CORRECTIONS[col]}) }}}}")
        return base
    if logical == "boolean":
        return f"try_cast({col} as boolean)"
    return f"{{{{ clean_text('{col}') }}}}"


def quality_rules(table: str, columns: list[str], types: dict,
                  key: str | None) -> dict[str, str]:
    """Row-level rules deciding clean vs quarantined."""
    rules: dict[str, str] = {}
    for col in required_columns(table, columns, key):
        rules[f"{col}_present"] = f"{col} is not null"

    ts = pick_timestamp(columns)
    if ts and types.get(ts) == "timestamp":
        rules["event_timestamp_valid"] = f"{ts} is not null"

    for col in columns:
        if types.get(col) != "decimal":
            continue
        if ((col.endswith(("_zar", "_usd")) or col in UNIT_CORRECTIONS)
                and not is_signed_measure(col)):
            # A negative measure is a sign error or an unflagged credit; either
            # way it must not be silently summed into a revenue total. Columns
            # that are *meant* to carry a sign are excluded -- see
            # SIGNED_PREFIXES for what applying this rule to one of them cost.
            rules[f"{col}_non_negative"] = f"{col} >= 0"
        if col in UNIT_CORRECTIONS:
            rules[f"{col}_within_range"] = (
                f"{col} <= {UNIT_CORRECTIONS[col]}")
        if col in PRICE_BANDS:
            lo, hi = PRICE_BANDS[col]
            rules[f"{col}_plausible"] = f"{col} between {lo} and {hi}"
        if col in NON_NEGATIVE_MEASURES:
            rules[f"{col}_non_negative"] = f"{col} >= 0"
        if col in BOUNDED_PERCENTAGES:
            lo, hi = BOUNDED_PERCENTAGES[col]
            rules[f"{col}_in_range"] = f"{col} between {lo} and {hi}"

    # Cross-field rules apply only where the table carries every column the
    # rule reads. A rule silently skipped because a column is missing is worse
    # than no rule, so membership is checked explicitly rather than assumed
    # from the table name.
    present = set(columns)
    for name, needed, expression in CONSISTENCY_RULES:
        if present.issuperset(needed):
            rules[name] = expression

    return rules


def render_cleansed(table: str, columns: list[str], types: dict,
                    layer: str) -> str:
    key = pick_key(table, columns)
    rules = quality_rules(table, columns, types, key)

    # Materialisation comes from dbt_project.yml so the layer can be switched
    # in one place rather than by regenerating hundreds of files.
    out = [HEADER,
           "-- Stage 1 of 2 in the cleansing layer: repair every column and",
           "-- assess every row, once. `stg_` and `qtn_` both read from here,",
           "-- so the expensive parsing is not paid for twice.",
           ""]

    ctes: list[str] = []

    src = ["with source as (",
           f"    select * from {{{{ source('lake_{layer}', '{table}') }}}}",
           ")"]
    ctes.append("\n".join(src))

    repair = ["-- Stage 1: repair. Trim, case-fold, parse numbers out of",
              "-- locale-formatted text, range-check timestamps.",
              "cleansed as (",
              "    select"]
    repair += [
        f"        {clean_expression(col, types.get(col, 'text'))} as {col},"
        for col in columns[:-1]
    ]
    last = columns[-1]
    repair.append(
        f"        {clean_expression(last, types.get(last, 'text'))} as {last}")
    repair += ["    from source", ")"]
    ctes.append("\n".join(repair))

    if rules:
        assess = ["-- Stage 2: assess. One boolean per rule, so a quarantined",
                  "-- row records exactly why it was rejected.",
                  "assessed as (",
                  "    select",
                  "        *,"]
        assess += [f"        ({expr}) as _dq_{name},"
                   for name, expr in rules.items()]
        checks = " and ".join(f"coalesce(_dq_{n}, false)" for n in rules)
        assess.append(f"        ({checks}) as _dq_is_valid,")
        assess.append("        concat_ws(',',")
        assess.append(",\n".join(
            f"            case when not coalesce(_dq_{n}, false) then '{n}' end"
            for n in rules))
        assess.append("        ) as _dq_failed_rules")
        assess += ["    from cleansed", ")"]
    else:
        assess = ["assessed as (",
                  "    select *,",
                  "           true as _dq_is_valid,",
                  "           cast('' as varchar) as _dq_failed_rules",
                  "    from cleansed",
                  ")"]
    ctes.append("\n".join(assess))

    final = ["select", "    *,", "    {{ cleansing_layer_columns() }}",
             "from assessed"]

    out.append(",\n\n".join(ctes))
    out.append("")
    out.append("\n".join(final))
    return "\n".join(out) + "\n"


def render_staging(table: str, columns: list[str], types: dict) -> str:
    """Valid rows only, deduplicated on the business key.

    Reads the already-repaired `cln_` table rather than re-parsing the raw
    landing zone, which is the whole reason the cleansing layer is split in
    two: the parsing is the expensive part and it is paid for once.
    """
    key = pick_key(table, columns)
    ts = pick_timestamp(columns)

    out = [HEADER,
           "-- Stage 2 of 2: the clean, conformed rows the marts consume.",
           ""]

    if key:
        order_col = "ingested_at" if "ingested_at" in columns else (ts or key)
        out += [
            "-- Source systems replay batches, so the same business key can",
            "-- arrive more than once. Keep the most recently ingested version.",
            "with deduplicated as (",
            "    select",
            "        *,",
            f"        row_number() over (partition by {key} "
            f"order by {order_col} desc nulls last) as _row_rank",
            f"    from {{{{ ref('cln_{table}') }}}}",
            "    where _dq_is_valid",
            ")",
            "",
            "select"]
        out += [f"    {col}," for col in columns]
        out += ["    _cleansed_at",
                "from deduplicated",
                "where _row_rank = 1"]
    else:
        out.append("select")
        out += [f"    {col}," for col in columns]
        out += ["    _cleansed_at",
                f"from {{{{ ref('cln_{table}') }}}}",
                "where _dq_is_valid"]
    return "\n".join(out) + "\n"


def render_quarantine(table: str, columns: list[str]) -> str:
    """Rejected rows, with the rule that rejected each one."""
    out = [HEADER,
           "-- Rows that failed the contract. Kept, not dropped: a silently",
           "-- discarded row becomes an unexplainable variance months later,",
           "-- and there is no way back from it.",
           "",
           "select",
           f"    '{table}' as _source_table,"]
    out += [f"    {col}," for col in columns]
    out += ["    _dq_failed_rules,",
            "    _cleansed_at",
            f"from {{{{ ref('cln_{table}') }}}}",
            "where not _dq_is_valid"]
    return "\n".join(out) + "\n"


def render_sources(tables: dict[str, dict]) -> str:
    dims = sorted(t for t in tables if not t.startswith("fact_"))
    facts = sorted(t for t in tables if t.startswith("fact_"))
    lines = [
        "# GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.",
        "version: 2",
        "",
        "sources:",
    ]
    for layer, names, folder in (("dimensions", dims, "dimensions"),
                                 ("facts", facts, "facts")):
        lines += [
            f"  - name: lake_{layer}",
            "    description: >",
            f"      Bronze landing zone for {layer}. Deliberately dirty: numbers",
            "      arrive as locale-formatted text, codes carry whitespace and",
            "      inconsistent casing, sentinels stand in for NULL, and source",
            "      batches replay. Cleansed by the stg_ models.",
            # No `database` on purpose: the catalog comes from the profile
            # target, so one definition serves DuckDB and every Databricks env.
            "    schema: bronze",
            "    meta:",
            "      external_location: >-",
            "        read_parquet('{{ env_var('DRAKENS_LAKE', '../data/lake') }}/"
            + folder + "/{name}/*.parquet', union_by_name=true)",
            "    tables:",
        ]
        for t in names:
            lines.append(f"      - name: {t}")
            lines.append(
                f"        description: \"Raw {t} -- {tables[t]['rows']:,} rows "
                f"as delivered by the source system.\"")
    return "\n".join(lines) + "\n"


def render_schema_yml(tables: dict[str, dict], layer: str) -> str:
    names = sorted(
        t for t in tables
        if (t.startswith("fact_") if layer == "facts" else not t.startswith("fact_")))
    lines = [
        "# GENERATED by scripts/generate_dbt_staging.py -- do not edit by hand.",
        "version: 2",
        "",
        "models:",
    ]
    for t in names:
        cols = tables[t]["columns"]
        key = pick_key(t, cols)
        lines.append(f"  - name: stg_{t}")
        lines.append(
            f"    description: \"Cleansed {t}. Repaired, validated and "
            f"deduplicated; rejected rows are in qtn_{t}.\"")
        if key:
            lines.append("    columns:")
            lines.append(f"      - name: {key}")
            lines.append(
                "        description: \"Business key. Unique and not null "
                "after cleansing -- if this fails, the cleansing layer is "
                "letting bad rows through.\"")
            lines.append("        data_tests:")
            lines.append("          - unique")
            lines.append("          - not_null")
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", type=Path, default=Path("data/lake/_manifest.json"))
    ap.add_argument("--out", type=Path, default=Path("dbt/models/staging"))
    ap.add_argument("--cleansed-out", type=Path,
                    default=Path("dbt/models/cleansed"))
    ap.add_argument("--quarantine-out", type=Path,
                    default=Path("dbt/models/quarantine"))
    args = ap.parse_args(argv)

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    tables = manifest["tables"]

    for sub in ("dimensions", "facts"):
        (args.out / sub).mkdir(parents=True, exist_ok=True)
        (args.cleansed_out / sub).mkdir(parents=True, exist_ok=True)
    args.quarantine_out.mkdir(parents=True, exist_ok=True)

    n_cln = n_stg = n_qtn = 0
    for table, info in sorted(tables.items()):
        layer = "facts" if table.startswith("fact_") else "dimensions"
        cols = info["columns"]
        types = info.get("intended_types", {})

        (args.cleansed_out / layer / f"cln_{table}.sql").write_text(
            render_cleansed(table, cols, types, layer), encoding="utf-8")
        n_cln += 1

        (args.out / layer / f"stg_{table}.sql").write_text(
            render_staging(table, cols, types), encoding="utf-8")
        n_stg += 1

        if quality_rules(table, cols, types, pick_key(table, cols)):
            (args.quarantine_out / f"qtn_{table}.sql").write_text(
                render_quarantine(table, cols), encoding="utf-8")
            n_qtn += 1

    (args.cleansed_out / "_sources.yml").write_text(
        render_sources(tables), encoding="utf-8")
    (args.out / "dimensions" / "_schema.yml").write_text(
        render_schema_yml(tables, "dimensions"), encoding="utf-8")
    (args.out / "facts" / "_schema.yml").write_text(
        render_schema_yml(tables, "facts"), encoding="utf-8")

    print(f"wrote {n_cln} repair/assess models to {args.cleansed_out}")
    print(f"wrote {n_stg} staging models to {args.out}")
    print(f"wrote {n_qtn} quarantine models to {args.quarantine_out}")


if __name__ == "__main__":
    main()
