table agg_executive_daily_kpi

	column 'Date Key'
		dataType: int64
		sourceColumn: date_key
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Full Date'
		dataType: dateTime
		sourceColumn: full_date
		summarizeBy: none
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	column 'Day Name'
		dataType: string
		sourceColumn: day_name
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Month Name'
		dataType: string
		sourceColumn: month_name
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Calendar Year'
		dataType: int64
		sourceColumn: calendar_year
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Fiscal Year'
		dataType: int64
		sourceColumn: fiscal_year
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Fiscal Quarter'
		dataType: int64
		sourceColumn: fiscal_quarter
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Is Weekend'
		dataType: boolean
		sourceColumn: is_weekend
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Is Public Holiday ZA'
		dataType: boolean
		sourceColumn: is_public_holiday_za
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Province'
		dataType: string
		sourceColumn: province
		summarizeBy: none
		dataCategory: StateOrProvince
		annotation SummarizationSetBy = "Automatic"

	column 'Trading Sites'
		dataType: int64
		sourceColumn: trading_sites
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Fuel Litres'
		dataType: double
		sourceColumn: fuel_litres
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Fuel Revenue (R)'
		dataType: decimal
		sourceColumn: fuel_revenue_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Fuel Margin (R)'
		dataType: decimal
		sourceColumn: fuel_margin_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Fuel Transactions'
		dataType: int64
		sourceColumn: fuel_transactions
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Shop Revenue (R)'
		dataType: decimal
		sourceColumn: shop_revenue_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Shop Margin (R)'
		dataType: decimal
		sourceColumn: shop_margin_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Total Revenue (R)'
		dataType: decimal
		sourceColumn: total_revenue_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Total Margin (R)'
		dataType: decimal
		sourceColumn: total_margin_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Delivery Count'
		dataType: int64
		sourceColumn: delivery_count
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'OTIF Deliveries'
		dataType: int64
		sourceColumn: otif_deliveries
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'OTIF %'
		dataType: double
		sourceColumn: otif_pct
		summarizeBy: none
		formatString: 0.0%
		annotation SummarizationSetBy = "Automatic"

	column 'Incident Count'
		dataType: int64
		sourceColumn: incident_count
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Reportable Incidents'
		dataType: int64
		sourceColumn: reportable_incidents
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Lost Time Injuries'
		dataType: int64
		sourceColumn: lost_time_injuries
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'EV Sessions'
		dataType: int64
		sourceColumn: ev_sessions
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'EV kWh'
		dataType: double
		sourceColumn: ev_kwh
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Gross Margin %'
		dataType: double
		sourceColumn: gross_margin_pct
		summarizeBy: none
		formatString: 0.0%
		annotation SummarizationSetBy = "Automatic"

	column 'Non Fuel Margin Share %'
		dataType: double
		sourceColumn: non_fuel_margin_share_pct
		summarizeBy: none
		formatString: 0.0%
		annotation SummarizationSetBy = "Automatic"

	column 'Litres Per Site'
		dataType: double
		sourceColumn: litres_per_site
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	partition agg_executive_daily_kpi = m
		mode: import
		source =
				let
				    Path    = DataFolder & "agg_executive_daily_kpi.csv",
				    Source  = Csv.Document(File.Contents(Path), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Chosen  = Table.SelectColumns(Headers, {"date_key", "full_date", "day_name", "month_name", "calendar_year", "fiscal_year", "fiscal_quarter", "is_weekend", "is_public_holiday_za", "province", "trading_sites", "fuel_litres", "fuel_revenue_zar", "fuel_margin_zar", "fuel_transactions", "shop_revenue_zar", "shop_margin_zar", "total_revenue_zar", "total_margin_zar", "delivery_count", "otif_deliveries", "otif_pct", "incident_count", "reportable_incidents", "lost_time_injuries", "ev_sessions", "ev_kwh", "gross_margin_pct", "non_fuel_margin_share_pct", "litres_per_site"}),
				    Typed   = Table.TransformColumnTypes(Chosen, {{"date_key", Int64.Type}, {"full_date", type datetime}, {"day_name", type text}, {"month_name", type text}, {"calendar_year", Int64.Type}, {"fiscal_year", Int64.Type}, {"fiscal_quarter", Int64.Type}, {"is_weekend", type logical}, {"is_public_holiday_za", type logical}, {"province", type text}, {"trading_sites", Int64.Type}, {"fuel_litres", type number}, {"fuel_revenue_zar", type number}, {"fuel_margin_zar", type number}, {"fuel_transactions", Int64.Type}, {"shop_revenue_zar", type number}, {"shop_margin_zar", type number}, {"total_revenue_zar", type number}, {"total_margin_zar", type number}, {"delivery_count", Int64.Type}, {"otif_deliveries", Int64.Type}, {"otif_pct", type number}, {"incident_count", Int64.Type}, {"reportable_incidents", Int64.Type}, {"lost_time_injuries", Int64.Type}, {"ev_sessions", Int64.Type}, {"ev_kwh", type number}, {"gross_margin_pct", type number}, {"non_fuel_margin_share_pct", type number}, {"litres_per_site", type number}})
				in
				    Typed
