table bridge_security_user_scope

	column 'User Principal'
		dataType: string
		sourceColumn: user_principal
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Scope Type'
		dataType: string
		sourceColumn: scope_type
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Scope Value'
		dataType: string
		sourceColumn: scope_value
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Grants Everything'
		dataType: boolean
		sourceColumn: grants_everything
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Dw Loaded At'
		dataType: dateTime
		sourceColumn: dw_loaded_at
		summarizeBy: none
		isHidden
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	partition bridge_security_user_scope = m
		mode: import
		source =
				let
				    Path    = DataFolder & "bridge_security_user_scope.csv",
				    Source  = Csv.Document(File.Contents(Path), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Chosen  = Table.SelectColumns(Headers, {"user_principal", "scope_type", "scope_value", "grants_everything", "dw_loaded_at"}),
				    Typed   = Table.TransformColumnTypes(Chosen, {{"user_principal", type text}, {"scope_type", type text}, {"scope_value", type text}, {"grants_everything", type logical}, {"dw_loaded_at", type datetime}})
				in
				    Typed
