table dim_product

	column 'Product Key'
		dataType: int64
		sourceColumn: product_key
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Product ID'
		dataType: string
		sourceColumn: product_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Product Name'
		dataType: string
		sourceColumn: product_name
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Category'
		dataType: string
		sourceColumn: category
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Subcategory'
		dataType: string
		sourceColumn: subcategory
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Brand'
		dataType: string
		sourceColumn: brand
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Uom'
		dataType: string
		sourceColumn: uom
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Base Price (R)'
		dataType: double
		sourceColumn: base_price_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Base Cost (R)'
		dataType: double
		sourceColumn: base_cost_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Regulated'
		dataType: boolean
		sourceColumn: regulated
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Hazard Class'
		dataType: string
		sourceColumn: hazard_class
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Shelf Life Days'
		dataType: int64
		sourceColumn: shelf_life_days
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Base Unit Margin (R)'
		dataType: decimal
		sourceColumn: base_unit_margin_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Base Margin %'
		dataType: double
		sourceColumn: base_margin_pct
		summarizeBy: none
		formatString: 0.0%
		annotation SummarizationSetBy = "Automatic"

	column 'Price Regime'
		dataType: string
		sourceColumn: price_regime
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Reporting Line'
		dataType: string
		sourceColumn: reporting_line
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Effective From Date'
		dataType: dateTime
		sourceColumn: effective_from_date
		summarizeBy: none
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	column 'Effective To Date'
		dataType: dateTime
		sourceColumn: effective_to_date
		summarizeBy: none
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	column 'Is Current'
		dataType: boolean
		sourceColumn: is_current
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Scd Version'
		dataType: int64
		sourceColumn: scd_version
		summarizeBy: sum
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Dw Hash Diff'
		dataType: string
		sourceColumn: dw_hash_diff
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Record Source'
		dataType: string
		sourceColumn: record_source
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	partition dim_product = m
		mode: import
		source =
				let
				    Path    = DataFolder & "dim_product.csv",
				    Source  = Csv.Document(File.Contents(Path), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Chosen  = Table.SelectColumns(Headers, {"product_key", "product_id", "product_name", "category", "subcategory", "brand", "uom", "base_price_zar", "base_cost_zar", "regulated", "hazard_class", "shelf_life_days", "base_unit_margin_zar", "base_margin_pct", "price_regime", "reporting_line", "effective_from_date", "effective_to_date", "is_current", "scd_version", "dw_hash_diff", "record_source"}),
				    Typed   = Table.TransformColumnTypes(Chosen, {{"product_key", Int64.Type}, {"product_id", type text}, {"product_name", type text}, {"category", type text}, {"subcategory", type text}, {"brand", type text}, {"uom", type text}, {"base_price_zar", type number}, {"base_cost_zar", type number}, {"regulated", type logical}, {"hazard_class", type text}, {"shelf_life_days", Int64.Type}, {"base_unit_margin_zar", type number}, {"base_margin_pct", type number}, {"price_regime", type text}, {"reporting_line", type text}, {"effective_from_date", type datetime}, {"effective_to_date", type datetime}, {"is_current", type logical}, {"scd_version", Int64.Type}, {"dw_hash_diff", type text}, {"record_source", type text}})
				in
				    Typed
