table dim_site

	column 'Site Key'
		dataType: int64
		sourceColumn: site_key
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Site ID'
		dataType: string
		sourceColumn: site_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Site Name'
		dataType: string
		sourceColumn: site_name
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Country Code'
		dataType: string
		sourceColumn: country_code
		summarizeBy: none
		dataCategory: Country
		annotation SummarizationSetBy = "Automatic"

	column 'Province'
		dataType: string
		sourceColumn: province
		summarizeBy: none
		dataCategory: StateOrProvince
		annotation SummarizationSetBy = "Automatic"

	column 'City'
		dataType: string
		sourceColumn: city
		summarizeBy: none
		dataCategory: City
		annotation SummarizationSetBy = "Automatic"

	column 'Urban Class'
		dataType: string
		sourceColumn: urban_class
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Site Type'
		dataType: string
		sourceColumn: site_type
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Ownership Model'
		dataType: string
		sourceColumn: ownership_model
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Site Status'
		dataType: string
		sourceColumn: site_status
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Latitude'
		dataType: double
		sourceColumn: latitude
		summarizeBy: none
		dataCategory: Latitude
		annotation SummarizationSetBy = "Automatic"

	column 'Longitude'
		dataType: double
		sourceColumn: longitude
		summarizeBy: none
		dataCategory: Longitude
		annotation SummarizationSetBy = "Automatic"

	column 'On National Route'
		dataType: boolean
		sourceColumn: on_national_route
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Forecourt Lanes'
		dataType: int64
		sourceColumn: forecourt_lanes
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Has Convenience'
		dataType: boolean
		sourceColumn: has_convenience
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Has QSR'
		dataType: boolean
		sourceColumn: has_qsr
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Has Car Wash'
		dataType: boolean
		sourceColumn: has_car_wash
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Has EV Charging'
		dataType: boolean
		sourceColumn: has_ev_charging
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Has Solar'
		dataType: boolean
		sourceColumn: has_solar
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Has LPG'
		dataType: boolean
		sourceColumn: has_lpg
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Is 24 Hour'
		dataType: boolean
		sourceColumn: is_24_hour
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Opened Date'
		dataType: dateTime
		sourceColumn: opened_date
		summarizeBy: none
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	column 'Demand Index'
		dataType: double
		sourceColumn: demand_index
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Demand Band'
		dataType: string
		sourceColumn: demand_band
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Offer Tier'
		dataType: string
		sourceColumn: offer_tier
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'New Energy Profile'
		dataType: string
		sourceColumn: new_energy_profile
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Site Age Years'
		dataType: double
		sourceColumn: site_age_years
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Is South Africa'
		dataType: boolean
		sourceColumn: is_south_africa
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Effective From Date'
		dataType: dateTime
		sourceColumn: effective_from_date
		summarizeBy: none
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	column 'Effective To Date'
		dataType: dateTime
		sourceColumn: effective_to_date
		summarizeBy: none
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	column 'Is Current'
		dataType: boolean
		sourceColumn: is_current
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Scd Version'
		dataType: int64
		sourceColumn: scd_version
		summarizeBy: sum
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Dw Hash Diff'
		dataType: string
		sourceColumn: dw_hash_diff
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Record Source'
		dataType: string
		sourceColumn: record_source
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	partition dim_site = m
		mode: import
		source =
				let
				    Path    = DataFolder & "dim_site.csv",
				    Source  = Csv.Document(File.Contents(Path), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Chosen  = Table.SelectColumns(Headers, {"site_key", "site_id", "site_name", "country_code", "province", "city", "urban_class", "site_type", "ownership_model", "site_status", "latitude", "longitude", "on_national_route", "forecourt_lanes", "has_convenience", "has_qsr", "has_car_wash", "has_ev_charging", "has_solar", "has_lpg", "is_24_hour", "opened_date", "demand_index", "demand_band", "offer_tier", "new_energy_profile", "site_age_years", "is_south_africa", "effective_from_date", "effective_to_date", "is_current", "scd_version", "dw_hash_diff", "record_source"}),
				    Typed   = Table.TransformColumnTypes(Chosen, {{"site_key", Int64.Type}, {"site_id", type text}, {"site_name", type text}, {"country_code", type text}, {"province", type text}, {"city", type text}, {"urban_class", type text}, {"site_type", type text}, {"ownership_model", type text}, {"site_status", type text}, {"latitude", type number}, {"longitude", type number}, {"on_national_route", type logical}, {"forecourt_lanes", Int64.Type}, {"has_convenience", type logical}, {"has_qsr", type logical}, {"has_car_wash", type logical}, {"has_ev_charging", type logical}, {"has_solar", type logical}, {"has_lpg", type logical}, {"is_24_hour", type logical}, {"opened_date", type datetime}, {"demand_index", type number}, {"demand_band", type text}, {"offer_tier", type text}, {"new_energy_profile", type text}, {"site_age_years", type number}, {"is_south_africa", type logical}, {"effective_from_date", type datetime}, {"effective_to_date", type datetime}, {"is_current", type logical}, {"scd_version", Int64.Type}, {"dw_hash_diff", type text}, {"record_source", type text}})
				in
				    Typed
