table dim_date
	dataCategory: Time

	column 'Date Key'
		dataType: int64
		sourceColumn: date_key
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Full Date'
		dataType: dateTime
		sourceColumn: full_date
		summarizeBy: none
		isKey
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	column 'Day Of Month'
		dataType: int64
		sourceColumn: day_of_month
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Day Of Week'
		dataType: int64
		sourceColumn: day_of_week
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Day Name'
		dataType: string
		sourceColumn: day_name
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Day Of Year'
		dataType: int64
		sourceColumn: day_of_year
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Week Of Year'
		dataType: int64
		sourceColumn: week_of_year
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Month Number'
		dataType: int64
		sourceColumn: month_number
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Month Name'
		dataType: string
		sourceColumn: month_name
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Quarter Number'
		dataType: int64
		sourceColumn: quarter_number
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Quarter Name'
		dataType: string
		sourceColumn: quarter_name
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Calendar Year'
		dataType: int64
		sourceColumn: calendar_year
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Fiscal Year'
		dataType: int64
		sourceColumn: fiscal_year
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Fiscal Quarter'
		dataType: int64
		sourceColumn: fiscal_quarter
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Fiscal Period'
		dataType: int64
		sourceColumn: fiscal_period
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Is Weekend'
		dataType: boolean
		sourceColumn: is_weekend
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Is Public Holiday ZA'
		dataType: boolean
		sourceColumn: is_public_holiday_za
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Is Trading Day'
		dataType: boolean
		sourceColumn: is_trading_day
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Season Southern'
		dataType: string
		sourceColumn: season_southern
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'School Holiday ZA'
		dataType: boolean
		sourceColumn: school_holiday_za
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Year Month'
		dataType: string
		sourceColumn: year_month
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Fiscal Year Label'
		dataType: string
		sourceColumn: fiscal_year_label
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Is Non Working Day'
		dataType: boolean
		sourceColumn: is_non_working_day
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	partition dim_date = m
		mode: import
		source =
				let
				    Path    = DataFolder & "dim_date.csv",
				    Source  = Csv.Document(File.Contents(Path), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Chosen  = Table.SelectColumns(Headers, {"date_key", "full_date", "day_of_month", "day_of_week", "day_name", "day_of_year", "week_of_year", "month_number", "month_name", "quarter_number", "quarter_name", "calendar_year", "fiscal_year", "fiscal_quarter", "fiscal_period", "is_weekend", "is_public_holiday_za", "is_trading_day", "season_southern", "school_holiday_za", "year_month", "fiscal_year_label", "is_non_working_day"}),
				    Typed   = Table.TransformColumnTypes(Chosen, {{"date_key", Int64.Type}, {"full_date", type datetime}, {"day_of_month", Int64.Type}, {"day_of_week", Int64.Type}, {"day_name", type text}, {"day_of_year", Int64.Type}, {"week_of_year", Int64.Type}, {"month_number", Int64.Type}, {"month_name", type text}, {"quarter_number", Int64.Type}, {"quarter_name", type text}, {"calendar_year", Int64.Type}, {"fiscal_year", Int64.Type}, {"fiscal_quarter", Int64.Type}, {"fiscal_period", Int64.Type}, {"is_weekend", type logical}, {"is_public_holiday_za", type logical}, {"is_trading_day", type logical}, {"season_southern", type text}, {"school_holiday_za", type logical}, {"year_month", type text}, {"fiscal_year_label", type text}, {"is_non_working_day", type logical}})
				in
				    Typed
