table fct_retail_fuel_sales

	column 'Transaction ID'
		dataType: string
		sourceColumn: transaction_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Transaction Timestamp'
		dataType: dateTime
		sourceColumn: transaction_ts
		summarizeBy: none
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	column 'Date Key'
		dataType: int64
		sourceColumn: date_key
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Time Key'
		dataType: int64
		sourceColumn: time_key
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Site Key'
		dataType: int64
		sourceColumn: site_key
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Product Key'
		dataType: int64
		sourceColumn: product_key
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Site ID'
		dataType: string
		sourceColumn: site_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Product ID'
		dataType: string
		sourceColumn: product_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Province'
		dataType: string
		sourceColumn: province
		summarizeBy: none
		dataCategory: StateOrProvince
		annotation SummarizationSetBy = "Automatic"

	column 'City'
		dataType: string
		sourceColumn: city
		summarizeBy: none
		dataCategory: City
		annotation SummarizationSetBy = "Automatic"

	column 'Country Code'
		dataType: string
		sourceColumn: country_code
		summarizeBy: none
		dataCategory: Country
		annotation SummarizationSetBy = "Automatic"

	column 'Urban Class'
		dataType: string
		sourceColumn: urban_class
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Site Type'
		dataType: string
		sourceColumn: site_type
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Ownership Model'
		dataType: string
		sourceColumn: ownership_model
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Demand Band'
		dataType: string
		sourceColumn: demand_band
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Product Name'
		dataType: string
		sourceColumn: product_name
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Fuel Grade'
		dataType: string
		sourceColumn: fuel_grade
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Reporting Line'
		dataType: string
		sourceColumn: reporting_line
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Is Regulated Price'
		dataType: boolean
		sourceColumn: is_regulated_price
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Is Unmatched Site'
		dataType: boolean
		sourceColumn: is_unmatched_site
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Is Unmatched Product'
		dataType: boolean
		sourceColumn: is_unmatched_product
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Pump Number'
		dataType: int64
		sourceColumn: pump_number
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Forecourt Lane'
		dataType: int64
		sourceColumn: forecourt_lane
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Shift Name'
		dataType: string
		sourceColumn: shift_name
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Payment Method'
		dataType: string
		sourceColumn: payment_method
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Loyalty Flag'
		dataType: boolean
		sourceColumn: loyalty_flag
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Loyalty Member ID'
		dataType: string
		sourceColumn: loyalty_member_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Is Fleet Sale'
		dataType: boolean
		sourceColumn: is_fleet_sale
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Litres'
		dataType: double
		sourceColumn: litres
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Gross Sales (R)'
		dataType: decimal
		sourceColumn: gross_sales_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Cogs (R)'
		dataType: decimal
		sourceColumn: cogs_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Gross Margin (R)'
		dataType: decimal
		sourceColumn: gross_margin_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Unit Price (R)'
		dataType: double
		sourceColumn: unit_price_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Line Margin %'
		dataType: double
		sourceColumn: line_margin_pct
		summarizeBy: none
		formatString: 0.0%
		annotation SummarizationSetBy = "Automatic"

	column 'Margin Cents Per Litre'
		dataType: double
		sourceColumn: margin_cents_per_litre
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Source System Code'
		dataType: string
		sourceColumn: source_system_code
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Ingested At'
		dataType: dateTime
		sourceColumn: ingested_at
		summarizeBy: none
		isHidden
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	column 'Cleansed At'
		dataType: dateTime
		sourceColumn: _cleansed_at
		summarizeBy: none
		isHidden
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	partition fct_retail_fuel_sales = m
		mode: import
		source =
				let
				    Path    = DataFolder & "fct_retail_fuel_sales.csv",
				    Source  = Csv.Document(File.Contents(Path), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Chosen  = Table.SelectColumns(Headers, {"transaction_id", "transaction_ts", "date_key", "time_key", "site_key", "product_key", "site_id", "product_id", "province", "city", "country_code", "urban_class", "site_type", "ownership_model", "demand_band", "product_name", "fuel_grade", "reporting_line", "is_regulated_price", "is_unmatched_site", "is_unmatched_product", "pump_number", "forecourt_lane", "shift_name", "payment_method", "loyalty_flag", "loyalty_member_id", "is_fleet_sale", "litres", "gross_sales_zar", "cogs_zar", "gross_margin_zar", "unit_price_zar", "line_margin_pct", "margin_cents_per_litre", "source_system_code", "ingested_at", "_cleansed_at"}),
				    Typed   = Table.TransformColumnTypes(Chosen, {{"transaction_id", type text}, {"transaction_ts", type datetime}, {"date_key", Int64.Type}, {"time_key", Int64.Type}, {"site_key", Int64.Type}, {"product_key", Int64.Type}, {"site_id", type text}, {"product_id", type text}, {"province", type text}, {"city", type text}, {"country_code", type text}, {"urban_class", type text}, {"site_type", type text}, {"ownership_model", type text}, {"demand_band", type text}, {"product_name", type text}, {"fuel_grade", type text}, {"reporting_line", type text}, {"is_regulated_price", type logical}, {"is_unmatched_site", type logical}, {"is_unmatched_product", type logical}, {"pump_number", Int64.Type}, {"forecourt_lane", Int64.Type}, {"shift_name", type text}, {"payment_method", type text}, {"loyalty_flag", type logical}, {"loyalty_member_id", type text}, {"is_fleet_sale", type logical}, {"litres", type number}, {"gross_sales_zar", type number}, {"cogs_zar", type number}, {"gross_margin_zar", type number}, {"unit_price_zar", type number}, {"line_margin_pct", type number}, {"margin_cents_per_litre", type number}, {"source_system_code", type text}, {"ingested_at", type datetime}, {"_cleansed_at", type datetime}})
				in
				    Typed
