table fct_commercial_orders

	column 'Order ID'
		dataType: string
		sourceColumn: order_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Order Timestamp'
		dataType: dateTime
		sourceColumn: order_ts
		summarizeBy: none
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	column 'Date Key'
		dataType: int64
		sourceColumn: date_key
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Customer Key'
		dataType: int64
		sourceColumn: customer_key
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Product Key'
		dataType: int64
		sourceColumn: product_key
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Is Unmatched Customer'
		dataType: boolean
		sourceColumn: is_unmatched_customer
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Customer ID'
		dataType: string
		sourceColumn: customer_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Contract ID'
		dataType: string
		sourceColumn: contract_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Product ID'
		dataType: string
		sourceColumn: product_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Customer Name'
		dataType: string
		sourceColumn: customer_name
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Sector'
		dataType: string
		sourceColumn: sector
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Segment'
		dataType: string
		sourceColumn: segment
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Credit Band'
		dataType: string
		sourceColumn: credit_band
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Credit Risk Tier'
		dataType: string
		sourceColumn: credit_risk_tier
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Service Model'
		dataType: string
		sourceColumn: service_model
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Is Industrial'
		dataType: boolean
		sourceColumn: is_industrial
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Product Name'
		dataType: string
		sourceColumn: product_name
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Reporting Line'
		dataType: string
		sourceColumn: reporting_line
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Channel'
		dataType: string
		sourceColumn: channel
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Order Status'
		dataType: string
		sourceColumn: order_status
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Requested Delivery Date'
		dataType: dateTime
		sourceColumn: requested_delivery_date
		summarizeBy: none
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	column 'Payment Terms Days'
		dataType: int64
		sourceColumn: payment_terms_days
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Volume Litres'
		dataType: double
		sourceColumn: volume_litres
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'List Price (R)'
		dataType: double
		sourceColumn: list_price_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Discount Cents Per Litre'
		dataType: double
		sourceColumn: discount_cents_per_litre
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Net Price (R)'
		dataType: double
		sourceColumn: net_price_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Revenue (R)'
		dataType: decimal
		sourceColumn: revenue_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Cogs (R)'
		dataType: decimal
		sourceColumn: cogs_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Gross Margin (R)'
		dataType: decimal
		sourceColumn: gross_margin_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Discount Value (R)'
		dataType: decimal
		sourceColumn: discount_value_zar
		summarizeBy: sum
		formatString: "R"#,0.00
		annotation SummarizationSetBy = "Automatic"

	column 'Margin %'
		dataType: double
		sourceColumn: margin_pct
		summarizeBy: none
		formatString: 0.0%
		annotation SummarizationSetBy = "Automatic"

	column 'Margin Cents Per Litre'
		dataType: double
		sourceColumn: margin_cents_per_litre
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Is Open Order'
		dataType: boolean
		sourceColumn: is_open_order
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Is Cancelled'
		dataType: boolean
		sourceColumn: is_cancelled
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Order Size Band'
		dataType: string
		sourceColumn: order_size_band
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Source System Code'
		dataType: string
		sourceColumn: source_system_code
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Ingested At'
		dataType: dateTime
		sourceColumn: ingested_at
		summarizeBy: none
		isHidden
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	column 'Cleansed At'
		dataType: dateTime
		sourceColumn: _cleansed_at
		summarizeBy: none
		isHidden
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	measure 'Commercial Revenue' = SUM ( fct_commercial_orders[Revenue (R)] )
		formatString: "R"#,0
		displayFolder: Commercial

	measure 'Commercial Margin' = SUM ( fct_commercial_orders[Gross Margin (R)] )
		formatString: "R"#,0
		displayFolder: Commercial

	measure 'Unmatched Customer Revenue %' = DIVIDE ( CALCULATE ( [Commercial Revenue], fct_commercial_orders[Customer Key] = -1 ), [Commercial Revenue] )
		formatString: 0.00%
		displayFolder: Data quality

	partition fct_commercial_orders = m
		mode: import
		source =
				let
				    Path    = DataFolder & "fct_commercial_orders.csv",
				    Source  = Csv.Document(File.Contents(Path), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Chosen  = Table.SelectColumns(Headers, {"order_id", "order_ts", "date_key", "customer_key", "product_key", "is_unmatched_customer", "customer_id", "contract_id", "product_id", "customer_name", "sector", "segment", "credit_band", "credit_risk_tier", "service_model", "is_industrial", "product_name", "reporting_line", "channel", "order_status", "requested_delivery_date", "payment_terms_days", "volume_litres", "list_price_zar", "discount_cents_per_litre", "net_price_zar", "revenue_zar", "cogs_zar", "gross_margin_zar", "discount_value_zar", "margin_pct", "margin_cents_per_litre", "is_open_order", "is_cancelled", "order_size_band", "source_system_code", "ingested_at", "_cleansed_at"}),
				    Typed   = Table.TransformColumnTypes(Chosen, {{"order_id", type text}, {"order_ts", type datetime}, {"date_key", Int64.Type}, {"customer_key", Int64.Type}, {"product_key", Int64.Type}, {"is_unmatched_customer", type logical}, {"customer_id", type text}, {"contract_id", type text}, {"product_id", type text}, {"customer_name", type text}, {"sector", type text}, {"segment", type text}, {"credit_band", type text}, {"credit_risk_tier", type text}, {"service_model", type text}, {"is_industrial", type logical}, {"product_name", type text}, {"reporting_line", type text}, {"channel", type text}, {"order_status", type text}, {"requested_delivery_date", type datetime}, {"payment_terms_days", Int64.Type}, {"volume_litres", type number}, {"list_price_zar", type number}, {"discount_cents_per_litre", type number}, {"net_price_zar", type number}, {"revenue_zar", type number}, {"cogs_zar", type number}, {"gross_margin_zar", type number}, {"discount_value_zar", type number}, {"margin_pct", type number}, {"margin_cents_per_litre", type number}, {"is_open_order", type logical}, {"is_cancelled", type logical}, {"order_size_band", type text}, {"source_system_code", type text}, {"ingested_at", type datetime}, {"_cleansed_at", type datetime}})
				in
				    Typed
