table fct_deliveries

	column 'Delivery ID'
		dataType: string
		sourceColumn: delivery_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Planned Arrival Timestamp'
		dataType: dateTime
		sourceColumn: planned_arrival_ts
		summarizeBy: none
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	column 'Actual Arrival Timestamp'
		dataType: dateTime
		sourceColumn: actual_arrival_ts
		summarizeBy: none
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	column 'Date Key'
		dataType: int64
		sourceColumn: date_key
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Destination Site Key'
		dataType: int64
		sourceColumn: destination_site_key
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Product Key'
		dataType: int64
		sourceColumn: product_key
		summarizeBy: none
		isHidden
		annotation SummarizationSetBy = "Automatic"

	column 'Is Unmatched Destination'
		dataType: boolean
		sourceColumn: is_unmatched_destination
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Route ID'
		dataType: string
		sourceColumn: route_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Origin Terminal ID'
		dataType: string
		sourceColumn: origin_terminal_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Destination Site ID'
		dataType: string
		sourceColumn: destination_site_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Vehicle ID'
		dataType: string
		sourceColumn: vehicle_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Driver ID'
		dataType: string
		sourceColumn: driver_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Carrier ID'
		dataType: string
		sourceColumn: carrier_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Product ID'
		dataType: string
		sourceColumn: product_id
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Province'
		dataType: string
		sourceColumn: province
		summarizeBy: none
		dataCategory: StateOrProvince
		annotation SummarizationSetBy = "Automatic"

	column 'City'
		dataType: string
		sourceColumn: city
		summarizeBy: none
		dataCategory: City
		annotation SummarizationSetBy = "Automatic"

	column 'Urban Class'
		dataType: string
		sourceColumn: urban_class
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Product Name'
		dataType: string
		sourceColumn: product_name
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Planned Litres'
		dataType: double
		sourceColumn: planned_litres
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Delivered Litres'
		dataType: double
		sourceColumn: delivered_litres
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Fill Rate %'
		dataType: double
		sourceColumn: fill_rate_pct
		summarizeBy: none
		formatString: 0.0%
		annotation SummarizationSetBy = "Automatic"

	column 'Distance km'
		dataType: double
		sourceColumn: distance_km
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Drop Count'
		dataType: int64
		sourceColumn: drop_count
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Delay Minutes'
		dataType: int64
		sourceColumn: delay_minutes
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Delivery Status'
		dataType: string
		sourceColumn: delivery_status
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Reason Code'
		dataType: string
		sourceColumn: reason_code
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Is On Time'
		dataType: boolean
		sourceColumn: is_on_time
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Is In Full'
		dataType: boolean
		sourceColumn: is_in_full
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Is OTIF'
		dataType: boolean
		sourceColumn: is_otif
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Punctuality Band'
		dataType: string
		sourceColumn: punctuality_band
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'km Per Drop'
		dataType: double
		sourceColumn: km_per_drop
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Litres Per km'
		dataType: double
		sourceColumn: litres_per_km
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Source System Code'
		dataType: string
		sourceColumn: source_system_code
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Ingested At'
		dataType: dateTime
		sourceColumn: ingested_at
		summarizeBy: none
		isHidden
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	column 'Cleansed At'
		dataType: dateTime
		sourceColumn: _cleansed_at
		summarizeBy: none
		isHidden
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	measure 'Deliveries' = COUNTROWS ( fct_deliveries )
		formatString: #,0
		displayFolder: Supply

	measure 'OTIF Deliveries' = CALCULATE ( [Deliveries], fct_deliveries[Is OTIF] = TRUE () )
		formatString: #,0
		displayFolder: Supply

	measure 'OTIF %' = DIVIDE ( [OTIF Deliveries], [Deliveries] )
		formatString: 0.0%
		displayFolder: Supply

	measure 'Average Delay (min)' = AVERAGE ( fct_deliveries[Delay Minutes] )
		formatString: #,0
		displayFolder: Supply

	partition fct_deliveries = m
		mode: import
		source =
				let
				    Path    = DataFolder & "fct_deliveries.csv",
				    Source  = Csv.Document(File.Contents(Path), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Chosen  = Table.SelectColumns(Headers, {"delivery_id", "planned_arrival_ts", "actual_arrival_ts", "date_key", "destination_site_key", "product_key", "is_unmatched_destination", "route_id", "origin_terminal_id", "destination_site_id", "vehicle_id", "driver_id", "carrier_id", "product_id", "province", "city", "urban_class", "product_name", "planned_litres", "delivered_litres", "fill_rate_pct", "distance_km", "drop_count", "delay_minutes", "delivery_status", "reason_code", "is_on_time", "is_in_full", "is_otif", "punctuality_band", "km_per_drop", "litres_per_km", "source_system_code", "ingested_at", "_cleansed_at"}),
				    Typed   = Table.TransformColumnTypes(Chosen, {{"delivery_id", type text}, {"planned_arrival_ts", type datetime}, {"actual_arrival_ts", type datetime}, {"date_key", Int64.Type}, {"destination_site_key", Int64.Type}, {"product_key", Int64.Type}, {"is_unmatched_destination", type logical}, {"route_id", type text}, {"origin_terminal_id", type text}, {"destination_site_id", type text}, {"vehicle_id", type text}, {"driver_id", type text}, {"carrier_id", type text}, {"product_id", type text}, {"province", type text}, {"city", type text}, {"urban_class", type text}, {"product_name", type text}, {"planned_litres", type number}, {"delivered_litres", type number}, {"fill_rate_pct", type number}, {"distance_km", type number}, {"drop_count", Int64.Type}, {"delay_minutes", Int64.Type}, {"delivery_status", type text}, {"reason_code", type text}, {"is_on_time", type logical}, {"is_in_full", type logical}, {"is_otif", type logical}, {"punctuality_band", type text}, {"km_per_drop", type number}, {"litres_per_km", type number}, {"source_system_code", type text}, {"ingested_at", type datetime}, {"_cleansed_at", type datetime}})
				in
				    Typed
