table obs_reconciliation_controls

	column 'Control Code'
		dataType: string
		sourceColumn: control_code
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Control Description'
		dataType: string
		sourceColumn: control_description
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Control Owner'
		dataType: string
		sourceColumn: control_owner
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Expected Value'
		dataType: double
		sourceColumn: expected_value
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Actual Value'
		dataType: double
		sourceColumn: actual_value
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Variance Absolute'
		dataType: double
		sourceColumn: variance_absolute
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Variance %'
		dataType: double
		sourceColumn: variance_pct
		summarizeBy: none
		formatString: 0.0%
		annotation SummarizationSetBy = "Automatic"

	column 'Tolerance %'
		dataType: decimal
		sourceColumn: tolerance_pct
		summarizeBy: none
		formatString: 0.0%
		annotation SummarizationSetBy = "Automatic"

	column 'Is Passing'
		dataType: boolean
		sourceColumn: is_passing
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Evaluated At'
		dataType: dateTime
		sourceColumn: evaluated_at
		summarizeBy: none
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	measure 'Controls' = COUNTROWS ( obs_reconciliation_controls )
		formatString: #,0
		displayFolder: Data quality

	measure 'Controls Passing' = CALCULATE ( [Controls], obs_reconciliation_controls[Is Passing] = TRUE () )
		formatString: #,0
		displayFolder: Data quality

	measure 'Control Pass Rate %' = DIVIDE ( [Controls Passing], [Controls] )
		formatString: 0.0%
		displayFolder: Data quality

	measure 'Worst Control Variance %' = MAX ( obs_reconciliation_controls[Variance %] )
		formatString: 0.000%
		displayFolder: Data quality

	partition obs_reconciliation_controls = m
		mode: import
		source =
				let
				    Path    = DataFolder & "obs_reconciliation_controls.csv",
				    Source  = Csv.Document(File.Contents(Path), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Chosen  = Table.SelectColumns(Headers, {"control_code", "control_description", "control_owner", "expected_value", "actual_value", "variance_absolute", "variance_pct", "tolerance_pct", "is_passing", "evaluated_at"}),
				    Typed   = Table.TransformColumnTypes(Chosen, {{"control_code", type text}, {"control_description", type text}, {"control_owner", type text}, {"expected_value", type number}, {"actual_value", type number}, {"variance_absolute", type number}, {"variance_pct", type number}, {"tolerance_pct", type number}, {"is_passing", type logical}, {"evaluated_at", type datetime}})
				in
				    Typed
