table obs_cleansing_summary

	column 'Table Name'
		dataType: string
		sourceColumn: table_name
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Raw Rows'
		dataType: int64
		sourceColumn: raw_rows
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Cleansed Rows'
		dataType: int64
		sourceColumn: cleansed_rows
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Quarantined Rows'
		dataType: int64
		sourceColumn: quarantined_rows
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Duplicates Removed'
		dataType: int64
		sourceColumn: duplicates_removed
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Quarantine Rate %'
		dataType: double
		sourceColumn: quarantine_rate_pct
		summarizeBy: none
		formatString: 0.0%
		annotation SummarizationSetBy = "Automatic"

	column 'Duplicate Rate %'
		dataType: double
		sourceColumn: duplicate_rate_pct
		summarizeBy: none
		formatString: 0.0%
		annotation SummarizationSetBy = "Automatic"

	column 'Pass Rate %'
		dataType: double
		sourceColumn: pass_rate_pct
		summarizeBy: none
		formatString: 0.0%
		annotation SummarizationSetBy = "Automatic"

	column 'Quarantine Status'
		dataType: string
		sourceColumn: quarantine_status
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Row Count Reconciles'
		dataType: boolean
		sourceColumn: row_count_reconciles
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Evaluated At'
		dataType: dateTime
		sourceColumn: evaluated_at
		summarizeBy: none
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	measure 'Rows Landed' = SUM ( obs_cleansing_summary[Raw Rows] )
		formatString: #,0
		displayFolder: Data quality

	measure 'Rows Cleansed' = SUM ( obs_cleansing_summary[Cleansed Rows] )
		formatString: #,0
		displayFolder: Data quality

	measure 'Rows Quarantined' = SUM ( obs_cleansing_summary[Quarantined Rows] )
		formatString: #,0
		displayFolder: Data quality

	measure 'Quarantine Rate %' = DIVIDE ( [Rows Quarantined], [Rows Landed] )
		formatString: 0.00%
		displayFolder: Data quality

	measure 'Duplicate Rate %' = DIVIDE ( SUM ( obs_cleansing_summary[Duplicates Removed] ), [Rows Landed] )
		formatString: 0.00%
		displayFolder: Data quality

	measure 'Tables Monitored' = DISTINCTCOUNT ( obs_cleansing_summary[Table Name] )
		formatString: #,0
		displayFolder: Data quality

	measure 'Tables Not Reconciling' = CALCULATE ( [Tables Monitored], obs_cleansing_summary[Row Count Reconciles] = FALSE () )
		formatString: #,0
		displayFolder: Data quality

	partition obs_cleansing_summary = m
		mode: import
		source =
				let
				    Path    = DataFolder & "obs_cleansing_summary.csv",
				    Source  = Csv.Document(File.Contents(Path), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Chosen  = Table.SelectColumns(Headers, {"table_name", "raw_rows", "cleansed_rows", "quarantined_rows", "duplicates_removed", "quarantine_rate_pct", "duplicate_rate_pct", "pass_rate_pct", "quarantine_status", "row_count_reconciles", "evaluated_at"}),
				    Typed   = Table.TransformColumnTypes(Chosen, {{"table_name", type text}, {"raw_rows", Int64.Type}, {"cleansed_rows", Int64.Type}, {"quarantined_rows", Int64.Type}, {"duplicates_removed", Int64.Type}, {"quarantine_rate_pct", type number}, {"duplicate_rate_pct", type number}, {"pass_rate_pct", type number}, {"quarantine_status", type text}, {"row_count_reconciles", type logical}, {"evaluated_at", type datetime}})
				in
				    Typed
