table obs_quarantine_reasons

	column 'Table Name'
		dataType: string
		sourceColumn: table_name
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Failed Rule'
		dataType: string
		sourceColumn: failed_rule
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Failure Count'
		dataType: int64
		sourceColumn: failure_count
		summarizeBy: sum
		annotation SummarizationSetBy = "Automatic"

	column 'Failure Category'
		dataType: string
		sourceColumn: failure_category
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Likely Owner'
		dataType: string
		sourceColumn: likely_owner
		summarizeBy: none
		annotation SummarizationSetBy = "Automatic"

	column 'Evaluated At'
		dataType: dateTime
		sourceColumn: evaluated_at
		summarizeBy: none
		formatString: yyyy-mm-dd
		annotation SummarizationSetBy = "Automatic"

	measure 'Rows Rejected' = SUM ( obs_quarantine_reasons[Failure Count] )
		formatString: #,0
		displayFolder: Data quality

	measure 'Distinct Rules Firing' = DISTINCTCOUNT ( obs_quarantine_reasons[Failed Rule] )
		formatString: #,0
		displayFolder: Data quality

	partition obs_quarantine_reasons = m
		mode: import
		source =
				let
				    Path    = DataFolder & "obs_quarantine_reasons.csv",
				    Source  = Csv.Document(File.Contents(Path), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Chosen  = Table.SelectColumns(Headers, {"table_name", "failed_rule", "failure_count", "failure_category", "likely_owner", "evaluated_at"}),
				    Typed   = Table.TransformColumnTypes(Chosen, {{"table_name", type text}, {"failed_rule", type text}, {"failure_count", Int64.Type}, {"failure_category", type text}, {"likely_owner", type text}, {"evaluated_at", type datetime}})
				in
				    Typed
